/* tslint:disable */
/* eslint-disable */
/**
 * Hyperswitch - API Documentation
 *  ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app\'s client  |  Never share your secret api keys. Keep them guarded and secure. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hyperswitch@juspay.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DisputeResponse,
  DisputeStage,
  DisputeStatus,
} from '../models/index';
import {
    DisputeResponseFromJSON,
    DisputeResponseToJSON,
    DisputeStageFromJSON,
    DisputeStageToJSON,
    DisputeStatusFromJSON,
    DisputeStatusToJSON,
} from '../models/index';

export interface ListDisputesRequest {
    limit?: number | null;
    disputeStatus?: DisputeStatus | null;
    disputeStage?: DisputeStage | null;
    reason?: string | null;
    connector?: string | null;
    receivedTime?: Date | null;
    receivedTimeLt?: Date | null;
    receivedTimeGt?: Date | null;
    receivedTimeLte?: Date | null;
    receivedTimeGte?: Date | null;
}

export interface RetrieveADisputeRequest {
    disputeId: string;
    forceSync?: boolean | null;
}

/**
 * 
 */
export class DisputesApi extends runtime.BaseAPI {

    /**
     * Lists all the Disputes for a merchant
     * Disputes - List Disputes
     */
    async listDisputesRaw(requestParameters: ListDisputesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<DisputeResponse>>> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['disputeStatus'] != null) {
            queryParameters['dispute_status'] = requestParameters['disputeStatus'];
        }

        if (requestParameters['disputeStage'] != null) {
            queryParameters['dispute_stage'] = requestParameters['disputeStage'];
        }

        if (requestParameters['reason'] != null) {
            queryParameters['reason'] = requestParameters['reason'];
        }

        if (requestParameters['connector'] != null) {
            queryParameters['connector'] = requestParameters['connector'];
        }

        if (requestParameters['receivedTime'] != null) {
            queryParameters['received_time'] = (requestParameters['receivedTime'] as any).toISOString();
        }

        if (requestParameters['receivedTimeLt'] != null) {
            queryParameters['received_time.lt'] = (requestParameters['receivedTimeLt'] as any).toISOString();
        }

        if (requestParameters['receivedTimeGt'] != null) {
            queryParameters['received_time.gt'] = (requestParameters['receivedTimeGt'] as any).toISOString();
        }

        if (requestParameters['receivedTimeLte'] != null) {
            queryParameters['received_time.lte'] = (requestParameters['receivedTimeLte'] as any).toISOString();
        }

        if (requestParameters['receivedTimeGte'] != null) {
            queryParameters['received_time.gte'] = (requestParameters['receivedTimeGte'] as any).toISOString();
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["api-key"] = await this.configuration.apiKey("api-key"); // api_key authentication
        }


        let urlPath = `/disputes/list`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DisputeResponseFromJSON));
    }

    /**
     * Lists all the Disputes for a merchant
     * Disputes - List Disputes
     */
    async listDisputes(requestParameters: ListDisputesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<DisputeResponse>> {
        const response = await this.listDisputesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieves a dispute
     * Disputes - Retrieve Dispute
     */
    async retrieveADisputeRaw(requestParameters: RetrieveADisputeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DisputeResponse>> {
        if (requestParameters['disputeId'] == null) {
            throw new runtime.RequiredError(
                'disputeId',
                'Required parameter "disputeId" was null or undefined when calling retrieveADispute().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['forceSync'] != null) {
            queryParameters['force_sync'] = requestParameters['forceSync'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["api-key"] = await this.configuration.apiKey("api-key"); // api_key authentication
        }


        let urlPath = `/disputes/{dispute_id}`;
        urlPath = urlPath.replace(`{${"dispute_id"}}`, encodeURIComponent(String(requestParameters['disputeId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DisputeResponseFromJSON(jsonValue));
    }

    /**
     * Retrieves a dispute
     * Disputes - Retrieve Dispute
     */
    async retrieveADispute(requestParameters: RetrieveADisputeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DisputeResponse> {
        const response = await this.retrieveADisputeRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
