/* tslint:disable */
/* eslint-disable */
/**
 * Hyperswitch - API Documentation
 *  ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app\'s client  |  Never share your secret api keys. Keep them guarded and secure. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hyperswitch@juspay.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ContractBasedRoutingConfig,
  DecideGatewayResponse,
  DynamicRoutingFeatures,
  LinkedRoutingConfigRetrieveResponse,
  MerchantRoutingAlgorithm,
  OpenRouterDecideGatewayRequest,
  ProfileDefaultRoutingConfig,
  RoutableConnectorChoice,
  RoutingConfigRequest,
  RoutingDictionaryRecord,
  RoutingEvaluateRequest,
  RoutingEvaluateResponse,
  RoutingKind,
  SuccessBasedRoutingConfig,
  UpdateScorePayload,
  UpdateScoreResponse,
} from '../models/index';
import {
    ContractBasedRoutingConfigFromJSON,
    ContractBasedRoutingConfigToJSON,
    DecideGatewayResponseFromJSON,
    DecideGatewayResponseToJSON,
    DynamicRoutingFeaturesFromJSON,
    DynamicRoutingFeaturesToJSON,
    LinkedRoutingConfigRetrieveResponseFromJSON,
    LinkedRoutingConfigRetrieveResponseToJSON,
    MerchantRoutingAlgorithmFromJSON,
    MerchantRoutingAlgorithmToJSON,
    OpenRouterDecideGatewayRequestFromJSON,
    OpenRouterDecideGatewayRequestToJSON,
    ProfileDefaultRoutingConfigFromJSON,
    ProfileDefaultRoutingConfigToJSON,
    RoutableConnectorChoiceFromJSON,
    RoutableConnectorChoiceToJSON,
    RoutingConfigRequestFromJSON,
    RoutingConfigRequestToJSON,
    RoutingDictionaryRecordFromJSON,
    RoutingDictionaryRecordToJSON,
    RoutingEvaluateRequestFromJSON,
    RoutingEvaluateRequestToJSON,
    RoutingEvaluateResponseFromJSON,
    RoutingEvaluateResponseToJSON,
    RoutingKindFromJSON,
    RoutingKindToJSON,
    SuccessBasedRoutingConfigFromJSON,
    SuccessBasedRoutingConfigToJSON,
    UpdateScorePayloadFromJSON,
    UpdateScorePayloadToJSON,
    UpdateScoreResponseFromJSON,
    UpdateScoreResponseToJSON,
} from '../models/index';

export interface ActivateARoutingConfigRequest {
    routingAlgorithmId: string;
}

export interface CreateARoutingConfigRequest {
    routingConfigRequest: RoutingConfigRequest;
}

export interface DeactivateARoutingConfigRequest {
    routingConfigRequest: RoutingConfigRequest;
}

export interface EvaluateRoutingRulesRequest {
    openRouterDecideGatewayRequest: OpenRouterDecideGatewayRequest;
}

export interface EvaluateRoutingRulesAlternativeRequest {
    routingEvaluateRequest: RoutingEvaluateRequest;
}

export interface ListRoutingConfigsRequest {
    limit?: number | null;
    offset?: number | null;
    profileId?: string | null;
}

export interface RetrieveARoutingConfigRequest {
    routingAlgorithmId: string;
}

export interface RetrieveActiveConfigRequest {
    profileId?: string | null;
}

export interface ToggleContractRoutingAlgorithmRequest {
    accountId: string;
    profileId: string;
    enable: DynamicRoutingFeatures;
    contractBasedRoutingConfig: ContractBasedRoutingConfig;
}

export interface ToggleEliminationRoutingAlgorithmRequest {
    accountId: string;
    profileId: string;
    enable: DynamicRoutingFeatures;
}

export interface ToggleSuccessBasedDynamicRoutingAlgorithmRequest {
    accountId: string;
    profileId: string;
    enable: DynamicRoutingFeatures;
}

export interface UpdateContractBasedDynamicRoutingConfigsRequest {
    accountId: string;
    profileId: string;
    algorithmId: string;
    contractBasedRoutingConfig: ContractBasedRoutingConfig;
}

export interface UpdateDefaultConfigsForAllProfilesRequest {
    profileId: string;
    routableConnectorChoice: Array<RoutableConnectorChoice>;
}

export interface UpdateDefaultFallbackConfigRequest {
    routableConnectorChoice: Array<RoutableConnectorChoice>;
}

export interface UpdateGatewayScoresRequest {
    updateScorePayload: UpdateScorePayload;
}

export interface UpdateSuccessBasedDynamicRoutingConfigsRequest {
    accountId: string;
    profileId: string;
    algorithmId: string;
    successBasedRoutingConfig: SuccessBasedRoutingConfig;
}

/**
 * 
 */
export class RoutingApi extends runtime.BaseAPI {

    /**
     * Activate a routing config
     * Routing - Activate config
     */
    async activateARoutingConfigRaw(requestParameters: ActivateARoutingConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RoutingDictionaryRecord>> {
        if (requestParameters['routingAlgorithmId'] == null) {
            throw new runtime.RequiredError(
                'routingAlgorithmId',
                'Required parameter "routingAlgorithmId" was null or undefined when calling activateARoutingConfig().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwt_key", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["api-key"] = await this.configuration.apiKey("api-key"); // api_key authentication
        }


        let urlPath = `/routing/{routing_algorithm_id}/activate`;
        urlPath = urlPath.replace(`{${"routing_algorithm_id"}}`, encodeURIComponent(String(requestParameters['routingAlgorithmId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RoutingDictionaryRecordFromJSON(jsonValue));
    }

    /**
     * Activate a routing config
     * Routing - Activate config
     */
    async activateARoutingConfig(requestParameters: ActivateARoutingConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RoutingDictionaryRecord> {
        const response = await this.activateARoutingConfigRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a routing config
     * Routing - Create
     */
    async createARoutingConfigRaw(requestParameters: CreateARoutingConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RoutingDictionaryRecord>> {
        if (requestParameters['routingConfigRequest'] == null) {
            throw new runtime.RequiredError(
                'routingConfigRequest',
                'Required parameter "routingConfigRequest" was null or undefined when calling createARoutingConfig().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwt_key", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["api-key"] = await this.configuration.apiKey("api-key"); // api_key authentication
        }


        let urlPath = `/routing`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RoutingConfigRequestToJSON(requestParameters['routingConfigRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RoutingDictionaryRecordFromJSON(jsonValue));
    }

    /**
     * Create a routing config
     * Routing - Create
     */
    async createARoutingConfig(requestParameters: CreateARoutingConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RoutingDictionaryRecord> {
        const response = await this.createARoutingConfigRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Deactivates a routing config
     * Routing - Deactivate
     */
    async deactivateARoutingConfigRaw(requestParameters: DeactivateARoutingConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RoutingDictionaryRecord>> {
        if (requestParameters['routingConfigRequest'] == null) {
            throw new runtime.RequiredError(
                'routingConfigRequest',
                'Required parameter "routingConfigRequest" was null or undefined when calling deactivateARoutingConfig().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwt_key", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["api-key"] = await this.configuration.apiKey("api-key"); // api_key authentication
        }


        let urlPath = `/routing/deactivate`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RoutingConfigRequestToJSON(requestParameters['routingConfigRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RoutingDictionaryRecordFromJSON(jsonValue));
    }

    /**
     * Deactivates a routing config
     * Routing - Deactivate
     */
    async deactivateARoutingConfig(requestParameters: DeactivateARoutingConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RoutingDictionaryRecord> {
        const response = await this.deactivateARoutingConfigRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Evaluate routing rules
     * Routing - Evaluate
     */
    async evaluateRoutingRulesRaw(requestParameters: EvaluateRoutingRulesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DecideGatewayResponse>> {
        if (requestParameters['openRouterDecideGatewayRequest'] == null) {
            throw new runtime.RequiredError(
                'openRouterDecideGatewayRequest',
                'Required parameter "openRouterDecideGatewayRequest" was null or undefined when calling evaluateRoutingRules().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["api-key"] = await this.configuration.apiKey("api-key"); // api_key authentication
        }


        let urlPath = `/routing/evaluate`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: OpenRouterDecideGatewayRequestToJSON(requestParameters['openRouterDecideGatewayRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DecideGatewayResponseFromJSON(jsonValue));
    }

    /**
     * Evaluate routing rules
     * Routing - Evaluate
     */
    async evaluateRoutingRules(requestParameters: EvaluateRoutingRulesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DecideGatewayResponse> {
        const response = await this.evaluateRoutingRulesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Evaluate routing rules
     * Routing - Rule Evaluate
     */
    async evaluateRoutingRulesAlternativeRaw(requestParameters: EvaluateRoutingRulesAlternativeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RoutingEvaluateResponse>> {
        if (requestParameters['routingEvaluateRequest'] == null) {
            throw new runtime.RequiredError(
                'routingEvaluateRequest',
                'Required parameter "routingEvaluateRequest" was null or undefined when calling evaluateRoutingRulesAlternative().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["api-key"] = await this.configuration.apiKey("api-key"); // api_key authentication
        }


        let urlPath = `/routing/rule/evaluate`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RoutingEvaluateRequestToJSON(requestParameters['routingEvaluateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RoutingEvaluateResponseFromJSON(jsonValue));
    }

    /**
     * Evaluate routing rules
     * Routing - Rule Evaluate
     */
    async evaluateRoutingRulesAlternative(requestParameters: EvaluateRoutingRulesAlternativeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RoutingEvaluateResponse> {
        const response = await this.evaluateRoutingRulesAlternativeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List all routing configs
     * Routing - List
     */
    async listRoutingConfigsRaw(requestParameters: ListRoutingConfigsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RoutingKind>> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['profileId'] != null) {
            queryParameters['profile_id'] = requestParameters['profileId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwt_key", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["api-key"] = await this.configuration.apiKey("api-key"); // api_key authentication
        }


        let urlPath = `/routing`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RoutingKindFromJSON(jsonValue));
    }

    /**
     * List all routing configs
     * Routing - List
     */
    async listRoutingConfigs(requestParameters: ListRoutingConfigsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RoutingKind> {
        const response = await this.listRoutingConfigsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve a routing algorithm
     * Routing - Retrieve
     */
    async retrieveARoutingConfigRaw(requestParameters: RetrieveARoutingConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MerchantRoutingAlgorithm>> {
        if (requestParameters['routingAlgorithmId'] == null) {
            throw new runtime.RequiredError(
                'routingAlgorithmId',
                'Required parameter "routingAlgorithmId" was null or undefined when calling retrieveARoutingConfig().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwt_key", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["api-key"] = await this.configuration.apiKey("api-key"); // api_key authentication
        }


        let urlPath = `/routing/{routing_algorithm_id}`;
        urlPath = urlPath.replace(`{${"routing_algorithm_id"}}`, encodeURIComponent(String(requestParameters['routingAlgorithmId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MerchantRoutingAlgorithmFromJSON(jsonValue));
    }

    /**
     * Retrieve a routing algorithm
     * Routing - Retrieve
     */
    async retrieveARoutingConfig(requestParameters: RetrieveARoutingConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MerchantRoutingAlgorithm> {
        const response = await this.retrieveARoutingConfigRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve active config
     * Routing - Retrieve Config
     */
    async retrieveActiveConfigRaw(requestParameters: RetrieveActiveConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LinkedRoutingConfigRetrieveResponse>> {
        const queryParameters: any = {};

        if (requestParameters['profileId'] != null) {
            queryParameters['profile_id'] = requestParameters['profileId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwt_key", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["api-key"] = await this.configuration.apiKey("api-key"); // api_key authentication
        }


        let urlPath = `/routing/active`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LinkedRoutingConfigRetrieveResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve active config
     * Routing - Retrieve Config
     */
    async retrieveActiveConfig(requestParameters: RetrieveActiveConfigRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LinkedRoutingConfigRetrieveResponse> {
        const response = await this.retrieveActiveConfigRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve default config for profiles
     * Routing - Retrieve Default For Profile
     */
    async retrieveDefaultConfigsForAllProfilesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProfileDefaultRoutingConfig>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwt_key", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["api-key"] = await this.configuration.apiKey("api-key"); // api_key authentication
        }


        let urlPath = `/routing/default/profile`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProfileDefaultRoutingConfigFromJSON(jsonValue));
    }

    /**
     * Retrieve default config for profiles
     * Routing - Retrieve Default For Profile
     */
    async retrieveDefaultConfigsForAllProfiles(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProfileDefaultRoutingConfig> {
        const response = await this.retrieveDefaultConfigsForAllProfilesRaw(initOverrides);
        return await response.value();
    }

    /**
     * Retrieve default fallback config
     * Routing - Retrieve Default Config
     */
    async retrieveDefaultFallbackConfigRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<RoutableConnectorChoice>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwt_key", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["api-key"] = await this.configuration.apiKey("api-key"); // api_key authentication
        }


        let urlPath = `/routing/default`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(RoutableConnectorChoiceFromJSON));
    }

    /**
     * Retrieve default fallback config
     * Routing - Retrieve Default Config
     */
    async retrieveDefaultFallbackConfig(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<RoutableConnectorChoice>> {
        const response = await this.retrieveDefaultFallbackConfigRaw(initOverrides);
        return await response.value();
    }

    /**
     * Create a Contract based dynamic routing algorithm
     * Routing - Toggle Contract routing for profile
     */
    async toggleContractRoutingAlgorithmRaw(requestParameters: ToggleContractRoutingAlgorithmRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RoutingDictionaryRecord>> {
        if (requestParameters['accountId'] == null) {
            throw new runtime.RequiredError(
                'accountId',
                'Required parameter "accountId" was null or undefined when calling toggleContractRoutingAlgorithm().'
            );
        }

        if (requestParameters['profileId'] == null) {
            throw new runtime.RequiredError(
                'profileId',
                'Required parameter "profileId" was null or undefined when calling toggleContractRoutingAlgorithm().'
            );
        }

        if (requestParameters['enable'] == null) {
            throw new runtime.RequiredError(
                'enable',
                'Required parameter "enable" was null or undefined when calling toggleContractRoutingAlgorithm().'
            );
        }

        if (requestParameters['contractBasedRoutingConfig'] == null) {
            throw new runtime.RequiredError(
                'contractBasedRoutingConfig',
                'Required parameter "contractBasedRoutingConfig" was null or undefined when calling toggleContractRoutingAlgorithm().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['enable'] != null) {
            queryParameters['enable'] = requestParameters['enable'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwt_key", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["api-key"] = await this.configuration.apiKey("api-key"); // api_key authentication
        }


        let urlPath = `/account/{account_id}/business_profile/{profile_id}/dynamic_routing/contracts/toggle`;
        urlPath = urlPath.replace(`{${"account_id"}}`, encodeURIComponent(String(requestParameters['accountId'])));
        urlPath = urlPath.replace(`{${"profile_id"}}`, encodeURIComponent(String(requestParameters['profileId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ContractBasedRoutingConfigToJSON(requestParameters['contractBasedRoutingConfig']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RoutingDictionaryRecordFromJSON(jsonValue));
    }

    /**
     * Create a Contract based dynamic routing algorithm
     * Routing - Toggle Contract routing for profile
     */
    async toggleContractRoutingAlgorithm(requestParameters: ToggleContractRoutingAlgorithmRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RoutingDictionaryRecord> {
        const response = await this.toggleContractRoutingAlgorithmRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a elimination based dynamic routing algorithm
     * Routing - Toggle elimination routing for profile
     */
    async toggleEliminationRoutingAlgorithmRaw(requestParameters: ToggleEliminationRoutingAlgorithmRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RoutingDictionaryRecord>> {
        if (requestParameters['accountId'] == null) {
            throw new runtime.RequiredError(
                'accountId',
                'Required parameter "accountId" was null or undefined when calling toggleEliminationRoutingAlgorithm().'
            );
        }

        if (requestParameters['profileId'] == null) {
            throw new runtime.RequiredError(
                'profileId',
                'Required parameter "profileId" was null or undefined when calling toggleEliminationRoutingAlgorithm().'
            );
        }

        if (requestParameters['enable'] == null) {
            throw new runtime.RequiredError(
                'enable',
                'Required parameter "enable" was null or undefined when calling toggleEliminationRoutingAlgorithm().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['enable'] != null) {
            queryParameters['enable'] = requestParameters['enable'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwt_key", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["api-key"] = await this.configuration.apiKey("api-key"); // api_key authentication
        }


        let urlPath = `/account/{account_id}/business_profile/{profile_id}/dynamic_routing/elimination/toggle`;
        urlPath = urlPath.replace(`{${"account_id"}}`, encodeURIComponent(String(requestParameters['accountId'])));
        urlPath = urlPath.replace(`{${"profile_id"}}`, encodeURIComponent(String(requestParameters['profileId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RoutingDictionaryRecordFromJSON(jsonValue));
    }

    /**
     * Create a elimination based dynamic routing algorithm
     * Routing - Toggle elimination routing for profile
     */
    async toggleEliminationRoutingAlgorithm(requestParameters: ToggleEliminationRoutingAlgorithmRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RoutingDictionaryRecord> {
        const response = await this.toggleEliminationRoutingAlgorithmRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a success based dynamic routing algorithm
     * Routing - Toggle success based dynamic routing for profile
     */
    async toggleSuccessBasedDynamicRoutingAlgorithmRaw(requestParameters: ToggleSuccessBasedDynamicRoutingAlgorithmRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RoutingDictionaryRecord>> {
        if (requestParameters['accountId'] == null) {
            throw new runtime.RequiredError(
                'accountId',
                'Required parameter "accountId" was null or undefined when calling toggleSuccessBasedDynamicRoutingAlgorithm().'
            );
        }

        if (requestParameters['profileId'] == null) {
            throw new runtime.RequiredError(
                'profileId',
                'Required parameter "profileId" was null or undefined when calling toggleSuccessBasedDynamicRoutingAlgorithm().'
            );
        }

        if (requestParameters['enable'] == null) {
            throw new runtime.RequiredError(
                'enable',
                'Required parameter "enable" was null or undefined when calling toggleSuccessBasedDynamicRoutingAlgorithm().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['enable'] != null) {
            queryParameters['enable'] = requestParameters['enable'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwt_key", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["api-key"] = await this.configuration.apiKey("api-key"); // api_key authentication
        }


        let urlPath = `/account/{account_id}/business_profile/{profile_id}/dynamic_routing/success_based/toggle`;
        urlPath = urlPath.replace(`{${"account_id"}}`, encodeURIComponent(String(requestParameters['accountId'])));
        urlPath = urlPath.replace(`{${"profile_id"}}`, encodeURIComponent(String(requestParameters['profileId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RoutingDictionaryRecordFromJSON(jsonValue));
    }

    /**
     * Create a success based dynamic routing algorithm
     * Routing - Toggle success based dynamic routing for profile
     */
    async toggleSuccessBasedDynamicRoutingAlgorithm(requestParameters: ToggleSuccessBasedDynamicRoutingAlgorithmRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RoutingDictionaryRecord> {
        const response = await this.toggleSuccessBasedDynamicRoutingAlgorithmRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update contract based dynamic routing algorithm
     * Routing - Update contract based dynamic routing config for profile
     */
    async updateContractBasedDynamicRoutingConfigsRaw(requestParameters: UpdateContractBasedDynamicRoutingConfigsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RoutingDictionaryRecord>> {
        if (requestParameters['accountId'] == null) {
            throw new runtime.RequiredError(
                'accountId',
                'Required parameter "accountId" was null or undefined when calling updateContractBasedDynamicRoutingConfigs().'
            );
        }

        if (requestParameters['profileId'] == null) {
            throw new runtime.RequiredError(
                'profileId',
                'Required parameter "profileId" was null or undefined when calling updateContractBasedDynamicRoutingConfigs().'
            );
        }

        if (requestParameters['algorithmId'] == null) {
            throw new runtime.RequiredError(
                'algorithmId',
                'Required parameter "algorithmId" was null or undefined when calling updateContractBasedDynamicRoutingConfigs().'
            );
        }

        if (requestParameters['contractBasedRoutingConfig'] == null) {
            throw new runtime.RequiredError(
                'contractBasedRoutingConfig',
                'Required parameter "contractBasedRoutingConfig" was null or undefined when calling updateContractBasedDynamicRoutingConfigs().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwt_key", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["api-key"] = await this.configuration.apiKey("api-key"); // api_key authentication
        }


        let urlPath = `/account/{account_id}/business_profile/{profile_id}/dynamic_routing/contracts/config/{algorithm_id}`;
        urlPath = urlPath.replace(`{${"account_id"}}`, encodeURIComponent(String(requestParameters['accountId'])));
        urlPath = urlPath.replace(`{${"profile_id"}}`, encodeURIComponent(String(requestParameters['profileId'])));
        urlPath = urlPath.replace(`{${"algorithm_id"}}`, encodeURIComponent(String(requestParameters['algorithmId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: ContractBasedRoutingConfigToJSON(requestParameters['contractBasedRoutingConfig']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RoutingDictionaryRecordFromJSON(jsonValue));
    }

    /**
     * Update contract based dynamic routing algorithm
     * Routing - Update contract based dynamic routing config for profile
     */
    async updateContractBasedDynamicRoutingConfigs(requestParameters: UpdateContractBasedDynamicRoutingConfigsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RoutingDictionaryRecord> {
        const response = await this.updateContractBasedDynamicRoutingConfigsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update default config for profiles
     * Routing - Update Default For Profile
     */
    async updateDefaultConfigsForAllProfilesRaw(requestParameters: UpdateDefaultConfigsForAllProfilesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProfileDefaultRoutingConfig>> {
        if (requestParameters['profileId'] == null) {
            throw new runtime.RequiredError(
                'profileId',
                'Required parameter "profileId" was null or undefined when calling updateDefaultConfigsForAllProfiles().'
            );
        }

        if (requestParameters['routableConnectorChoice'] == null) {
            throw new runtime.RequiredError(
                'routableConnectorChoice',
                'Required parameter "routableConnectorChoice" was null or undefined when calling updateDefaultConfigsForAllProfiles().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwt_key", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["api-key"] = await this.configuration.apiKey("api-key"); // api_key authentication
        }


        let urlPath = `/routing/default/profile/{profile_id}`;
        urlPath = urlPath.replace(`{${"profile_id"}}`, encodeURIComponent(String(requestParameters['profileId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['routableConnectorChoice']!.map(RoutableConnectorChoiceToJSON),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProfileDefaultRoutingConfigFromJSON(jsonValue));
    }

    /**
     * Update default config for profiles
     * Routing - Update Default For Profile
     */
    async updateDefaultConfigsForAllProfiles(requestParameters: UpdateDefaultConfigsForAllProfilesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProfileDefaultRoutingConfig> {
        const response = await this.updateDefaultConfigsForAllProfilesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update default fallback config
     * Routing - Update Default Config
     */
    async updateDefaultFallbackConfigRaw(requestParameters: UpdateDefaultFallbackConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<RoutableConnectorChoice>>> {
        if (requestParameters['routableConnectorChoice'] == null) {
            throw new runtime.RequiredError(
                'routableConnectorChoice',
                'Required parameter "routableConnectorChoice" was null or undefined when calling updateDefaultFallbackConfig().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwt_key", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["api-key"] = await this.configuration.apiKey("api-key"); // api_key authentication
        }


        let urlPath = `/routing/default`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['routableConnectorChoice']!.map(RoutableConnectorChoiceToJSON),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(RoutableConnectorChoiceFromJSON));
    }

    /**
     * Update default fallback config
     * Routing - Update Default Config
     */
    async updateDefaultFallbackConfig(requestParameters: UpdateDefaultFallbackConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<RoutableConnectorChoice>> {
        const response = await this.updateDefaultFallbackConfigRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update gateway scores for dynamic routing
     * Routing - Feedback
     */
    async updateGatewayScoresRaw(requestParameters: UpdateGatewayScoresRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UpdateScoreResponse>> {
        if (requestParameters['updateScorePayload'] == null) {
            throw new runtime.RequiredError(
                'updateScorePayload',
                'Required parameter "updateScorePayload" was null or undefined when calling updateGatewayScores().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["api-key"] = await this.configuration.apiKey("api-key"); // api_key authentication
        }


        let urlPath = `/routing/feedback`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateScorePayloadToJSON(requestParameters['updateScorePayload']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UpdateScoreResponseFromJSON(jsonValue));
    }

    /**
     * Update gateway scores for dynamic routing
     * Routing - Feedback
     */
    async updateGatewayScores(requestParameters: UpdateGatewayScoresRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UpdateScoreResponse> {
        const response = await this.updateGatewayScoresRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update success based dynamic routing algorithm
     * Routing - Update success based dynamic routing config for profile
     */
    async updateSuccessBasedDynamicRoutingConfigsRaw(requestParameters: UpdateSuccessBasedDynamicRoutingConfigsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RoutingDictionaryRecord>> {
        if (requestParameters['accountId'] == null) {
            throw new runtime.RequiredError(
                'accountId',
                'Required parameter "accountId" was null or undefined when calling updateSuccessBasedDynamicRoutingConfigs().'
            );
        }

        if (requestParameters['profileId'] == null) {
            throw new runtime.RequiredError(
                'profileId',
                'Required parameter "profileId" was null or undefined when calling updateSuccessBasedDynamicRoutingConfigs().'
            );
        }

        if (requestParameters['algorithmId'] == null) {
            throw new runtime.RequiredError(
                'algorithmId',
                'Required parameter "algorithmId" was null or undefined when calling updateSuccessBasedDynamicRoutingConfigs().'
            );
        }

        if (requestParameters['successBasedRoutingConfig'] == null) {
            throw new runtime.RequiredError(
                'successBasedRoutingConfig',
                'Required parameter "successBasedRoutingConfig" was null or undefined when calling updateSuccessBasedDynamicRoutingConfigs().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwt_key", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["api-key"] = await this.configuration.apiKey("api-key"); // api_key authentication
        }


        let urlPath = `/account/{account_id}/business_profile/{profile_id}/dynamic_routing/success_based/config/{algorithm_id}`;
        urlPath = urlPath.replace(`{${"account_id"}}`, encodeURIComponent(String(requestParameters['accountId'])));
        urlPath = urlPath.replace(`{${"profile_id"}}`, encodeURIComponent(String(requestParameters['profileId'])));
        urlPath = urlPath.replace(`{${"algorithm_id"}}`, encodeURIComponent(String(requestParameters['algorithmId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: SuccessBasedRoutingConfigToJSON(requestParameters['successBasedRoutingConfig']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RoutingDictionaryRecordFromJSON(jsonValue));
    }

    /**
     * Update success based dynamic routing algorithm
     * Routing - Update success based dynamic routing config for profile
     */
    async updateSuccessBasedDynamicRoutingConfigs(requestParameters: UpdateSuccessBasedDynamicRoutingConfigsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RoutingDictionaryRecord> {
        const response = await this.updateSuccessBasedDynamicRoutingConfigsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
