/* tslint:disable */
/* eslint-disable */
/**
 * Hyperswitch - API Documentation
 *  ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app\'s client  |  Never share your secret api keys. Keep them guarded and secure. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hyperswitch@juspay.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Currency } from './Currency';
import {
    CurrencyFromJSON,
    CurrencyFromJSONTyped,
    CurrencyToJSON,
    CurrencyToJSONTyped,
} from './Currency';

/**
 * 
 * @export
 * @interface AcceptedCurrenciesOneOf
 */
export interface AcceptedCurrenciesOneOf {
    /**
     * 
     * @type {string}
     * @memberof AcceptedCurrenciesOneOf
     */
    type: AcceptedCurrenciesOneOfTypeEnum;
    /**
     * 
     * @type {Array<Currency>}
     * @memberof AcceptedCurrenciesOneOf
     */
    list: Array<Currency>;
}


/**
 * @export
 */
export const AcceptedCurrenciesOneOfTypeEnum = {
    EnableOnly: 'enable_only'
} as const;
export type AcceptedCurrenciesOneOfTypeEnum = typeof AcceptedCurrenciesOneOfTypeEnum[keyof typeof AcceptedCurrenciesOneOfTypeEnum];


/**
 * Check if a given object implements the AcceptedCurrenciesOneOf interface.
 */
export function instanceOfAcceptedCurrenciesOneOf(value: object): value is AcceptedCurrenciesOneOf {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('list' in value) || value['list'] === undefined) return false;
    return true;
}

export function AcceptedCurrenciesOneOfFromJSON(json: any): AcceptedCurrenciesOneOf {
    return AcceptedCurrenciesOneOfFromJSONTyped(json, false);
}

export function AcceptedCurrenciesOneOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): AcceptedCurrenciesOneOf {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'list': ((json['list'] as Array<any>).map(CurrencyFromJSON)),
    };
}

export function AcceptedCurrenciesOneOfToJSON(json: any): AcceptedCurrenciesOneOf {
    return AcceptedCurrenciesOneOfToJSONTyped(json, false);
}

export function AcceptedCurrenciesOneOfToJSONTyped(value?: AcceptedCurrenciesOneOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'list': ((value['list'] as Array<any>).map(CurrencyToJSON)),
    };
}

