/* tslint:disable */
/* eslint-disable */
/**
 * Hyperswitch - API Documentation
 *  ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app\'s client  |  Never share your secret api keys. Keep them guarded and secure. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hyperswitch@juspay.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Currency } from './Currency';
import {
    CurrencyFromJSON,
    CurrencyFromJSONTyped,
    CurrencyToJSON,
    CurrencyToJSONTyped,
} from './Currency';

/**
 * 
 * @export
 * @interface AcceptedCurrenciesOneOf1
 */
export interface AcceptedCurrenciesOneOf1 {
    /**
     * 
     * @type {string}
     * @memberof AcceptedCurrenciesOneOf1
     */
    type: AcceptedCurrenciesOneOf1TypeEnum;
    /**
     * 
     * @type {Array<Currency>}
     * @memberof AcceptedCurrenciesOneOf1
     */
    list: Array<Currency>;
}


/**
 * @export
 */
export const AcceptedCurrenciesOneOf1TypeEnum = {
    DisableOnly: 'disable_only'
} as const;
export type AcceptedCurrenciesOneOf1TypeEnum = typeof AcceptedCurrenciesOneOf1TypeEnum[keyof typeof AcceptedCurrenciesOneOf1TypeEnum];


/**
 * Check if a given object implements the AcceptedCurrenciesOneOf1 interface.
 */
export function instanceOfAcceptedCurrenciesOneOf1(value: object): value is AcceptedCurrenciesOneOf1 {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('list' in value) || value['list'] === undefined) return false;
    return true;
}

export function AcceptedCurrenciesOneOf1FromJSON(json: any): AcceptedCurrenciesOneOf1 {
    return AcceptedCurrenciesOneOf1FromJSONTyped(json, false);
}

export function AcceptedCurrenciesOneOf1FromJSONTyped(json: any, ignoreDiscriminator: boolean): AcceptedCurrenciesOneOf1 {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'list': ((json['list'] as Array<any>).map(CurrencyFromJSON)),
    };
}

export function AcceptedCurrenciesOneOf1ToJSON(json: any): AcceptedCurrenciesOneOf1 {
    return AcceptedCurrenciesOneOf1ToJSONTyped(json, false);
}

export function AcceptedCurrenciesOneOf1ToJSONTyped(value?: AcceptedCurrenciesOneOf1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'list': ((value['list'] as Array<any>).map(CurrencyToJSON)),
    };
}

