/* tslint:disable */
/* eslint-disable */
/**
 * Hyperswitch - API Documentation
 *  ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app\'s client  |  Never share your secret api keys. Keep them guarded and secure. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hyperswitch@juspay.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdyenSplitType } from './AdyenSplitType';
import {
    AdyenSplitTypeFromJSON,
    AdyenSplitTypeFromJSONTyped,
    AdyenSplitTypeToJSON,
    AdyenSplitTypeToJSONTyped,
} from './AdyenSplitType';

/**
 * Data for the split items
 * @export
 * @interface AdyenSplitItem
 */
export interface AdyenSplitItem {
    /**
     * The amount of the split item
     * @type {number}
     * @memberof AdyenSplitItem
     */
    amount: number;
    /**
     * 
     * @type {AdyenSplitType}
     * @memberof AdyenSplitItem
     */
    splitType: AdyenSplitType;
    /**
     * The unique identifier of the account to which the split amount is allocated.
     * @type {string}
     * @memberof AdyenSplitItem
     */
    account?: string | null;
    /**
     * Unique Identifier for the split item
     * @type {string}
     * @memberof AdyenSplitItem
     */
    reference: string;
    /**
     * Description for the part of the payment that will be allocated to the specified account.
     * @type {string}
     * @memberof AdyenSplitItem
     */
    description?: string | null;
}



/**
 * Check if a given object implements the AdyenSplitItem interface.
 */
export function instanceOfAdyenSplitItem(value: object): value is AdyenSplitItem {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('splitType' in value) || value['splitType'] === undefined) return false;
    if (!('reference' in value) || value['reference'] === undefined) return false;
    return true;
}

export function AdyenSplitItemFromJSON(json: any): AdyenSplitItem {
    return AdyenSplitItemFromJSONTyped(json, false);
}

export function AdyenSplitItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdyenSplitItem {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'splitType': AdyenSplitTypeFromJSON(json['split_type']),
        'account': json['account'] == null ? undefined : json['account'],
        'reference': json['reference'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function AdyenSplitItemToJSON(json: any): AdyenSplitItem {
    return AdyenSplitItemToJSONTyped(json, false);
}

export function AdyenSplitItemToJSONTyped(value?: AdyenSplitItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'split_type': AdyenSplitTypeToJSON(value['splitType']),
        'account': value['account'],
        'reference': value['reference'],
        'description': value['description'],
    };
}

