/* tslint:disable */
/* eslint-disable */
/**
 * Hyperswitch - API Documentation
 *  ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app\'s client  |  Never share your secret api keys. Keep them guarded and secure. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hyperswitch@juspay.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AmazonPayDeliveryPrice } from './AmazonPayDeliveryPrice';
import {
    AmazonPayDeliveryPriceFromJSON,
    AmazonPayDeliveryPriceFromJSONTyped,
    AmazonPayDeliveryPriceToJSON,
    AmazonPayDeliveryPriceToJSONTyped,
} from './AmazonPayDeliveryPrice';
import type { AmazonPayShippingMethod } from './AmazonPayShippingMethod';
import {
    AmazonPayShippingMethodFromJSON,
    AmazonPayShippingMethodFromJSONTyped,
    AmazonPayShippingMethodToJSON,
    AmazonPayShippingMethodToJSONTyped,
} from './AmazonPayShippingMethod';

/**
 * 
 * @export
 * @interface AmazonPayDeliveryOptions
 */
export interface AmazonPayDeliveryOptions {
    /**
     * Delivery Option identifier
     * @type {string}
     * @memberof AmazonPayDeliveryOptions
     */
    id: string;
    /**
     * 
     * @type {AmazonPayDeliveryPrice}
     * @memberof AmazonPayDeliveryOptions
     */
    price: AmazonPayDeliveryPrice;
    /**
     * 
     * @type {AmazonPayShippingMethod}
     * @memberof AmazonPayDeliveryOptions
     */
    shippingMethod: AmazonPayShippingMethod;
    /**
     * Specifies if this delivery option is the default
     * @type {boolean}
     * @memberof AmazonPayDeliveryOptions
     */
    isDefault: boolean;
}

/**
 * Check if a given object implements the AmazonPayDeliveryOptions interface.
 */
export function instanceOfAmazonPayDeliveryOptions(value: object): value is AmazonPayDeliveryOptions {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('shippingMethod' in value) || value['shippingMethod'] === undefined) return false;
    if (!('isDefault' in value) || value['isDefault'] === undefined) return false;
    return true;
}

export function AmazonPayDeliveryOptionsFromJSON(json: any): AmazonPayDeliveryOptions {
    return AmazonPayDeliveryOptionsFromJSONTyped(json, false);
}

export function AmazonPayDeliveryOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AmazonPayDeliveryOptions {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'price': AmazonPayDeliveryPriceFromJSON(json['price']),
        'shippingMethod': AmazonPayShippingMethodFromJSON(json['shipping_method']),
        'isDefault': json['is_default'],
    };
}

export function AmazonPayDeliveryOptionsToJSON(json: any): AmazonPayDeliveryOptions {
    return AmazonPayDeliveryOptionsToJSONTyped(json, false);
}

export function AmazonPayDeliveryOptionsToJSONTyped(value?: AmazonPayDeliveryOptions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'price': AmazonPayDeliveryPriceToJSON(value['price']),
        'shipping_method': AmazonPayShippingMethodToJSON(value['shippingMethod']),
        'is_default': value['isDefault'],
    };
}

