/* tslint:disable */
/* eslint-disable */
/**
 * Hyperswitch - API Documentation
 *  ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app\'s client  |  Never share your secret api keys. Keep them guarded and secure. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hyperswitch@juspay.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Currency } from './Currency';
import {
    CurrencyFromJSON,
    CurrencyFromJSONTyped,
    CurrencyToJSON,
    CurrencyToJSONTyped,
} from './Currency';
import type { ApplePayAddressParameters } from './ApplePayAddressParameters';
import {
    ApplePayAddressParametersFromJSON,
    ApplePayAddressParametersFromJSONTyped,
    ApplePayAddressParametersToJSON,
    ApplePayAddressParametersToJSONTyped,
} from './ApplePayAddressParameters';
import type { ApplePayRecurringPaymentRequest } from './ApplePayRecurringPaymentRequest';
import {
    ApplePayRecurringPaymentRequestFromJSON,
    ApplePayRecurringPaymentRequestFromJSONTyped,
    ApplePayRecurringPaymentRequestToJSON,
    ApplePayRecurringPaymentRequestToJSONTyped,
} from './ApplePayRecurringPaymentRequest';
import type { AmountInfo } from './AmountInfo';
import {
    AmountInfoFromJSON,
    AmountInfoFromJSONTyped,
    AmountInfoToJSON,
    AmountInfoToJSONTyped,
} from './AmountInfo';
import type { CountryAlpha2 } from './CountryAlpha2';
import {
    CountryAlpha2FromJSON,
    CountryAlpha2FromJSONTyped,
    CountryAlpha2ToJSON,
    CountryAlpha2ToJSONTyped,
} from './CountryAlpha2';

/**
 * 
 * @export
 * @interface ApplePayPaymentRequest
 */
export interface ApplePayPaymentRequest {
    /**
     * 
     * @type {CountryAlpha2}
     * @memberof ApplePayPaymentRequest
     */
    countryCode: CountryAlpha2;
    /**
     * 
     * @type {Currency}
     * @memberof ApplePayPaymentRequest
     */
    currencyCode: Currency;
    /**
     * 
     * @type {AmountInfo}
     * @memberof ApplePayPaymentRequest
     */
    total: AmountInfo;
    /**
     * The list of merchant capabilities(ex: whether capable of 3ds or no-3ds)
     * @type {Array<string>}
     * @memberof ApplePayPaymentRequest
     */
    merchantCapabilities?: Array<string> | null;
    /**
     * The list of supported networks
     * @type {Array<string>}
     * @memberof ApplePayPaymentRequest
     */
    supportedNetworks?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof ApplePayPaymentRequest
     */
    merchantIdentifier?: string | null;
    /**
     * 
     * @type {Array<ApplePayAddressParameters>}
     * @memberof ApplePayPaymentRequest
     */
    requiredBillingContactFields?: Array<ApplePayAddressParameters> | null;
    /**
     * 
     * @type {Array<ApplePayAddressParameters>}
     * @memberof ApplePayPaymentRequest
     */
    requiredShippingContactFields?: Array<ApplePayAddressParameters> | null;
    /**
     * 
     * @type {ApplePayRecurringPaymentRequest}
     * @memberof ApplePayPaymentRequest
     */
    recurringPaymentRequest?: ApplePayRecurringPaymentRequest | null;
}



/**
 * Check if a given object implements the ApplePayPaymentRequest interface.
 */
export function instanceOfApplePayPaymentRequest(value: object): value is ApplePayPaymentRequest {
    if (!('countryCode' in value) || value['countryCode'] === undefined) return false;
    if (!('currencyCode' in value) || value['currencyCode'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function ApplePayPaymentRequestFromJSON(json: any): ApplePayPaymentRequest {
    return ApplePayPaymentRequestFromJSONTyped(json, false);
}

export function ApplePayPaymentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplePayPaymentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'countryCode': CountryAlpha2FromJSON(json['country_code']),
        'currencyCode': CurrencyFromJSON(json['currency_code']),
        'total': AmountInfoFromJSON(json['total']),
        'merchantCapabilities': json['merchant_capabilities'] == null ? undefined : json['merchant_capabilities'],
        'supportedNetworks': json['supported_networks'] == null ? undefined : json['supported_networks'],
        'merchantIdentifier': json['merchant_identifier'] == null ? undefined : json['merchant_identifier'],
        'requiredBillingContactFields': json['required_billing_contact_fields'] == null ? undefined : ((json['required_billing_contact_fields'] as Array<any>).map(ApplePayAddressParametersFromJSON)),
        'requiredShippingContactFields': json['required_shipping_contact_fields'] == null ? undefined : ((json['required_shipping_contact_fields'] as Array<any>).map(ApplePayAddressParametersFromJSON)),
        'recurringPaymentRequest': json['recurring_payment_request'] == null ? undefined : ApplePayRecurringPaymentRequestFromJSON(json['recurring_payment_request']),
    };
}

export function ApplePayPaymentRequestToJSON(json: any): ApplePayPaymentRequest {
    return ApplePayPaymentRequestToJSONTyped(json, false);
}

export function ApplePayPaymentRequestToJSONTyped(value?: ApplePayPaymentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'country_code': CountryAlpha2ToJSON(value['countryCode']),
        'currency_code': CurrencyToJSON(value['currencyCode']),
        'total': AmountInfoToJSON(value['total']),
        'merchant_capabilities': value['merchantCapabilities'],
        'supported_networks': value['supportedNetworks'],
        'merchant_identifier': value['merchantIdentifier'],
        'required_billing_contact_fields': value['requiredBillingContactFields'] == null ? undefined : ((value['requiredBillingContactFields'] as Array<any>).map(ApplePayAddressParametersToJSON)),
        'required_shipping_contact_fields': value['requiredShippingContactFields'] == null ? undefined : ((value['requiredShippingContactFields'] as Array<any>).map(ApplePayAddressParametersToJSON)),
        'recurring_payment_request': ApplePayRecurringPaymentRequestToJSON(value['recurringPaymentRequest']),
    };
}

