/* tslint:disable */
/* eslint-disable */
/**
 * Hyperswitch - API Documentation
 *  ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app\'s client  |  Never share your secret api keys. Keep them guarded and secure. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hyperswitch@juspay.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The status of the attempt
 * @export
 */
export const AttemptStatus = {
    Started: 'started',
    AuthenticationFailed: 'authentication_failed',
    RouterDeclined: 'router_declined',
    AuthenticationPending: 'authentication_pending',
    AuthenticationSuccessful: 'authentication_successful',
    Authorized: 'authorized',
    AuthorizationFailed: 'authorization_failed',
    Charged: 'charged',
    Authorizing: 'authorizing',
    CodInitiated: 'cod_initiated',
    Voided: 'voided',
    VoidedPostCharge: 'voided_post_charge',
    VoidInitiated: 'void_initiated',
    CaptureInitiated: 'capture_initiated',
    CaptureFailed: 'capture_failed',
    VoidFailed: 'void_failed',
    AutoRefunded: 'auto_refunded',
    PartialCharged: 'partial_charged',
    PartiallyAuthorized: 'partially_authorized',
    PartialChargedAndChargeable: 'partial_charged_and_chargeable',
    Unresolved: 'unresolved',
    Pending: 'pending',
    Failure: 'failure',
    PaymentMethodAwaited: 'payment_method_awaited',
    ConfirmationAwaited: 'confirmation_awaited',
    DeviceDataCollectionPending: 'device_data_collection_pending',
    IntegrityFailure: 'integrity_failure',
    Expired: 'expired'
} as const;
export type AttemptStatus = typeof AttemptStatus[keyof typeof AttemptStatus];


export function instanceOfAttemptStatus(value: any): boolean {
    for (const key in AttemptStatus) {
        if (Object.prototype.hasOwnProperty.call(AttemptStatus, key)) {
            if (AttemptStatus[key as keyof typeof AttemptStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AttemptStatusFromJSON(json: any): AttemptStatus {
    return AttemptStatusFromJSONTyped(json, false);
}

export function AttemptStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): AttemptStatus {
    return json as AttemptStatus;
}

export function AttemptStatusToJSON(value?: AttemptStatus | null): any {
    return value as any;
}

export function AttemptStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): AttemptStatus {
    return value as AttemptStatus;
}

