/* tslint:disable */
/* eslint-disable */
/**
 * Hyperswitch - API Documentation
 *  ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app\'s client  |  Never share your secret api keys. Keep them guarded and secure. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hyperswitch@juspay.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AuthenticationConnectors } from './AuthenticationConnectors';
import {
    AuthenticationConnectorsFromJSON,
    AuthenticationConnectorsFromJSONTyped,
    AuthenticationConnectorsToJSON,
    AuthenticationConnectorsToJSONTyped,
} from './AuthenticationConnectors';

/**
 * 
 * @export
 * @interface AuthenticationConnectorDetails
 */
export interface AuthenticationConnectorDetails {
    /**
     * List of authentication connectors
     * @type {Array<AuthenticationConnectors>}
     * @memberof AuthenticationConnectorDetails
     */
    authenticationConnectors: Array<AuthenticationConnectors>;
    /**
     * URL of the (customer service) website that will be shown to the shopper in case of technical errors during the 3D Secure 2 process.
     * @type {string}
     * @memberof AuthenticationConnectorDetails
     */
    threeDsRequestorUrl: string;
    /**
     * Merchant app declaring their URL within the CReq message so that the Authentication app can call the Merchant app after OOB authentication has occurred.
     * @type {string}
     * @memberof AuthenticationConnectorDetails
     */
    threeDsRequestorAppUrl?: string | null;
}

/**
 * Check if a given object implements the AuthenticationConnectorDetails interface.
 */
export function instanceOfAuthenticationConnectorDetails(value: object): value is AuthenticationConnectorDetails {
    if (!('authenticationConnectors' in value) || value['authenticationConnectors'] === undefined) return false;
    if (!('threeDsRequestorUrl' in value) || value['threeDsRequestorUrl'] === undefined) return false;
    return true;
}

export function AuthenticationConnectorDetailsFromJSON(json: any): AuthenticationConnectorDetails {
    return AuthenticationConnectorDetailsFromJSONTyped(json, false);
}

export function AuthenticationConnectorDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthenticationConnectorDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'authenticationConnectors': ((json['authentication_connectors'] as Array<any>).map(AuthenticationConnectorsFromJSON)),
        'threeDsRequestorUrl': json['three_ds_requestor_url'],
        'threeDsRequestorAppUrl': json['three_ds_requestor_app_url'] == null ? undefined : json['three_ds_requestor_app_url'],
    };
}

export function AuthenticationConnectorDetailsToJSON(json: any): AuthenticationConnectorDetails {
    return AuthenticationConnectorDetailsToJSONTyped(json, false);
}

export function AuthenticationConnectorDetailsToJSONTyped(value?: AuthenticationConnectorDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'authentication_connectors': ((value['authenticationConnectors'] as Array<any>).map(AuthenticationConnectorsToJSON)),
        'three_ds_requestor_url': value['threeDsRequestorUrl'],
        'three_ds_requestor_app_url': value['threeDsRequestorAppUrl'],
    };
}

