/* tslint:disable */
/* eslint-disable */
/**
 * Hyperswitch - API Documentation
 *  ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app\'s client  |  Never share your secret api keys. Keep them guarded and secure. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hyperswitch@juspay.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BankRedirectDataOneOf6Interac } from './BankRedirectDataOneOf6Interac';
import {
    BankRedirectDataOneOf6InteracFromJSON,
    BankRedirectDataOneOf6InteracFromJSONTyped,
    BankRedirectDataOneOf6InteracToJSON,
    BankRedirectDataOneOf6InteracToJSONTyped,
} from './BankRedirectDataOneOf6Interac';

/**
 * 
 * @export
 * @interface BankRedirectDataOneOf6
 */
export interface BankRedirectDataOneOf6 {
    /**
     * 
     * @type {BankRedirectDataOneOf6Interac}
     * @memberof BankRedirectDataOneOf6
     */
    interac: BankRedirectDataOneOf6Interac;
}

/**
 * Check if a given object implements the BankRedirectDataOneOf6 interface.
 */
export function instanceOfBankRedirectDataOneOf6(value: object): value is BankRedirectDataOneOf6 {
    if (!('interac' in value) || value['interac'] === undefined) return false;
    return true;
}

export function BankRedirectDataOneOf6FromJSON(json: any): BankRedirectDataOneOf6 {
    return BankRedirectDataOneOf6FromJSONTyped(json, false);
}

export function BankRedirectDataOneOf6FromJSONTyped(json: any, ignoreDiscriminator: boolean): BankRedirectDataOneOf6 {
    if (json == null) {
        return json;
    }
    return {
        
        'interac': BankRedirectDataOneOf6InteracFromJSON(json['interac']),
    };
}

export function BankRedirectDataOneOf6ToJSON(json: any): BankRedirectDataOneOf6 {
    return BankRedirectDataOneOf6ToJSONTyped(json, false);
}

export function BankRedirectDataOneOf6ToJSONTyped(value?: BankRedirectDataOneOf6 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'interac': BankRedirectDataOneOf6InteracToJSON(value['interac']),
    };
}

