/* tslint:disable */
/* eslint-disable */
/**
 * Hyperswitch - API Documentation
 *  ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app\'s client  |  Never share your secret api keys. Keep them guarded and secure. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hyperswitch@juspay.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BankRedirectDataOneOf18Eft
 */
export interface BankRedirectDataOneOf18Eft {
    /**
     * The preferred eft provider
     * @type {string}
     * @memberof BankRedirectDataOneOf18Eft
     */
    provider: string;
}

/**
 * Check if a given object implements the BankRedirectDataOneOf18Eft interface.
 */
export function instanceOfBankRedirectDataOneOf18Eft(value: object): value is BankRedirectDataOneOf18Eft {
    if (!('provider' in value) || value['provider'] === undefined) return false;
    return true;
}

export function BankRedirectDataOneOf18EftFromJSON(json: any): BankRedirectDataOneOf18Eft {
    return BankRedirectDataOneOf18EftFromJSONTyped(json, false);
}

export function BankRedirectDataOneOf18EftFromJSONTyped(json: any, ignoreDiscriminator: boolean): BankRedirectDataOneOf18Eft {
    if (json == null) {
        return json;
    }
    return {
        
        'provider': json['provider'],
    };
}

export function BankRedirectDataOneOf18EftToJSON(json: any): BankRedirectDataOneOf18Eft {
    return BankRedirectDataOneOf18EftToJSONTyped(json, false);
}

export function BankRedirectDataOneOf18EftToJSONTyped(value?: BankRedirectDataOneOf18Eft | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'provider': value['provider'],
    };
}

