/* tslint:disable */
/* eslint-disable */
/**
 * Hyperswitch - API Documentation
 *  ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app\'s client  |  Never share your secret api keys. Keep them guarded and secure. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hyperswitch@juspay.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BankTransferAdditionalDataOneOf12
 */
export interface BankTransferAdditionalDataOneOf12 {
    /**
     * 
     * @type {object}
     * @memberof BankTransferAdditionalDataOneOf12
     */
    pse: object;
}

/**
 * Check if a given object implements the BankTransferAdditionalDataOneOf12 interface.
 */
export function instanceOfBankTransferAdditionalDataOneOf12(value: object): value is BankTransferAdditionalDataOneOf12 {
    if (!('pse' in value) || value['pse'] === undefined) return false;
    return true;
}

export function BankTransferAdditionalDataOneOf12FromJSON(json: any): BankTransferAdditionalDataOneOf12 {
    return BankTransferAdditionalDataOneOf12FromJSONTyped(json, false);
}

export function BankTransferAdditionalDataOneOf12FromJSONTyped(json: any, ignoreDiscriminator: boolean): BankTransferAdditionalDataOneOf12 {
    if (json == null) {
        return json;
    }
    return {
        
        'pse': json['pse'],
    };
}

export function BankTransferAdditionalDataOneOf12ToJSON(json: any): BankTransferAdditionalDataOneOf12 {
    return BankTransferAdditionalDataOneOf12ToJSONTyped(json, false);
}

export function BankTransferAdditionalDataOneOf12ToJSONTyped(value?: BankTransferAdditionalDataOneOf12 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pse': value['pse'],
    };
}

