/* tslint:disable */
/* eslint-disable */
/**
 * Hyperswitch - API Documentation
 *  ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app\'s client  |  Never share your secret api keys. Keep them guarded and secure. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hyperswitch@juspay.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BankRedirectDataOneOf4Giropay } from './BankRedirectDataOneOf4Giropay';
import {
    BankRedirectDataOneOf4GiropayFromJSON,
    BankRedirectDataOneOf4GiropayFromJSONTyped,
    BankRedirectDataOneOf4GiropayToJSON,
    BankRedirectDataOneOf4GiropayToJSONTyped,
} from './BankRedirectDataOneOf4Giropay';

/**
 * 
 * @export
 * @interface BankRedirectDataOneOf4
 */
export interface BankRedirectDataOneOf4 {
    /**
     * 
     * @type {BankRedirectDataOneOf4Giropay}
     * @memberof BankRedirectDataOneOf4
     */
    giropay: BankRedirectDataOneOf4Giropay;
}

/**
 * Check if a given object implements the BankRedirectDataOneOf4 interface.
 */
export function instanceOfBankRedirectDataOneOf4(value: object): value is BankRedirectDataOneOf4 {
    if (!('giropay' in value) || value['giropay'] === undefined) return false;
    return true;
}

export function BankRedirectDataOneOf4FromJSON(json: any): BankRedirectDataOneOf4 {
    return BankRedirectDataOneOf4FromJSONTyped(json, false);
}

export function BankRedirectDataOneOf4FromJSONTyped(json: any, ignoreDiscriminator: boolean): BankRedirectDataOneOf4 {
    if (json == null) {
        return json;
    }
    return {
        
        'giropay': BankRedirectDataOneOf4GiropayFromJSON(json['giropay']),
    };
}

export function BankRedirectDataOneOf4ToJSON(json: any): BankRedirectDataOneOf4 {
    return BankRedirectDataOneOf4ToJSONTyped(json, false);
}

export function BankRedirectDataOneOf4ToJSONTyped(value?: BankRedirectDataOneOf4 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'giropay': BankRedirectDataOneOf4GiropayToJSON(value['giropay']),
    };
}

