/* tslint:disable */
/* eslint-disable */
/**
 * Hyperswitch - API Documentation
 *  ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app\'s client  |  Never share your secret api keys. Keep them guarded and secure. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hyperswitch@juspay.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BankTransferDataOneOf4PermataBankTransfer } from './BankTransferDataOneOf4PermataBankTransfer';
import {
    BankTransferDataOneOf4PermataBankTransferFromJSON,
    BankTransferDataOneOf4PermataBankTransferFromJSONTyped,
    BankTransferDataOneOf4PermataBankTransferToJSON,
    BankTransferDataOneOf4PermataBankTransferToJSONTyped,
} from './BankTransferDataOneOf4PermataBankTransfer';

/**
 * 
 * @export
 * @interface BankTransferDataOneOf8
 */
export interface BankTransferDataOneOf8 {
    /**
     * 
     * @type {BankTransferDataOneOf4PermataBankTransfer}
     * @memberof BankTransferDataOneOf8
     */
    cimbVaBankTransfer: BankTransferDataOneOf4PermataBankTransfer;
}

/**
 * Check if a given object implements the BankTransferDataOneOf8 interface.
 */
export function instanceOfBankTransferDataOneOf8(value: object): value is BankTransferDataOneOf8 {
    if (!('cimbVaBankTransfer' in value) || value['cimbVaBankTransfer'] === undefined) return false;
    return true;
}

export function BankTransferDataOneOf8FromJSON(json: any): BankTransferDataOneOf8 {
    return BankTransferDataOneOf8FromJSONTyped(json, false);
}

export function BankTransferDataOneOf8FromJSONTyped(json: any, ignoreDiscriminator: boolean): BankTransferDataOneOf8 {
    if (json == null) {
        return json;
    }
    return {
        
        'cimbVaBankTransfer': BankTransferDataOneOf4PermataBankTransferFromJSON(json['cimb_va_bank_transfer']),
    };
}

export function BankTransferDataOneOf8ToJSON(json: any): BankTransferDataOneOf8 {
    return BankTransferDataOneOf8ToJSONTyped(json, false);
}

export function BankTransferDataOneOf8ToJSONTyped(value?: BankTransferDataOneOf8 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cimb_va_bank_transfer': BankTransferDataOneOf4PermataBankTransferToJSON(value['cimbVaBankTransfer']),
    };
}

