/* tslint:disable */
/* eslint-disable */
/**
 * Hyperswitch - API Documentation
 *  ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app\'s client  |  Never share your secret api keys. Keep them guarded and secure. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hyperswitch@juspay.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaymentLinkConfigRequest } from './PaymentLinkConfigRequest';
import {
    PaymentLinkConfigRequestFromJSON,
    PaymentLinkConfigRequestFromJSONTyped,
    PaymentLinkConfigRequestToJSON,
    PaymentLinkConfigRequestToJSONTyped,
} from './PaymentLinkConfigRequest';
import type { PaymentLinkSdkLabelType } from './PaymentLinkSdkLabelType';
import {
    PaymentLinkSdkLabelTypeFromJSON,
    PaymentLinkSdkLabelTypeFromJSONTyped,
    PaymentLinkSdkLabelTypeToJSON,
    PaymentLinkSdkLabelTypeToJSONTyped,
} from './PaymentLinkSdkLabelType';
import type { PaymentLinkTransactionDetails } from './PaymentLinkTransactionDetails';
import {
    PaymentLinkTransactionDetailsFromJSON,
    PaymentLinkTransactionDetailsFromJSONTyped,
    PaymentLinkTransactionDetailsToJSON,
    PaymentLinkTransactionDetailsToJSONTyped,
} from './PaymentLinkTransactionDetails';
import type { PaymentLinkBackgroundImageConfig } from './PaymentLinkBackgroundImageConfig';
import {
    PaymentLinkBackgroundImageConfigFromJSON,
    PaymentLinkBackgroundImageConfigFromJSONTyped,
    PaymentLinkBackgroundImageConfigToJSON,
    PaymentLinkBackgroundImageConfigToJSONTyped,
} from './PaymentLinkBackgroundImageConfig';
import type { PaymentLinkDetailsLayout } from './PaymentLinkDetailsLayout';
import {
    PaymentLinkDetailsLayoutFromJSON,
    PaymentLinkDetailsLayoutFromJSONTyped,
    PaymentLinkDetailsLayoutToJSON,
    PaymentLinkDetailsLayoutToJSONTyped,
} from './PaymentLinkDetailsLayout';
import type { PaymentLinkShowSdkTerms } from './PaymentLinkShowSdkTerms';
import {
    PaymentLinkShowSdkTermsFromJSON,
    PaymentLinkShowSdkTermsFromJSONTyped,
    PaymentLinkShowSdkTermsToJSON,
    PaymentLinkShowSdkTermsToJSONTyped,
} from './PaymentLinkShowSdkTerms';

/**
 * 
 * @export
 * @interface BusinessPaymentLinkConfig
 */
export interface BusinessPaymentLinkConfig {
    /**
     * custom theme for the payment link
     * @type {string}
     * @memberof BusinessPaymentLinkConfig
     */
    theme?: string | null;
    /**
     * merchant display logo
     * @type {string}
     * @memberof BusinessPaymentLinkConfig
     */
    logo?: string | null;
    /**
     * Custom merchant name for payment link
     * @type {string}
     * @memberof BusinessPaymentLinkConfig
     */
    sellerName?: string | null;
    /**
     * Custom layout for sdk
     * @type {string}
     * @memberof BusinessPaymentLinkConfig
     */
    sdkLayout?: string | null;
    /**
     * Display only the sdk for payment link
     * @type {boolean}
     * @memberof BusinessPaymentLinkConfig
     */
    displaySdkOnly?: boolean | null;
    /**
     * Enable saved payment method option for payment link
     * @type {boolean}
     * @memberof BusinessPaymentLinkConfig
     */
    enabledSavedPaymentMethod?: boolean | null;
    /**
     * Hide card nickname field option for payment link
     * @type {boolean}
     * @memberof BusinessPaymentLinkConfig
     */
    hideCardNicknameField?: boolean | null;
    /**
     * Show card form by default for payment link
     * @type {boolean}
     * @memberof BusinessPaymentLinkConfig
     */
    showCardFormByDefault?: boolean | null;
    /**
     * Dynamic details related to merchant to be rendered in payment link
     * @type {Array<PaymentLinkTransactionDetails>}
     * @memberof BusinessPaymentLinkConfig
     */
    transactionDetails?: Array<PaymentLinkTransactionDetails> | null;
    /**
     * 
     * @type {PaymentLinkBackgroundImageConfig}
     * @memberof BusinessPaymentLinkConfig
     */
    backgroundImage?: PaymentLinkBackgroundImageConfig | null;
    /**
     * 
     * @type {PaymentLinkDetailsLayout}
     * @memberof BusinessPaymentLinkConfig
     */
    detailsLayout?: PaymentLinkDetailsLayout | null;
    /**
     * Text for payment link's handle confirm button
     * @type {string}
     * @memberof BusinessPaymentLinkConfig
     */
    paymentButtonText?: string | null;
    /**
     * Text for customizing message for card terms
     * @type {string}
     * @memberof BusinessPaymentLinkConfig
     */
    customMessageForCardTerms?: string | null;
    /**
     * Custom background colour for payment link's handle confirm button
     * @type {string}
     * @memberof BusinessPaymentLinkConfig
     */
    paymentButtonColour?: string | null;
    /**
     * Skip the status screen after payment completion
     * @type {boolean}
     * @memberof BusinessPaymentLinkConfig
     */
    skipStatusScreen?: boolean | null;
    /**
     * Custom text colour for payment link's handle confirm button
     * @type {string}
     * @memberof BusinessPaymentLinkConfig
     */
    paymentButtonTextColour?: string | null;
    /**
     * Custom background colour for the payment link
     * @type {string}
     * @memberof BusinessPaymentLinkConfig
     */
    backgroundColour?: string | null;
    /**
     * SDK configuration rules
     * @type {{ [key: string]: { [key: string]: string; }; }}
     * @memberof BusinessPaymentLinkConfig
     */
    sdkUiRules?: { [key: string]: { [key: string]: string; }; } | null;
    /**
     * Payment link configuration rules
     * @type {{ [key: string]: { [key: string]: string; }; }}
     * @memberof BusinessPaymentLinkConfig
     */
    paymentLinkUiRules?: { [key: string]: { [key: string]: string; }; } | null;
    /**
     * Flag to enable the button only when the payment form is ready for submission
     * @type {boolean}
     * @memberof BusinessPaymentLinkConfig
     */
    enableButtonOnlyOnFormReady?: boolean | null;
    /**
     * Optional header for the SDK's payment form
     * @type {string}
     * @memberof BusinessPaymentLinkConfig
     */
    paymentFormHeaderText?: string | null;
    /**
     * 
     * @type {PaymentLinkSdkLabelType}
     * @memberof BusinessPaymentLinkConfig
     */
    paymentFormLabelType?: PaymentLinkSdkLabelType | null;
    /**
     * 
     * @type {PaymentLinkShowSdkTerms}
     * @memberof BusinessPaymentLinkConfig
     */
    showCardTerms?: PaymentLinkShowSdkTerms | null;
    /**
     * Boolean to control payment button text for setup mandate calls
     * @type {boolean}
     * @memberof BusinessPaymentLinkConfig
     */
    isSetupMandateFlow?: boolean | null;
    /**
     * Hex color for the CVC icon during error state
     * @type {string}
     * @memberof BusinessPaymentLinkConfig
     */
    colorIconCardCvcError?: string | null;
    /**
     * Custom domain name to be used for hosting the link in your own domain
     * @type {string}
     * @memberof BusinessPaymentLinkConfig
     */
    domainName?: string | null;
    /**
     * list of configs for multi theme setup
     * @type {{ [key: string]: PaymentLinkConfigRequest; }}
     * @memberof BusinessPaymentLinkConfig
     */
    businessSpecificConfigs?: { [key: string]: PaymentLinkConfigRequest; } | null;
    /**
     * A list of allowed domains (glob patterns) where this link can be embedded / opened from
     * @type {Set<string>}
     * @memberof BusinessPaymentLinkConfig
     */
    allowedDomains?: Set<string> | null;
    /**
     * Toggle for HyperSwitch branding visibility
     * @type {boolean}
     * @memberof BusinessPaymentLinkConfig
     */
    brandingVisibility?: boolean | null;
}



/**
 * Check if a given object implements the BusinessPaymentLinkConfig interface.
 */
export function instanceOfBusinessPaymentLinkConfig(value: object): value is BusinessPaymentLinkConfig {
    return true;
}

export function BusinessPaymentLinkConfigFromJSON(json: any): BusinessPaymentLinkConfig {
    return BusinessPaymentLinkConfigFromJSONTyped(json, false);
}

export function BusinessPaymentLinkConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): BusinessPaymentLinkConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'theme': json['theme'] == null ? undefined : json['theme'],
        'logo': json['logo'] == null ? undefined : json['logo'],
        'sellerName': json['seller_name'] == null ? undefined : json['seller_name'],
        'sdkLayout': json['sdk_layout'] == null ? undefined : json['sdk_layout'],
        'displaySdkOnly': json['display_sdk_only'] == null ? undefined : json['display_sdk_only'],
        'enabledSavedPaymentMethod': json['enabled_saved_payment_method'] == null ? undefined : json['enabled_saved_payment_method'],
        'hideCardNicknameField': json['hide_card_nickname_field'] == null ? undefined : json['hide_card_nickname_field'],
        'showCardFormByDefault': json['show_card_form_by_default'] == null ? undefined : json['show_card_form_by_default'],
        'transactionDetails': json['transaction_details'] == null ? undefined : ((json['transaction_details'] as Array<any>).map(PaymentLinkTransactionDetailsFromJSON)),
        'backgroundImage': json['background_image'] == null ? undefined : PaymentLinkBackgroundImageConfigFromJSON(json['background_image']),
        'detailsLayout': json['details_layout'] == null ? undefined : PaymentLinkDetailsLayoutFromJSON(json['details_layout']),
        'paymentButtonText': json['payment_button_text'] == null ? undefined : json['payment_button_text'],
        'customMessageForCardTerms': json['custom_message_for_card_terms'] == null ? undefined : json['custom_message_for_card_terms'],
        'paymentButtonColour': json['payment_button_colour'] == null ? undefined : json['payment_button_colour'],
        'skipStatusScreen': json['skip_status_screen'] == null ? undefined : json['skip_status_screen'],
        'paymentButtonTextColour': json['payment_button_text_colour'] == null ? undefined : json['payment_button_text_colour'],
        'backgroundColour': json['background_colour'] == null ? undefined : json['background_colour'],
        'sdkUiRules': json['sdk_ui_rules'] == null ? undefined : json['sdk_ui_rules'],
        'paymentLinkUiRules': json['payment_link_ui_rules'] == null ? undefined : json['payment_link_ui_rules'],
        'enableButtonOnlyOnFormReady': json['enable_button_only_on_form_ready'] == null ? undefined : json['enable_button_only_on_form_ready'],
        'paymentFormHeaderText': json['payment_form_header_text'] == null ? undefined : json['payment_form_header_text'],
        'paymentFormLabelType': json['payment_form_label_type'] == null ? undefined : PaymentLinkSdkLabelTypeFromJSON(json['payment_form_label_type']),
        'showCardTerms': json['show_card_terms'] == null ? undefined : PaymentLinkShowSdkTermsFromJSON(json['show_card_terms']),
        'isSetupMandateFlow': json['is_setup_mandate_flow'] == null ? undefined : json['is_setup_mandate_flow'],
        'colorIconCardCvcError': json['color_icon_card_cvc_error'] == null ? undefined : json['color_icon_card_cvc_error'],
        'domainName': json['domain_name'] == null ? undefined : json['domain_name'],
        'businessSpecificConfigs': json['business_specific_configs'] == null ? undefined : (mapValues(json['business_specific_configs'], PaymentLinkConfigRequestFromJSON)),
        'allowedDomains': json['allowed_domains'] == null ? undefined : new Set(json['allowed_domains']),
        'brandingVisibility': json['branding_visibility'] == null ? undefined : json['branding_visibility'],
    };
}

export function BusinessPaymentLinkConfigToJSON(json: any): BusinessPaymentLinkConfig {
    return BusinessPaymentLinkConfigToJSONTyped(json, false);
}

export function BusinessPaymentLinkConfigToJSONTyped(value?: BusinessPaymentLinkConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'theme': value['theme'],
        'logo': value['logo'],
        'seller_name': value['sellerName'],
        'sdk_layout': value['sdkLayout'],
        'display_sdk_only': value['displaySdkOnly'],
        'enabled_saved_payment_method': value['enabledSavedPaymentMethod'],
        'hide_card_nickname_field': value['hideCardNicknameField'],
        'show_card_form_by_default': value['showCardFormByDefault'],
        'transaction_details': value['transactionDetails'] == null ? undefined : ((value['transactionDetails'] as Array<any>).map(PaymentLinkTransactionDetailsToJSON)),
        'background_image': PaymentLinkBackgroundImageConfigToJSON(value['backgroundImage']),
        'details_layout': PaymentLinkDetailsLayoutToJSON(value['detailsLayout']),
        'payment_button_text': value['paymentButtonText'],
        'custom_message_for_card_terms': value['customMessageForCardTerms'],
        'payment_button_colour': value['paymentButtonColour'],
        'skip_status_screen': value['skipStatusScreen'],
        'payment_button_text_colour': value['paymentButtonTextColour'],
        'background_colour': value['backgroundColour'],
        'sdk_ui_rules': value['sdkUiRules'],
        'payment_link_ui_rules': value['paymentLinkUiRules'],
        'enable_button_only_on_form_ready': value['enableButtonOnlyOnFormReady'],
        'payment_form_header_text': value['paymentFormHeaderText'],
        'payment_form_label_type': PaymentLinkSdkLabelTypeToJSON(value['paymentFormLabelType']),
        'show_card_terms': PaymentLinkShowSdkTermsToJSON(value['showCardTerms']),
        'is_setup_mandate_flow': value['isSetupMandateFlow'],
        'color_icon_card_cvc_error': value['colorIconCardCvcError'],
        'domain_name': value['domainName'],
        'business_specific_configs': value['businessSpecificConfigs'] == null ? undefined : (mapValues(value['businessSpecificConfigs'], PaymentLinkConfigRequestToJSON)),
        'allowed_domains': value['allowedDomains'] == null ? undefined : Array.from(value['allowedDomains'] as Set<any>),
        'branding_visibility': value['brandingVisibility'],
    };
}

