/* tslint:disable */
/* eslint-disable */
/**
 * Hyperswitch - API Documentation
 *  ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app\'s client  |  Never share your secret api keys. Keep them guarded and secure. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hyperswitch@juspay.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BusinessGenericLinkConfig
 */
export interface BusinessGenericLinkConfig {
    /**
     * Merchant's display logo
     * @type {string}
     * @memberof BusinessGenericLinkConfig
     */
    logo?: string | null;
    /**
     * Custom merchant name for the link
     * @type {string}
     * @memberof BusinessGenericLinkConfig
     */
    merchantName?: string | null;
    /**
     * Primary color to be used in the form represented in hex format
     * @type {string}
     * @memberof BusinessGenericLinkConfig
     */
    theme?: string | null;
    /**
     * Custom domain name to be used for hosting the link
     * @type {string}
     * @memberof BusinessGenericLinkConfig
     */
    domainName?: string | null;
    /**
     * A list of allowed domains (glob patterns) where this link can be embedded / opened from
     * @type {Set<string>}
     * @memberof BusinessGenericLinkConfig
     */
    allowedDomains: Set<string>;
}

/**
 * Check if a given object implements the BusinessGenericLinkConfig interface.
 */
export function instanceOfBusinessGenericLinkConfig(value: object): value is BusinessGenericLinkConfig {
    if (!('allowedDomains' in value) || value['allowedDomains'] === undefined) return false;
    return true;
}

export function BusinessGenericLinkConfigFromJSON(json: any): BusinessGenericLinkConfig {
    return BusinessGenericLinkConfigFromJSONTyped(json, false);
}

export function BusinessGenericLinkConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): BusinessGenericLinkConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'logo': json['logo'] == null ? undefined : json['logo'],
        'merchantName': json['merchant_name'] == null ? undefined : json['merchant_name'],
        'theme': json['theme'] == null ? undefined : json['theme'],
        'domainName': json['domain_name'] == null ? undefined : json['domain_name'],
        'allowedDomains': new Set(json['allowed_domains']),
    };
}

export function BusinessGenericLinkConfigToJSON(json: any): BusinessGenericLinkConfig {
    return BusinessGenericLinkConfigToJSONTyped(json, false);
}

export function BusinessGenericLinkConfigToJSONTyped(value?: BusinessGenericLinkConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'logo': value['logo'],
        'merchant_name': value['merchantName'],
        'theme': value['theme'],
        'domain_name': value['domainName'],
        'allowed_domains': Array.from(value['allowedDomains'] as Set<any>),
    };
}

