/* tslint:disable */
/* eslint-disable */
/**
 * Hyperswitch - API Documentation
 *  ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app\'s client  |  Never share your secret api keys. Keep them guarded and secure. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hyperswitch@juspay.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SurchargeDetailsResponse } from './SurchargeDetailsResponse';
import {
    SurchargeDetailsResponseFromJSON,
    SurchargeDetailsResponseFromJSONTyped,
    SurchargeDetailsResponseToJSON,
    SurchargeDetailsResponseToJSONTyped,
} from './SurchargeDetailsResponse';
import type { CardNetwork } from './CardNetwork';
import {
    CardNetworkFromJSON,
    CardNetworkFromJSONTyped,
    CardNetworkToJSON,
    CardNetworkToJSONTyped,
} from './CardNetwork';

/**
 * 
 * @export
 * @interface CardNetworkTypes
 */
export interface CardNetworkTypes {
    /**
     * 
     * @type {CardNetwork}
     * @memberof CardNetworkTypes
     */
    cardNetwork?: CardNetwork | null;
    /**
     * 
     * @type {SurchargeDetailsResponse}
     * @memberof CardNetworkTypes
     */
    surchargeDetails?: SurchargeDetailsResponse | null;
    /**
     * The list of eligible connectors for a given card network
     * @type {Array<string>}
     * @memberof CardNetworkTypes
     */
    eligibleConnectors: Array<string>;
}



/**
 * Check if a given object implements the CardNetworkTypes interface.
 */
export function instanceOfCardNetworkTypes(value: object): value is CardNetworkTypes {
    if (!('eligibleConnectors' in value) || value['eligibleConnectors'] === undefined) return false;
    return true;
}

export function CardNetworkTypesFromJSON(json: any): CardNetworkTypes {
    return CardNetworkTypesFromJSONTyped(json, false);
}

export function CardNetworkTypesFromJSONTyped(json: any, ignoreDiscriminator: boolean): CardNetworkTypes {
    if (json == null) {
        return json;
    }
    return {
        
        'cardNetwork': json['card_network'] == null ? undefined : CardNetworkFromJSON(json['card_network']),
        'surchargeDetails': json['surcharge_details'] == null ? undefined : SurchargeDetailsResponseFromJSON(json['surcharge_details']),
        'eligibleConnectors': json['eligible_connectors'],
    };
}

export function CardNetworkTypesToJSON(json: any): CardNetworkTypes {
    return CardNetworkTypesToJSONTyped(json, false);
}

export function CardNetworkTypesToJSONTyped(value?: CardNetworkTypes | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'card_network': CardNetworkToJSON(value['cardNetwork']),
        'surcharge_details': SurchargeDetailsResponseToJSON(value['surchargeDetails']),
        'eligible_connectors': value['eligibleConnectors'],
    };
}

