/* tslint:disable */
/* eslint-disable */
/**
 * Hyperswitch - API Documentation
 *  ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app\'s client  |  Never share your secret api keys. Keep them guarded and secure. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hyperswitch@juspay.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Currency } from './Currency';
import {
    CurrencyFromJSON,
    CurrencyFromJSONTyped,
    CurrencyToJSON,
    CurrencyToJSONTyped,
} from './Currency';
import type { CardNetwork } from './CardNetwork';
import {
    CardNetworkFromJSON,
    CardNetworkFromJSONTyped,
    CardNetworkToJSON,
    CardNetworkToJSONTyped,
} from './CardNetwork';
import type { CtpServiceProvider } from './CtpServiceProvider';
import {
    CtpServiceProviderFromJSON,
    CtpServiceProviderFromJSONTyped,
    CtpServiceProviderToJSON,
    CtpServiceProviderToJSONTyped,
} from './CtpServiceProvider';

/**
 * 
 * @export
 * @interface ClickToPaySessionResponse
 */
export interface ClickToPaySessionResponse {
    /**
     * 
     * @type {string}
     * @memberof ClickToPaySessionResponse
     */
    dpaId: string;
    /**
     * 
     * @type {string}
     * @memberof ClickToPaySessionResponse
     */
    dpaName: string;
    /**
     * 
     * @type {string}
     * @memberof ClickToPaySessionResponse
     */
    locale: string;
    /**
     * 
     * @type {Array<CardNetwork>}
     * @memberof ClickToPaySessionResponse
     */
    cardBrands: Array<CardNetwork>;
    /**
     * 
     * @type {string}
     * @memberof ClickToPaySessionResponse
     */
    acquirerBin: string;
    /**
     * 
     * @type {string}
     * @memberof ClickToPaySessionResponse
     */
    acquirerMerchantId: string;
    /**
     * 
     * @type {string}
     * @memberof ClickToPaySessionResponse
     */
    merchantCategoryCode: string;
    /**
     * 
     * @type {string}
     * @memberof ClickToPaySessionResponse
     */
    merchantCountryCode: string;
    /**
     * 
     * @type {string}
     * @memberof ClickToPaySessionResponse
     */
    transactionAmount: string;
    /**
     * 
     * @type {Currency}
     * @memberof ClickToPaySessionResponse
     */
    transactionCurrencyCode: Currency;
    /**
     * 
     * @type {string}
     * @memberof ClickToPaySessionResponse
     */
    phoneNumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ClickToPaySessionResponse
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ClickToPaySessionResponse
     */
    phoneCountryCode?: string | null;
    /**
     * 
     * @type {CtpServiceProvider}
     * @memberof ClickToPaySessionResponse
     */
    provider?: CtpServiceProvider | null;
    /**
     * 
     * @type {string}
     * @memberof ClickToPaySessionResponse
     */
    dpaClientId?: string | null;
}



/**
 * Check if a given object implements the ClickToPaySessionResponse interface.
 */
export function instanceOfClickToPaySessionResponse(value: object): value is ClickToPaySessionResponse {
    if (!('dpaId' in value) || value['dpaId'] === undefined) return false;
    if (!('dpaName' in value) || value['dpaName'] === undefined) return false;
    if (!('locale' in value) || value['locale'] === undefined) return false;
    if (!('cardBrands' in value) || value['cardBrands'] === undefined) return false;
    if (!('acquirerBin' in value) || value['acquirerBin'] === undefined) return false;
    if (!('acquirerMerchantId' in value) || value['acquirerMerchantId'] === undefined) return false;
    if (!('merchantCategoryCode' in value) || value['merchantCategoryCode'] === undefined) return false;
    if (!('merchantCountryCode' in value) || value['merchantCountryCode'] === undefined) return false;
    if (!('transactionAmount' in value) || value['transactionAmount'] === undefined) return false;
    if (!('transactionCurrencyCode' in value) || value['transactionCurrencyCode'] === undefined) return false;
    return true;
}

export function ClickToPaySessionResponseFromJSON(json: any): ClickToPaySessionResponse {
    return ClickToPaySessionResponseFromJSONTyped(json, false);
}

export function ClickToPaySessionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClickToPaySessionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'dpaId': json['dpa_id'],
        'dpaName': json['dpa_name'],
        'locale': json['locale'],
        'cardBrands': ((json['card_brands'] as Array<any>).map(CardNetworkFromJSON)),
        'acquirerBin': json['acquirer_bin'],
        'acquirerMerchantId': json['acquirer_merchant_id'],
        'merchantCategoryCode': json['merchant_category_code'],
        'merchantCountryCode': json['merchant_country_code'],
        'transactionAmount': json['transaction_amount'],
        'transactionCurrencyCode': CurrencyFromJSON(json['transaction_currency_code']),
        'phoneNumber': json['phone_number'] == null ? undefined : json['phone_number'],
        'email': json['email'] == null ? undefined : json['email'],
        'phoneCountryCode': json['phone_country_code'] == null ? undefined : json['phone_country_code'],
        'provider': json['provider'] == null ? undefined : CtpServiceProviderFromJSON(json['provider']),
        'dpaClientId': json['dpa_client_id'] == null ? undefined : json['dpa_client_id'],
    };
}

export function ClickToPaySessionResponseToJSON(json: any): ClickToPaySessionResponse {
    return ClickToPaySessionResponseToJSONTyped(json, false);
}

export function ClickToPaySessionResponseToJSONTyped(value?: ClickToPaySessionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'dpa_id': value['dpaId'],
        'dpa_name': value['dpaName'],
        'locale': value['locale'],
        'card_brands': ((value['cardBrands'] as Array<any>).map(CardNetworkToJSON)),
        'acquirer_bin': value['acquirerBin'],
        'acquirer_merchant_id': value['acquirerMerchantId'],
        'merchant_category_code': value['merchantCategoryCode'],
        'merchant_country_code': value['merchantCountryCode'],
        'transaction_amount': value['transactionAmount'],
        'transaction_currency_code': CurrencyToJSON(value['transactionCurrencyCode']),
        'phone_number': value['phoneNumber'],
        'email': value['email'],
        'phone_country_code': value['phoneCountryCode'],
        'provider': CtpServiceProviderToJSON(value['provider']),
        'dpa_client_id': value['dpaClientId'],
    };
}

