/* tslint:disable */
/* eslint-disable */
/**
 * Hyperswitch - API Documentation
 *  ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app\'s client  |  Never share your secret api keys. Keep them guarded and secure. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hyperswitch@juspay.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Conditional comparison type
 * @export
 */
export const ComparisonType = {
    Equal: 'equal',
    NotEqual: 'not_equal',
    LessThan: 'less_than',
    LessThanEqual: 'less_than_equal',
    GreaterThan: 'greater_than',
    GreaterThanEqual: 'greater_than_equal'
} as const;
export type ComparisonType = typeof ComparisonType[keyof typeof ComparisonType];


export function instanceOfComparisonType(value: any): boolean {
    for (const key in ComparisonType) {
        if (Object.prototype.hasOwnProperty.call(ComparisonType, key)) {
            if (ComparisonType[key as keyof typeof ComparisonType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ComparisonTypeFromJSON(json: any): ComparisonType {
    return ComparisonTypeFromJSONTyped(json, false);
}

export function ComparisonTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComparisonType {
    return json as ComparisonType;
}

export function ComparisonTypeToJSON(value?: ComparisonType | null): any {
    return value as any;
}

export function ComparisonTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): ComparisonType {
    return value as ComparisonType;
}

