/* tslint:disable */
/* eslint-disable */
/**
 * Hyperswitch - API Documentation
 *  ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app\'s client  |  Never share your secret api keys. Keep them guarded and secure. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hyperswitch@juspay.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConnectorWalletDetails
 */
export interface ConnectorWalletDetails {
    /**
     * This field contains the Apple Pay certificates and credentials for iOS and Web Apple Pay flow
     * @type {object}
     * @memberof ConnectorWalletDetails
     */
    applePayCombined?: object | null;
    /**
     * This field is for our legacy Apple Pay flow that contains the Apple Pay certificates and credentials for only iOS Apple Pay flow
     * @type {object}
     * @memberof ConnectorWalletDetails
     */
    applePay?: object | null;
    /**
     * This field contains the Amazon Pay certificates and credentials
     * @type {object}
     * @memberof ConnectorWalletDetails
     */
    amazonPay?: object | null;
    /**
     * This field contains the Samsung Pay certificates and credentials
     * @type {object}
     * @memberof ConnectorWalletDetails
     */
    samsungPay?: object | null;
    /**
     * This field contains the Paze certificates and credentials
     * @type {object}
     * @memberof ConnectorWalletDetails
     */
    paze?: object | null;
    /**
     * This field contains the Google Pay certificates and credentials
     * @type {object}
     * @memberof ConnectorWalletDetails
     */
    googlePay?: object | null;
}

/**
 * Check if a given object implements the ConnectorWalletDetails interface.
 */
export function instanceOfConnectorWalletDetails(value: object): value is ConnectorWalletDetails {
    return true;
}

export function ConnectorWalletDetailsFromJSON(json: any): ConnectorWalletDetails {
    return ConnectorWalletDetailsFromJSONTyped(json, false);
}

export function ConnectorWalletDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConnectorWalletDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'applePayCombined': json['apple_pay_combined'] == null ? undefined : json['apple_pay_combined'],
        'applePay': json['apple_pay'] == null ? undefined : json['apple_pay'],
        'amazonPay': json['amazon_pay'] == null ? undefined : json['amazon_pay'],
        'samsungPay': json['samsung_pay'] == null ? undefined : json['samsung_pay'],
        'paze': json['paze'] == null ? undefined : json['paze'],
        'googlePay': json['google_pay'] == null ? undefined : json['google_pay'],
    };
}

export function ConnectorWalletDetailsToJSON(json: any): ConnectorWalletDetails {
    return ConnectorWalletDetailsToJSONTyped(json, false);
}

export function ConnectorWalletDetailsToJSONTyped(value?: ConnectorWalletDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'apple_pay_combined': value['applePayCombined'],
        'apple_pay': value['applePay'],
        'amazon_pay': value['amazonPay'],
        'samsung_pay': value['samsungPay'],
        'paze': value['paze'],
        'google_pay': value['googlePay'],
    };
}

