/* tslint:disable */
/* eslint-disable */
/**
 * Hyperswitch - API Documentation
 *  ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app\'s client  |  Never share your secret api keys. Keep them guarded and secure. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hyperswitch@juspay.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EventClass } from './EventClass';
import {
    EventClassFromJSON,
    EventClassFromJSONTyped,
    EventClassToJSON,
    EventClassToJSONTyped,
} from './EventClass';
import type { SupportedPaymentMethod } from './SupportedPaymentMethod';
import {
    SupportedPaymentMethodFromJSON,
    SupportedPaymentMethodFromJSONTyped,
    SupportedPaymentMethodToJSON,
    SupportedPaymentMethodToJSONTyped,
} from './SupportedPaymentMethod';
import type { ConnectorIntegrationStatus } from './ConnectorIntegrationStatus';
import {
    ConnectorIntegrationStatusFromJSON,
    ConnectorIntegrationStatusFromJSONTyped,
    ConnectorIntegrationStatusToJSON,
    ConnectorIntegrationStatusToJSONTyped,
} from './ConnectorIntegrationStatus';
import type { HyperswitchConnectorCategory } from './HyperswitchConnectorCategory';
import {
    HyperswitchConnectorCategoryFromJSON,
    HyperswitchConnectorCategoryFromJSONTyped,
    HyperswitchConnectorCategoryToJSON,
    HyperswitchConnectorCategoryToJSONTyped,
} from './HyperswitchConnectorCategory';

/**
 * 
 * @export
 * @interface ConnectorFeatureMatrixResponse
 */
export interface ConnectorFeatureMatrixResponse {
    /**
     * The name of the connector
     * @type {string}
     * @memberof ConnectorFeatureMatrixResponse
     */
    name: string;
    /**
     * The display name of the connector
     * @type {string}
     * @memberof ConnectorFeatureMatrixResponse
     */
    displayName: string;
    /**
     * The description of the connector
     * @type {string}
     * @memberof ConnectorFeatureMatrixResponse
     */
    description: string;
    /**
     * 
     * @type {HyperswitchConnectorCategory}
     * @memberof ConnectorFeatureMatrixResponse
     */
    category: HyperswitchConnectorCategory;
    /**
     * 
     * @type {ConnectorIntegrationStatus}
     * @memberof ConnectorFeatureMatrixResponse
     */
    integrationStatus: ConnectorIntegrationStatus;
    /**
     * The list of payment methods supported by the connector
     * @type {Array<SupportedPaymentMethod>}
     * @memberof ConnectorFeatureMatrixResponse
     */
    supportedPaymentMethods?: Array<SupportedPaymentMethod> | null;
    /**
     * The list of webhook flows supported by the connector
     * @type {Array<EventClass>}
     * @memberof ConnectorFeatureMatrixResponse
     */
    supportedWebhookFlows?: Array<EventClass> | null;
}



/**
 * Check if a given object implements the ConnectorFeatureMatrixResponse interface.
 */
export function instanceOfConnectorFeatureMatrixResponse(value: object): value is ConnectorFeatureMatrixResponse {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('integrationStatus' in value) || value['integrationStatus'] === undefined) return false;
    return true;
}

export function ConnectorFeatureMatrixResponseFromJSON(json: any): ConnectorFeatureMatrixResponse {
    return ConnectorFeatureMatrixResponseFromJSONTyped(json, false);
}

export function ConnectorFeatureMatrixResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConnectorFeatureMatrixResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'displayName': json['display_name'],
        'description': json['description'],
        'category': HyperswitchConnectorCategoryFromJSON(json['category']),
        'integrationStatus': ConnectorIntegrationStatusFromJSON(json['integration_status']),
        'supportedPaymentMethods': json['supported_payment_methods'] == null ? undefined : ((json['supported_payment_methods'] as Array<any>).map(SupportedPaymentMethodFromJSON)),
        'supportedWebhookFlows': json['supported_webhook_flows'] == null ? undefined : ((json['supported_webhook_flows'] as Array<any>).map(EventClassFromJSON)),
    };
}

export function ConnectorFeatureMatrixResponseToJSON(json: any): ConnectorFeatureMatrixResponse {
    return ConnectorFeatureMatrixResponseToJSONTyped(json, false);
}

export function ConnectorFeatureMatrixResponseToJSONTyped(value?: ConnectorFeatureMatrixResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'display_name': value['displayName'],
        'description': value['description'],
        'category': HyperswitchConnectorCategoryToJSON(value['category']),
        'integration_status': ConnectorIntegrationStatusToJSON(value['integrationStatus']),
        'supported_payment_methods': value['supportedPaymentMethods'] == null ? undefined : ((value['supportedPaymentMethods'] as Array<any>).map(SupportedPaymentMethodToJSON)),
        'supported_webhook_flows': value['supportedWebhookFlows'] == null ? undefined : ((value['supportedWebhookFlows'] as Array<any>).map(EventClassToJSON)),
    };
}

