/* tslint:disable */
/* eslint-disable */
/**
 * Hyperswitch - API Documentation
 *  ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app\'s client  |  Never share your secret api keys. Keep them guarded and secure. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hyperswitch@juspay.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const Connector = {
    Authipay: 'authipay',
    Adyenplatform: 'adyenplatform',
    StripeBillingTest: 'stripe_billing_test',
    Phonypay: 'phonypay',
    Fauxpay: 'fauxpay',
    Pretendpay: 'pretendpay',
    StripeTest: 'stripe_test',
    AdyenTest: 'adyen_test',
    CheckoutTest: 'checkout_test',
    PaypalTest: 'paypal_test',
    Aci: 'aci',
    Adyen: 'adyen',
    Affirm: 'affirm',
    Airwallex: 'airwallex',
    Amazonpay: 'amazonpay',
    Archipel: 'archipel',
    Authorizedotnet: 'authorizedotnet',
    Bambora: 'bambora',
    Bamboraapac: 'bamboraapac',
    Bankofamerica: 'bankofamerica',
    Barclaycard: 'barclaycard',
    Billwerk: 'billwerk',
    Bitpay: 'bitpay',
    Bluesnap: 'bluesnap',
    Blackhawknetwork: 'blackhawknetwork',
    Bluecode: 'bluecode',
    Boku: 'boku',
    Braintree: 'braintree',
    Breadpay: 'breadpay',
    Cashtocode: 'cashtocode',
    Celero: 'celero',
    Chargebee: 'chargebee',
    Checkbook: 'checkbook',
    Checkout: 'checkout',
    Coinbase: 'coinbase',
    Coingate: 'coingate',
    Custombilling: 'custombilling',
    Cryptopay: 'cryptopay',
    CtpMastercard: 'ctp_mastercard',
    CtpVisa: 'ctp_visa',
    Cybersource: 'cybersource',
    Datatrans: 'datatrans',
    Deutschebank: 'deutschebank',
    Digitalvirgo: 'digitalvirgo',
    Dlocal: 'dlocal',
    Dwolla: 'dwolla',
    Ebanx: 'ebanx',
    Elavon: 'elavon',
    Facilitapay: 'facilitapay',
    Fiserv: 'fiserv',
    Fiservemea: 'fiservemea',
    Fiuu: 'fiuu',
    Flexiti: 'flexiti',
    Forte: 'forte',
    Getnet: 'getnet',
    Globalpay: 'globalpay',
    Globepay: 'globepay',
    Gocardless: 'gocardless',
    Gpayments: 'gpayments',
    Hipay: 'hipay',
    Helcim: 'helcim',
    HyperswitchVault: 'hyperswitch_vault',
    Inespay: 'inespay',
    Iatapay: 'iatapay',
    Itaubank: 'itaubank',
    Jpmorgan: 'jpmorgan',
    Juspaythreedsserver: 'juspaythreedsserver',
    Klarna: 'klarna',
    Mifinity: 'mifinity',
    Mollie: 'mollie',
    Moneris: 'moneris',
    Multisafepay: 'multisafepay',
    Netcetera: 'netcetera',
    Nexinets: 'nexinets',
    Nexixpay: 'nexixpay',
    Nmi: 'nmi',
    Nomupay: 'nomupay',
    Noon: 'noon',
    Nordea: 'nordea',
    Novalnet: 'novalnet',
    Nuvei: 'nuvei',
    Opennode: 'opennode',
    Paybox: 'paybox',
    Payload: 'payload',
    Payme: 'payme',
    Payone: 'payone',
    Paypal: 'paypal',
    Paystack: 'paystack',
    Paytm: 'paytm',
    Payu: 'payu',
    Phonepe: 'phonepe',
    Placetopay: 'placetopay',
    Powertranz: 'powertranz',
    Prophetpay: 'prophetpay',
    Rapyd: 'rapyd',
    Razorpay: 'razorpay',
    Recurly: 'recurly',
    Redsys: 'redsys',
    Santander: 'santander',
    Shift4: 'shift4',
    Silverflow: 'silverflow',
    Square: 'square',
    Stax: 'stax',
    Stripe: 'stripe',
    Stripebilling: 'stripebilling',
    Taxjar: 'taxjar',
    Threedsecureio: 'threedsecureio',
    Tokenio: 'tokenio',
    Trustpay: 'trustpay',
    Tsys: 'tsys',
    Vgs: 'vgs',
    Volt: 'volt',
    Wellsfargo: 'wellsfargo',
    Wise: 'wise',
    Worldline: 'worldline',
    Worldpay: 'worldpay',
    Worldpayvantiv: 'worldpayvantiv',
    Worldpayxml: 'worldpayxml',
    Signifyd: 'signifyd',
    Plaid: 'plaid',
    Riskified: 'riskified',
    Xendit: 'xendit',
    Zen: 'zen',
    Zsl: 'zsl'
} as const;
export type Connector = typeof Connector[keyof typeof Connector];


export function instanceOfConnector(value: any): boolean {
    for (const key in Connector) {
        if (Object.prototype.hasOwnProperty.call(Connector, key)) {
            if (Connector[key as keyof typeof Connector] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ConnectorFromJSON(json: any): Connector {
    return ConnectorFromJSONTyped(json, false);
}

export function ConnectorFromJSONTyped(json: any, ignoreDiscriminator: boolean): Connector {
    return json as Connector;
}

export function ConnectorToJSON(value?: Connector | null): any {
    return value as any;
}

export function ConnectorToJSONTyped(value: any, ignoreDiscriminator: boolean): Connector {
    return value as Connector;
}

