/* tslint:disable */
/* eslint-disable */
/**
 * Hyperswitch - API Documentation
 *  ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app\'s client  |  Never share your secret api keys. Keep them guarded and secure. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hyperswitch@juspay.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Passing this object creates a new customer or attaches an existing customer to the payment
 * @export
 * @interface CustomerDetails
 */
export interface CustomerDetails {
    /**
     * The identifier for the customer.
     * @type {string}
     * @memberof CustomerDetails
     */
    id: string;
    /**
     * The customer's name
     * @type {string}
     * @memberof CustomerDetails
     */
    name?: string | null;
    /**
     * The customer's email address
     * @type {string}
     * @memberof CustomerDetails
     */
    email?: string | null;
    /**
     * The customer's phone number
     * @type {string}
     * @memberof CustomerDetails
     */
    phone?: string | null;
    /**
     * The country code for the customer's phone number
     * @type {string}
     * @memberof CustomerDetails
     */
    phoneCountryCode?: string | null;
    /**
     * The tax registration identifier of the customer.
     * @type {string}
     * @memberof CustomerDetails
     */
    taxRegistrationId?: string | null;
}

/**
 * Check if a given object implements the CustomerDetails interface.
 */
export function instanceOfCustomerDetails(value: object): value is CustomerDetails {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function CustomerDetailsFromJSON(json: any): CustomerDetails {
    return CustomerDetailsFromJSONTyped(json, false);
}

export function CustomerDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'email': json['email'] == null ? undefined : json['email'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'phoneCountryCode': json['phone_country_code'] == null ? undefined : json['phone_country_code'],
        'taxRegistrationId': json['tax_registration_id'] == null ? undefined : json['tax_registration_id'],
    };
}

export function CustomerDetailsToJSON(json: any): CustomerDetails {
    return CustomerDetailsToJSONTyped(json, false);
}

export function CustomerDetailsToJSONTyped(value?: CustomerDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'email': value['email'],
        'phone': value['phone'],
        'phone_country_code': value['phoneCountryCode'],
        'tax_registration_id': value['taxRegistrationId'],
    };
}

