/* tslint:disable */
/* eslint-disable */
/**
 * Hyperswitch - API Documentation
 *  ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app\'s client  |  Never share your secret api keys. Keep them guarded and secure. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hyperswitch@juspay.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CustomerDeleteResponse
 */
export interface CustomerDeleteResponse {
    /**
     * The identifier for the customer object
     * @type {string}
     * @memberof CustomerDeleteResponse
     */
    customerId: string;
    /**
     * Whether customer was deleted or not
     * @type {boolean}
     * @memberof CustomerDeleteResponse
     */
    customerDeleted: boolean;
    /**
     * Whether address was deleted or not
     * @type {boolean}
     * @memberof CustomerDeleteResponse
     */
    addressDeleted: boolean;
    /**
     * Whether payment methods deleted or not
     * @type {boolean}
     * @memberof CustomerDeleteResponse
     */
    paymentMethodsDeleted: boolean;
}

/**
 * Check if a given object implements the CustomerDeleteResponse interface.
 */
export function instanceOfCustomerDeleteResponse(value: object): value is CustomerDeleteResponse {
    if (!('customerId' in value) || value['customerId'] === undefined) return false;
    if (!('customerDeleted' in value) || value['customerDeleted'] === undefined) return false;
    if (!('addressDeleted' in value) || value['addressDeleted'] === undefined) return false;
    if (!('paymentMethodsDeleted' in value) || value['paymentMethodsDeleted'] === undefined) return false;
    return true;
}

export function CustomerDeleteResponseFromJSON(json: any): CustomerDeleteResponse {
    return CustomerDeleteResponseFromJSONTyped(json, false);
}

export function CustomerDeleteResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerDeleteResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'customerId': json['customer_id'],
        'customerDeleted': json['customer_deleted'],
        'addressDeleted': json['address_deleted'],
        'paymentMethodsDeleted': json['payment_methods_deleted'],
    };
}

export function CustomerDeleteResponseToJSON(json: any): CustomerDeleteResponse {
    return CustomerDeleteResponseToJSONTyped(json, false);
}

export function CustomerDeleteResponseToJSONTyped(value?: CustomerDeleteResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'customer_id': value['customerId'],
        'customer_deleted': value['customerDeleted'],
        'address_deleted': value['addressDeleted'],
        'payment_methods_deleted': value['paymentMethodsDeleted'],
    };
}

