/* tslint:disable */
/* eslint-disable */
/**
 * Hyperswitch - API Documentation
 *  ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app\'s client  |  Never share your secret api keys. Keep them guarded and secure. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hyperswitch@juspay.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * ephemeral_key for the customer_id mentioned
 * @export
 * @interface EphemeralKeyCreateResponse
 */
export interface EphemeralKeyCreateResponse {
    /**
     * customer_id to which this ephemeral key belongs to
     * @type {string}
     * @memberof EphemeralKeyCreateResponse
     */
    customerId: string;
    /**
     * time at which this ephemeral key was created
     * @type {number}
     * @memberof EphemeralKeyCreateResponse
     */
    createdAt: number;
    /**
     * time at which this ephemeral key would expire
     * @type {number}
     * @memberof EphemeralKeyCreateResponse
     */
    expires: number;
    /**
     * ephemeral key
     * @type {string}
     * @memberof EphemeralKeyCreateResponse
     */
    secret: string;
}

/**
 * Check if a given object implements the EphemeralKeyCreateResponse interface.
 */
export function instanceOfEphemeralKeyCreateResponse(value: object): value is EphemeralKeyCreateResponse {
    if (!('customerId' in value) || value['customerId'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('expires' in value) || value['expires'] === undefined) return false;
    if (!('secret' in value) || value['secret'] === undefined) return false;
    return true;
}

export function EphemeralKeyCreateResponseFromJSON(json: any): EphemeralKeyCreateResponse {
    return EphemeralKeyCreateResponseFromJSONTyped(json, false);
}

export function EphemeralKeyCreateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EphemeralKeyCreateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'customerId': json['customer_id'],
        'createdAt': json['created_at'],
        'expires': json['expires'],
        'secret': json['secret'],
    };
}

export function EphemeralKeyCreateResponseToJSON(json: any): EphemeralKeyCreateResponse {
    return EphemeralKeyCreateResponseToJSONTyped(json, false);
}

export function EphemeralKeyCreateResponseToJSONTyped(value?: EphemeralKeyCreateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'customer_id': value['customerId'],
        'created_at': value['createdAt'],
        'expires': value['expires'],
        'secret': value['secret'],
    };
}

