/* tslint:disable */
/* eslint-disable */
/**
 * Hyperswitch - API Documentation
 *  ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app\'s client  |  Never share your secret api keys. Keep them guarded and secure. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hyperswitch@juspay.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CardNetwork } from './CardNetwork';
import {
    CardNetworkFromJSON,
    CardNetworkFromJSONTyped,
    CardNetworkToJSON,
    CardNetworkToJSONTyped,
} from './CardNetwork';

/**
 * 
 * @export
 * @interface ExtendedCardInfo
 */
export interface ExtendedCardInfo {
    /**
     * The card number
     * @type {string}
     * @memberof ExtendedCardInfo
     */
    cardNumber: string;
    /**
     * The card's expiry month
     * @type {string}
     * @memberof ExtendedCardInfo
     */
    cardExpMonth: string;
    /**
     * The card's expiry year
     * @type {string}
     * @memberof ExtendedCardInfo
     */
    cardExpYear: string;
    /**
     * The card holder's name
     * @type {string}
     * @memberof ExtendedCardInfo
     */
    cardHolderName: string;
    /**
     * The CVC number for the card
     * @type {string}
     * @memberof ExtendedCardInfo
     */
    cardCvc: string;
    /**
     * The name of the issuer of card
     * @type {string}
     * @memberof ExtendedCardInfo
     */
    cardIssuer?: string | null;
    /**
     * 
     * @type {CardNetwork}
     * @memberof ExtendedCardInfo
     */
    cardNetwork?: CardNetwork | null;
    /**
     * 
     * @type {string}
     * @memberof ExtendedCardInfo
     */
    cardType?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ExtendedCardInfo
     */
    cardIssuingCountry?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ExtendedCardInfo
     */
    bankCode?: string | null;
}



/**
 * Check if a given object implements the ExtendedCardInfo interface.
 */
export function instanceOfExtendedCardInfo(value: object): value is ExtendedCardInfo {
    if (!('cardNumber' in value) || value['cardNumber'] === undefined) return false;
    if (!('cardExpMonth' in value) || value['cardExpMonth'] === undefined) return false;
    if (!('cardExpYear' in value) || value['cardExpYear'] === undefined) return false;
    if (!('cardHolderName' in value) || value['cardHolderName'] === undefined) return false;
    if (!('cardCvc' in value) || value['cardCvc'] === undefined) return false;
    return true;
}

export function ExtendedCardInfoFromJSON(json: any): ExtendedCardInfo {
    return ExtendedCardInfoFromJSONTyped(json, false);
}

export function ExtendedCardInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtendedCardInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'cardNumber': json['card_number'],
        'cardExpMonth': json['card_exp_month'],
        'cardExpYear': json['card_exp_year'],
        'cardHolderName': json['card_holder_name'],
        'cardCvc': json['card_cvc'],
        'cardIssuer': json['card_issuer'] == null ? undefined : json['card_issuer'],
        'cardNetwork': json['card_network'] == null ? undefined : CardNetworkFromJSON(json['card_network']),
        'cardType': json['card_type'] == null ? undefined : json['card_type'],
        'cardIssuingCountry': json['card_issuing_country'] == null ? undefined : json['card_issuing_country'],
        'bankCode': json['bank_code'] == null ? undefined : json['bank_code'],
    };
}

export function ExtendedCardInfoToJSON(json: any): ExtendedCardInfo {
    return ExtendedCardInfoToJSONTyped(json, false);
}

export function ExtendedCardInfoToJSONTyped(value?: ExtendedCardInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'card_number': value['cardNumber'],
        'card_exp_month': value['cardExpMonth'],
        'card_exp_year': value['cardExpYear'],
        'card_holder_name': value['cardHolderName'],
        'card_cvc': value['cardCvc'],
        'card_issuer': value['cardIssuer'],
        'card_network': CardNetworkToJSON(value['cardNetwork']),
        'card_type': value['cardType'],
        'card_issuing_country': value['cardIssuingCountry'],
        'bank_code': value['bankCode'],
    };
}

