/* tslint:disable */
/* eslint-disable */
/**
 * Hyperswitch - API Documentation
 *  ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app\'s client  |  Never share your secret api keys. Keep them guarded and secure. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hyperswitch@juspay.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { GiftCardAdditionalDataOneOf } from './GiftCardAdditionalDataOneOf';
import {
    instanceOfGiftCardAdditionalDataOneOf,
    GiftCardAdditionalDataOneOfFromJSON,
    GiftCardAdditionalDataOneOfFromJSONTyped,
    GiftCardAdditionalDataOneOfToJSON,
} from './GiftCardAdditionalDataOneOf';
import type { GiftCardAdditionalDataOneOf1 } from './GiftCardAdditionalDataOneOf1';
import {
    instanceOfGiftCardAdditionalDataOneOf1,
    GiftCardAdditionalDataOneOf1FromJSON,
    GiftCardAdditionalDataOneOf1FromJSONTyped,
    GiftCardAdditionalDataOneOf1ToJSON,
} from './GiftCardAdditionalDataOneOf1';
import type { GiftCardAdditionalDataOneOf2 } from './GiftCardAdditionalDataOneOf2';
import {
    instanceOfGiftCardAdditionalDataOneOf2,
    GiftCardAdditionalDataOneOf2FromJSON,
    GiftCardAdditionalDataOneOf2FromJSONTyped,
    GiftCardAdditionalDataOneOf2ToJSON,
} from './GiftCardAdditionalDataOneOf2';

/**
 * @type GiftCardAdditionalData
 * 
 * @export
 */
export type GiftCardAdditionalData = GiftCardAdditionalDataOneOf | GiftCardAdditionalDataOneOf1 | GiftCardAdditionalDataOneOf2;

export function GiftCardAdditionalDataFromJSON(json: any): GiftCardAdditionalData {
    return GiftCardAdditionalDataFromJSONTyped(json, false);
}

export function GiftCardAdditionalDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): GiftCardAdditionalData {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfGiftCardAdditionalDataOneOf(json)) {
        return GiftCardAdditionalDataOneOfFromJSONTyped(json, true);
    }
    if (instanceOfGiftCardAdditionalDataOneOf1(json)) {
        return GiftCardAdditionalDataOneOf1FromJSONTyped(json, true);
    }
    if (instanceOfGiftCardAdditionalDataOneOf2(json)) {
        return GiftCardAdditionalDataOneOf2FromJSONTyped(json, true);
    }

    return {} as any;
}

export function GiftCardAdditionalDataToJSON(json: any): any {
    return GiftCardAdditionalDataToJSONTyped(json, false);
}

export function GiftCardAdditionalDataToJSONTyped(value?: GiftCardAdditionalData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfGiftCardAdditionalDataOneOf(value)) {
        return GiftCardAdditionalDataOneOfToJSON(value as GiftCardAdditionalDataOneOf);
    }
    if (instanceOfGiftCardAdditionalDataOneOf1(value)) {
        return GiftCardAdditionalDataOneOf1ToJSON(value as GiftCardAdditionalDataOneOf1);
    }
    if (instanceOfGiftCardAdditionalDataOneOf2(value)) {
        return GiftCardAdditionalDataOneOf2ToJSON(value as GiftCardAdditionalDataOneOf2);
    }

    return {};
}

