/* tslint:disable */
/* eslint-disable */
/**
 * Hyperswitch - API Documentation
 *  ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app\'s client  |  Never share your secret api keys. Keep them guarded and secure. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hyperswitch@juspay.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JCSVoucherData
 */
export interface JCSVoucherData {
    /**
     * The billing first name for Japanese convenience stores
     * @type {string}
     * @memberof JCSVoucherData
     */
    firstName?: string | null;
    /**
     * The billing second name Japanese convenience stores
     * @type {string}
     * @memberof JCSVoucherData
     */
    lastName?: string | null;
    /**
     * The Email ID for Japanese convenience stores
     * @type {string}
     * @memberof JCSVoucherData
     */
    email?: string | null;
    /**
     * The telephone number for Japanese convenience stores
     * @type {string}
     * @memberof JCSVoucherData
     */
    phoneNumber?: string | null;
}

/**
 * Check if a given object implements the JCSVoucherData interface.
 */
export function instanceOfJCSVoucherData(value: object): value is JCSVoucherData {
    return true;
}

export function JCSVoucherDataFromJSON(json: any): JCSVoucherData {
    return JCSVoucherDataFromJSONTyped(json, false);
}

export function JCSVoucherDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): JCSVoucherData {
    if (json == null) {
        return json;
    }
    return {
        
        'firstName': json['first_name'] == null ? undefined : json['first_name'],
        'lastName': json['last_name'] == null ? undefined : json['last_name'],
        'email': json['email'] == null ? undefined : json['email'],
        'phoneNumber': json['phone_number'] == null ? undefined : json['phone_number'],
    };
}

export function JCSVoucherDataToJSON(json: any): JCSVoucherData {
    return JCSVoucherDataToJSONTyped(json, false);
}

export function JCSVoucherDataToJSONTyped(value?: JCSVoucherData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'first_name': value['firstName'],
        'last_name': value['lastName'],
        'email': value['email'],
        'phone_number': value['phoneNumber'],
    };
}

