/* tslint:disable */
/* eslint-disable */
/**
 * Hyperswitch - API Documentation
 *  ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app\'s client  |  Never share your secret api keys. Keep them guarded and secure. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hyperswitch@juspay.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MerchantAccountType } from './MerchantAccountType';
import {
    MerchantAccountTypeFromJSON,
    MerchantAccountTypeFromJSONTyped,
    MerchantAccountTypeToJSON,
    MerchantAccountTypeToJSONTyped,
} from './MerchantAccountType';
import type { MerchantDetails } from './MerchantDetails';
import {
    MerchantDetailsFromJSON,
    MerchantDetailsFromJSONTyped,
    MerchantDetailsToJSON,
    MerchantDetailsToJSONTyped,
} from './MerchantDetails';
import type { MerchantProductType } from './MerchantProductType';
import {
    MerchantProductTypeFromJSON,
    MerchantProductTypeFromJSONTyped,
    MerchantProductTypeToJSON,
    MerchantProductTypeToJSONTyped,
} from './MerchantProductType';
import type { ReconStatus } from './ReconStatus';
import {
    ReconStatusFromJSON,
    ReconStatusFromJSONTyped,
    ReconStatusToJSON,
    ReconStatusToJSONTyped,
} from './ReconStatus';
import type { WebhookDetails } from './WebhookDetails';
import {
    WebhookDetailsFromJSON,
    WebhookDetailsFromJSONTyped,
    WebhookDetailsToJSON,
    WebhookDetailsToJSONTyped,
} from './WebhookDetails';
import type { StaticRoutingAlgorithm } from './StaticRoutingAlgorithm';
import {
    StaticRoutingAlgorithmFromJSON,
    StaticRoutingAlgorithmFromJSONTyped,
    StaticRoutingAlgorithmToJSON,
    StaticRoutingAlgorithmToJSONTyped,
} from './StaticRoutingAlgorithm';
import type { BusinessCollectLinkConfig } from './BusinessCollectLinkConfig';
import {
    BusinessCollectLinkConfigFromJSON,
    BusinessCollectLinkConfigFromJSONTyped,
    BusinessCollectLinkConfigToJSON,
    BusinessCollectLinkConfigToJSONTyped,
} from './BusinessCollectLinkConfig';
import type { PrimaryBusinessDetails } from './PrimaryBusinessDetails';
import {
    PrimaryBusinessDetailsFromJSON,
    PrimaryBusinessDetailsFromJSONTyped,
    PrimaryBusinessDetailsToJSON,
    PrimaryBusinessDetailsToJSONTyped,
} from './PrimaryBusinessDetails';

/**
 * 
 * @export
 * @interface MerchantAccountResponse
 */
export interface MerchantAccountResponse {
    /**
     * The identifier for the Merchant Account
     * @type {string}
     * @memberof MerchantAccountResponse
     */
    merchantId: string;
    /**
     * Name of the Merchant Account
     * @type {string}
     * @memberof MerchantAccountResponse
     */
    merchantName?: string | null;
    /**
     * The URL to redirect after completion of the payment
     * @type {string}
     * @memberof MerchantAccountResponse
     */
    returnUrl?: string | null;
    /**
     * A boolean value to indicate if payment response hash needs to be enabled
     * @type {boolean}
     * @memberof MerchantAccountResponse
     */
    enablePaymentResponseHash: boolean;
    /**
     * Refers to the hash key used for calculating the signature for webhooks and redirect response. If the value is not provided, a value is automatically generated.
     * @type {string}
     * @memberof MerchantAccountResponse
     */
    paymentResponseHashKey?: string | null;
    /**
     * A boolean value to indicate if redirect to merchant with http post needs to be enabled
     * @type {boolean}
     * @memberof MerchantAccountResponse
     */
    redirectToMerchantWithHttpPost: boolean;
    /**
     * 
     * @type {MerchantDetails}
     * @memberof MerchantAccountResponse
     */
    merchantDetails?: MerchantDetails | null;
    /**
     * 
     * @type {WebhookDetails}
     * @memberof MerchantAccountResponse
     */
    webhookDetails?: WebhookDetails | null;
    /**
     * 
     * @type {StaticRoutingAlgorithm}
     * @memberof MerchantAccountResponse
     */
    payoutRoutingAlgorithm?: StaticRoutingAlgorithm | null;
    /**
     * A boolean value to indicate if the merchant is a sub-merchant under a master or a parent merchant. By default, its value is false.
     * @type {boolean}
     * @memberof MerchantAccountResponse
     */
    subMerchantsEnabled?: boolean | null;
    /**
     * Refers to the Parent Merchant ID if the merchant being created is a sub-merchant
     * @type {string}
     * @memberof MerchantAccountResponse
     */
    parentMerchantId?: string | null;
    /**
     * API key that will be used for server side API access
     * @type {string}
     * @memberof MerchantAccountResponse
     */
    publishableKey?: string | null;
    /**
     * Metadata is useful for storing additional, unstructured information on an object.
     * @type {object}
     * @memberof MerchantAccountResponse
     */
    metadata?: object | null;
    /**
     * An identifier for the vault used to store payment method information.
     * @type {string}
     * @memberof MerchantAccountResponse
     */
    lockerId?: string | null;
    /**
     * Details about the primary business unit of the merchant account
     * @type {Array<PrimaryBusinessDetails>}
     * @memberof MerchantAccountResponse
     */
    primaryBusinessDetails: Array<PrimaryBusinessDetails>;
    /**
     * 
     * @type {StaticRoutingAlgorithm}
     * @memberof MerchantAccountResponse
     */
    frmRoutingAlgorithm?: StaticRoutingAlgorithm | null;
    /**
     * The organization id merchant is associated with
     * @type {string}
     * @memberof MerchantAccountResponse
     */
    organizationId: string;
    /**
     * A boolean value to indicate if the merchant has recon service is enabled or not, by default value is false
     * @type {boolean}
     * @memberof MerchantAccountResponse
     */
    isReconEnabled: boolean;
    /**
     * The default profile that must be used for creating merchant accounts and payments
     * @type {string}
     * @memberof MerchantAccountResponse
     */
    defaultProfile?: string | null;
    /**
     * 
     * @type {ReconStatus}
     * @memberof MerchantAccountResponse
     */
    reconStatus: ReconStatus;
    /**
     * 
     * @type {BusinessCollectLinkConfig}
     * @memberof MerchantAccountResponse
     */
    pmCollectLinkConfig?: BusinessCollectLinkConfig | null;
    /**
     * 
     * @type {MerchantProductType}
     * @memberof MerchantAccountResponse
     */
    productType?: MerchantProductType | null;
    /**
     * 
     * @type {MerchantAccountType}
     * @memberof MerchantAccountResponse
     */
    merchantAccountType: MerchantAccountType;
}



/**
 * Check if a given object implements the MerchantAccountResponse interface.
 */
export function instanceOfMerchantAccountResponse(value: object): value is MerchantAccountResponse {
    if (!('merchantId' in value) || value['merchantId'] === undefined) return false;
    if (!('enablePaymentResponseHash' in value) || value['enablePaymentResponseHash'] === undefined) return false;
    if (!('redirectToMerchantWithHttpPost' in value) || value['redirectToMerchantWithHttpPost'] === undefined) return false;
    if (!('primaryBusinessDetails' in value) || value['primaryBusinessDetails'] === undefined) return false;
    if (!('organizationId' in value) || value['organizationId'] === undefined) return false;
    if (!('isReconEnabled' in value) || value['isReconEnabled'] === undefined) return false;
    if (!('reconStatus' in value) || value['reconStatus'] === undefined) return false;
    if (!('merchantAccountType' in value) || value['merchantAccountType'] === undefined) return false;
    return true;
}

export function MerchantAccountResponseFromJSON(json: any): MerchantAccountResponse {
    return MerchantAccountResponseFromJSONTyped(json, false);
}

export function MerchantAccountResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MerchantAccountResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'merchantId': json['merchant_id'],
        'merchantName': json['merchant_name'] == null ? undefined : json['merchant_name'],
        'returnUrl': json['return_url'] == null ? undefined : json['return_url'],
        'enablePaymentResponseHash': json['enable_payment_response_hash'],
        'paymentResponseHashKey': json['payment_response_hash_key'] == null ? undefined : json['payment_response_hash_key'],
        'redirectToMerchantWithHttpPost': json['redirect_to_merchant_with_http_post'],
        'merchantDetails': json['merchant_details'] == null ? undefined : MerchantDetailsFromJSON(json['merchant_details']),
        'webhookDetails': json['webhook_details'] == null ? undefined : WebhookDetailsFromJSON(json['webhook_details']),
        'payoutRoutingAlgorithm': json['payout_routing_algorithm'] == null ? undefined : StaticRoutingAlgorithmFromJSON(json['payout_routing_algorithm']),
        'subMerchantsEnabled': json['sub_merchants_enabled'] == null ? undefined : json['sub_merchants_enabled'],
        'parentMerchantId': json['parent_merchant_id'] == null ? undefined : json['parent_merchant_id'],
        'publishableKey': json['publishable_key'] == null ? undefined : json['publishable_key'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'lockerId': json['locker_id'] == null ? undefined : json['locker_id'],
        'primaryBusinessDetails': ((json['primary_business_details'] as Array<any>).map(PrimaryBusinessDetailsFromJSON)),
        'frmRoutingAlgorithm': json['frm_routing_algorithm'] == null ? undefined : StaticRoutingAlgorithmFromJSON(json['frm_routing_algorithm']),
        'organizationId': json['organization_id'],
        'isReconEnabled': json['is_recon_enabled'],
        'defaultProfile': json['default_profile'] == null ? undefined : json['default_profile'],
        'reconStatus': ReconStatusFromJSON(json['recon_status']),
        'pmCollectLinkConfig': json['pm_collect_link_config'] == null ? undefined : BusinessCollectLinkConfigFromJSON(json['pm_collect_link_config']),
        'productType': json['product_type'] == null ? undefined : MerchantProductTypeFromJSON(json['product_type']),
        'merchantAccountType': MerchantAccountTypeFromJSON(json['merchant_account_type']),
    };
}

export function MerchantAccountResponseToJSON(json: any): MerchantAccountResponse {
    return MerchantAccountResponseToJSONTyped(json, false);
}

export function MerchantAccountResponseToJSONTyped(value?: MerchantAccountResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'merchant_id': value['merchantId'],
        'merchant_name': value['merchantName'],
        'return_url': value['returnUrl'],
        'enable_payment_response_hash': value['enablePaymentResponseHash'],
        'payment_response_hash_key': value['paymentResponseHashKey'],
        'redirect_to_merchant_with_http_post': value['redirectToMerchantWithHttpPost'],
        'merchant_details': MerchantDetailsToJSON(value['merchantDetails']),
        'webhook_details': WebhookDetailsToJSON(value['webhookDetails']),
        'payout_routing_algorithm': StaticRoutingAlgorithmToJSON(value['payoutRoutingAlgorithm']),
        'sub_merchants_enabled': value['subMerchantsEnabled'],
        'parent_merchant_id': value['parentMerchantId'],
        'publishable_key': value['publishableKey'],
        'metadata': value['metadata'],
        'locker_id': value['lockerId'],
        'primary_business_details': ((value['primaryBusinessDetails'] as Array<any>).map(PrimaryBusinessDetailsToJSON)),
        'frm_routing_algorithm': StaticRoutingAlgorithmToJSON(value['frmRoutingAlgorithm']),
        'organization_id': value['organizationId'],
        'is_recon_enabled': value['isReconEnabled'],
        'default_profile': value['defaultProfile'],
        'recon_status': ReconStatusToJSON(value['reconStatus']),
        'pm_collect_link_config': BusinessCollectLinkConfigToJSON(value['pmCollectLinkConfig']),
        'product_type': MerchantProductTypeToJSON(value['productType']),
        'merchant_account_type': MerchantAccountTypeToJSON(value['merchantAccountType']),
    };
}

