/* tslint:disable */
/* eslint-disable */
/**
 * Hyperswitch - API Documentation
 *  ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app\'s client  |  Never share your secret api keys. Keep them guarded and secure. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hyperswitch@juspay.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Polish Elixir payment system
 * @export
 * @interface MerchantAccountDataOneOf5Elixir
 */
export interface MerchantAccountDataOneOf5Elixir {
    /**
     * Polish account number (26 digits)
     * @type {string}
     * @memberof MerchantAccountDataOneOf5Elixir
     */
    accountNumber: string;
    /**
     * Polish IBAN (28 chars)
     * @type {string}
     * @memberof MerchantAccountDataOneOf5Elixir
     */
    iban: string;
    /**
     * Account holder name
     * @type {string}
     * @memberof MerchantAccountDataOneOf5Elixir
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof MerchantAccountDataOneOf5Elixir
     */
    connectorRecipientId?: string | null;
}

/**
 * Check if a given object implements the MerchantAccountDataOneOf5Elixir interface.
 */
export function instanceOfMerchantAccountDataOneOf5Elixir(value: object): value is MerchantAccountDataOneOf5Elixir {
    if (!('accountNumber' in value) || value['accountNumber'] === undefined) return false;
    if (!('iban' in value) || value['iban'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function MerchantAccountDataOneOf5ElixirFromJSON(json: any): MerchantAccountDataOneOf5Elixir {
    return MerchantAccountDataOneOf5ElixirFromJSONTyped(json, false);
}

export function MerchantAccountDataOneOf5ElixirFromJSONTyped(json: any, ignoreDiscriminator: boolean): MerchantAccountDataOneOf5Elixir {
    if (json == null) {
        return json;
    }
    return {
        
        'accountNumber': json['account_number'],
        'iban': json['iban'],
        'name': json['name'],
        'connectorRecipientId': json['connector_recipient_id'] == null ? undefined : json['connector_recipient_id'],
    };
}

export function MerchantAccountDataOneOf5ElixirToJSON(json: any): MerchantAccountDataOneOf5Elixir {
    return MerchantAccountDataOneOf5ElixirToJSONTyped(json, false);
}

export function MerchantAccountDataOneOf5ElixirToJSONTyped(value?: MerchantAccountDataOneOf5Elixir | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'account_number': value['accountNumber'],
        'iban': value['iban'],
        'name': value['name'],
        'connector_recipient_id': value['connectorRecipientId'],
    };
}

