/* tslint:disable */
/* eslint-disable */
/**
 * Hyperswitch - API Documentation
 *  ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app\'s client  |  Never share your secret api keys. Keep them guarded and secure. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hyperswitch@juspay.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MerchantAccountDataOneOf4SepaInstant } from './MerchantAccountDataOneOf4SepaInstant';
import {
    MerchantAccountDataOneOf4SepaInstantFromJSON,
    MerchantAccountDataOneOf4SepaInstantFromJSONTyped,
    MerchantAccountDataOneOf4SepaInstantToJSON,
    MerchantAccountDataOneOf4SepaInstantToJSONTyped,
} from './MerchantAccountDataOneOf4SepaInstant';

/**
 * 
 * @export
 * @interface MerchantAccountDataOneOf4
 */
export interface MerchantAccountDataOneOf4 {
    /**
     * 
     * @type {MerchantAccountDataOneOf4SepaInstant}
     * @memberof MerchantAccountDataOneOf4
     */
    sepaInstant: MerchantAccountDataOneOf4SepaInstant;
}

/**
 * Check if a given object implements the MerchantAccountDataOneOf4 interface.
 */
export function instanceOfMerchantAccountDataOneOf4(value: object): value is MerchantAccountDataOneOf4 {
    if (!('sepaInstant' in value) || value['sepaInstant'] === undefined) return false;
    return true;
}

export function MerchantAccountDataOneOf4FromJSON(json: any): MerchantAccountDataOneOf4 {
    return MerchantAccountDataOneOf4FromJSONTyped(json, false);
}

export function MerchantAccountDataOneOf4FromJSONTyped(json: any, ignoreDiscriminator: boolean): MerchantAccountDataOneOf4 {
    if (json == null) {
        return json;
    }
    return {
        
        'sepaInstant': MerchantAccountDataOneOf4SepaInstantFromJSON(json['sepa_instant']),
    };
}

export function MerchantAccountDataOneOf4ToJSON(json: any): MerchantAccountDataOneOf4 {
    return MerchantAccountDataOneOf4ToJSONTyped(json, false);
}

export function MerchantAccountDataOneOf4ToJSONTyped(value?: MerchantAccountDataOneOf4 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sepa_instant': MerchantAccountDataOneOf4SepaInstantToJSON(value['sepaInstant']),
    };
}

