/* tslint:disable */
/* eslint-disable */
/**
 * Hyperswitch - API Documentation
 *  ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app\'s client  |  Never share your secret api keys. Keep them guarded and secure. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hyperswitch@juspay.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MobilePaymentConsent } from './MobilePaymentConsent';
import {
    MobilePaymentConsentFromJSON,
    MobilePaymentConsentFromJSONTyped,
    MobilePaymentConsentToJSON,
    MobilePaymentConsentToJSONTyped,
} from './MobilePaymentConsent';

/**
 * 
 * @export
 * @interface MobilePaymentNextStepData
 */
export interface MobilePaymentNextStepData {
    /**
     * 
     * @type {MobilePaymentConsent}
     * @memberof MobilePaymentNextStepData
     */
    consentDataRequired: MobilePaymentConsent;
}



/**
 * Check if a given object implements the MobilePaymentNextStepData interface.
 */
export function instanceOfMobilePaymentNextStepData(value: object): value is MobilePaymentNextStepData {
    if (!('consentDataRequired' in value) || value['consentDataRequired'] === undefined) return false;
    return true;
}

export function MobilePaymentNextStepDataFromJSON(json: any): MobilePaymentNextStepData {
    return MobilePaymentNextStepDataFromJSONTyped(json, false);
}

export function MobilePaymentNextStepDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): MobilePaymentNextStepData {
    if (json == null) {
        return json;
    }
    return {
        
        'consentDataRequired': MobilePaymentConsentFromJSON(json['consent_data_required']),
    };
}

export function MobilePaymentNextStepDataToJSON(json: any): MobilePaymentNextStepData {
    return MobilePaymentNextStepDataToJSONTyped(json, false);
}

export function MobilePaymentNextStepDataToJSONTyped(value?: MobilePaymentNextStepData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'consent_data_required': MobilePaymentConsentToJSON(value['consentDataRequired']),
    };
}

