/* tslint:disable */
/* eslint-disable */
/**
 * Hyperswitch - API Documentation
 *  ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app\'s client  |  Never share your secret api keys. Keep them guarded and secure. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hyperswitch@juspay.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SessionToken } from './SessionToken';
import {
    SessionTokenFromJSON,
    SessionTokenFromJSONTyped,
    SessionTokenToJSON,
    SessionTokenToJSONTyped,
} from './SessionToken';

/**
 * Contains third party sdk session token response
 * @export
 * @interface NextActionDataOneOf3
 */
export interface NextActionDataOneOf3 {
    /**
     * 
     * @type {SessionToken}
     * @memberof NextActionDataOneOf3
     */
    sessionToken?: SessionToken | null;
    /**
     * 
     * @type {string}
     * @memberof NextActionDataOneOf3
     */
    type: NextActionDataOneOf3TypeEnum;
}


/**
 * @export
 */
export const NextActionDataOneOf3TypeEnum = {
    ThirdPartySdkSessionToken: 'third_party_sdk_session_token'
} as const;
export type NextActionDataOneOf3TypeEnum = typeof NextActionDataOneOf3TypeEnum[keyof typeof NextActionDataOneOf3TypeEnum];


/**
 * Check if a given object implements the NextActionDataOneOf3 interface.
 */
export function instanceOfNextActionDataOneOf3(value: object): value is NextActionDataOneOf3 {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function NextActionDataOneOf3FromJSON(json: any): NextActionDataOneOf3 {
    return NextActionDataOneOf3FromJSONTyped(json, false);
}

export function NextActionDataOneOf3FromJSONTyped(json: any, ignoreDiscriminator: boolean): NextActionDataOneOf3 {
    if (json == null) {
        return json;
    }
    return {
        
        'sessionToken': json['session_token'] == null ? undefined : SessionTokenFromJSON(json['session_token']),
        'type': json['type'],
    };
}

export function NextActionDataOneOf3ToJSON(json: any): NextActionDataOneOf3 {
    return NextActionDataOneOf3ToJSONTyped(json, false);
}

export function NextActionDataOneOf3ToJSONTyped(value?: NextActionDataOneOf3 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'session_token': SessionTokenToJSON(value['sessionToken']),
        'type': value['type'],
    };
}

