/* tslint:disable */
/* eslint-disable */
/**
 * Hyperswitch - API Documentation
 *  ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app\'s client  |  Never share your secret api keys. Keep them guarded and secure. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hyperswitch@juspay.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ThreeDsData } from './ThreeDsData';
import {
    ThreeDsDataFromJSON,
    ThreeDsDataFromJSONTyped,
    ThreeDsDataToJSON,
    ThreeDsDataToJSONTyped,
} from './ThreeDsData';

/**
 * Contains the information regarding three_ds_method_data submission, three_ds authentication, and authorization flows
 * @export
 * @interface NextActionDataOneOf8
 */
export interface NextActionDataOneOf8 {
    /**
     * 
     * @type {ThreeDsData}
     * @memberof NextActionDataOneOf8
     */
    threeDsData: ThreeDsData;
    /**
     * 
     * @type {string}
     * @memberof NextActionDataOneOf8
     */
    type: NextActionDataOneOf8TypeEnum;
}


/**
 * @export
 */
export const NextActionDataOneOf8TypeEnum = {
    ThreeDsInvoke: 'three_ds_invoke'
} as const;
export type NextActionDataOneOf8TypeEnum = typeof NextActionDataOneOf8TypeEnum[keyof typeof NextActionDataOneOf8TypeEnum];


/**
 * Check if a given object implements the NextActionDataOneOf8 interface.
 */
export function instanceOfNextActionDataOneOf8(value: object): value is NextActionDataOneOf8 {
    if (!('threeDsData' in value) || value['threeDsData'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function NextActionDataOneOf8FromJSON(json: any): NextActionDataOneOf8 {
    return NextActionDataOneOf8FromJSONTyped(json, false);
}

export function NextActionDataOneOf8FromJSONTyped(json: any, ignoreDiscriminator: boolean): NextActionDataOneOf8 {
    if (json == null) {
        return json;
    }
    return {
        
        'threeDsData': ThreeDsDataFromJSON(json['three_ds_data']),
        'type': json['type'],
    };
}

export function NextActionDataOneOf8ToJSON(json: any): NextActionDataOneOf8 {
    return NextActionDataOneOf8ToJSONTyped(json, false);
}

export function NextActionDataOneOf8ToJSONTyped(value?: NextActionDataOneOf8 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'three_ds_data': ThreeDsDataToJSON(value['threeDsData']),
        'type': value['type'],
    };
}

