/* tslint:disable */
/* eslint-disable */
/**
 * Hyperswitch - API Documentation
 *  ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app\'s client  |  Never share your secret api keys. Keep them guarded and secure. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hyperswitch@juspay.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { PayLaterDataOneOf } from './PayLaterDataOneOf';
import {
    instanceOfPayLaterDataOneOf,
    PayLaterDataOneOfFromJSON,
    PayLaterDataOneOfFromJSONTyped,
    PayLaterDataOneOfToJSON,
} from './PayLaterDataOneOf';
import type { PayLaterDataOneOf1 } from './PayLaterDataOneOf1';
import {
    instanceOfPayLaterDataOneOf1,
    PayLaterDataOneOf1FromJSON,
    PayLaterDataOneOf1FromJSONTyped,
    PayLaterDataOneOf1ToJSON,
} from './PayLaterDataOneOf1';
import type { PayLaterDataOneOf2 } from './PayLaterDataOneOf2';
import {
    instanceOfPayLaterDataOneOf2,
    PayLaterDataOneOf2FromJSON,
    PayLaterDataOneOf2FromJSONTyped,
    PayLaterDataOneOf2ToJSON,
} from './PayLaterDataOneOf2';
import type { PayLaterDataOneOf3 } from './PayLaterDataOneOf3';
import {
    instanceOfPayLaterDataOneOf3,
    PayLaterDataOneOf3FromJSON,
    PayLaterDataOneOf3FromJSONTyped,
    PayLaterDataOneOf3ToJSON,
} from './PayLaterDataOneOf3';
import type { PayLaterDataOneOf4 } from './PayLaterDataOneOf4';
import {
    instanceOfPayLaterDataOneOf4,
    PayLaterDataOneOf4FromJSON,
    PayLaterDataOneOf4FromJSONTyped,
    PayLaterDataOneOf4ToJSON,
} from './PayLaterDataOneOf4';
import type { PayLaterDataOneOf5 } from './PayLaterDataOneOf5';
import {
    instanceOfPayLaterDataOneOf5,
    PayLaterDataOneOf5FromJSON,
    PayLaterDataOneOf5FromJSONTyped,
    PayLaterDataOneOf5ToJSON,
} from './PayLaterDataOneOf5';
import type { PayLaterDataOneOf6 } from './PayLaterDataOneOf6';
import {
    instanceOfPayLaterDataOneOf6,
    PayLaterDataOneOf6FromJSON,
    PayLaterDataOneOf6FromJSONTyped,
    PayLaterDataOneOf6ToJSON,
} from './PayLaterDataOneOf6';
import type { PayLaterDataOneOf7 } from './PayLaterDataOneOf7';
import {
    instanceOfPayLaterDataOneOf7,
    PayLaterDataOneOf7FromJSON,
    PayLaterDataOneOf7FromJSONTyped,
    PayLaterDataOneOf7ToJSON,
} from './PayLaterDataOneOf7';
import type { PayLaterDataOneOf8 } from './PayLaterDataOneOf8';
import {
    instanceOfPayLaterDataOneOf8,
    PayLaterDataOneOf8FromJSON,
    PayLaterDataOneOf8FromJSONTyped,
    PayLaterDataOneOf8ToJSON,
} from './PayLaterDataOneOf8';
import type { PayLaterDataOneOf9 } from './PayLaterDataOneOf9';
import {
    instanceOfPayLaterDataOneOf9,
    PayLaterDataOneOf9FromJSON,
    PayLaterDataOneOf9FromJSONTyped,
    PayLaterDataOneOf9ToJSON,
} from './PayLaterDataOneOf9';

/**
 * @type PayLaterData
 * 
 * @export
 */
export type PayLaterData = PayLaterDataOneOf | PayLaterDataOneOf1 | PayLaterDataOneOf2 | PayLaterDataOneOf3 | PayLaterDataOneOf4 | PayLaterDataOneOf5 | PayLaterDataOneOf6 | PayLaterDataOneOf7 | PayLaterDataOneOf8 | PayLaterDataOneOf9;

export function PayLaterDataFromJSON(json: any): PayLaterData {
    return PayLaterDataFromJSONTyped(json, false);
}

export function PayLaterDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): PayLaterData {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfPayLaterDataOneOf(json)) {
        return PayLaterDataOneOfFromJSONTyped(json, true);
    }
    if (instanceOfPayLaterDataOneOf1(json)) {
        return PayLaterDataOneOf1FromJSONTyped(json, true);
    }
    if (instanceOfPayLaterDataOneOf2(json)) {
        return PayLaterDataOneOf2FromJSONTyped(json, true);
    }
    if (instanceOfPayLaterDataOneOf3(json)) {
        return PayLaterDataOneOf3FromJSONTyped(json, true);
    }
    if (instanceOfPayLaterDataOneOf4(json)) {
        return PayLaterDataOneOf4FromJSONTyped(json, true);
    }
    if (instanceOfPayLaterDataOneOf5(json)) {
        return PayLaterDataOneOf5FromJSONTyped(json, true);
    }
    if (instanceOfPayLaterDataOneOf6(json)) {
        return PayLaterDataOneOf6FromJSONTyped(json, true);
    }
    if (instanceOfPayLaterDataOneOf7(json)) {
        return PayLaterDataOneOf7FromJSONTyped(json, true);
    }
    if (instanceOfPayLaterDataOneOf8(json)) {
        return PayLaterDataOneOf8FromJSONTyped(json, true);
    }
    if (instanceOfPayLaterDataOneOf9(json)) {
        return PayLaterDataOneOf9FromJSONTyped(json, true);
    }

    return {} as any;
}

export function PayLaterDataToJSON(json: any): any {
    return PayLaterDataToJSONTyped(json, false);
}

export function PayLaterDataToJSONTyped(value?: PayLaterData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfPayLaterDataOneOf(value)) {
        return PayLaterDataOneOfToJSON(value as PayLaterDataOneOf);
    }
    if (instanceOfPayLaterDataOneOf1(value)) {
        return PayLaterDataOneOf1ToJSON(value as PayLaterDataOneOf1);
    }
    if (instanceOfPayLaterDataOneOf2(value)) {
        return PayLaterDataOneOf2ToJSON(value as PayLaterDataOneOf2);
    }
    if (instanceOfPayLaterDataOneOf3(value)) {
        return PayLaterDataOneOf3ToJSON(value as PayLaterDataOneOf3);
    }
    if (instanceOfPayLaterDataOneOf4(value)) {
        return PayLaterDataOneOf4ToJSON(value as PayLaterDataOneOf4);
    }
    if (instanceOfPayLaterDataOneOf5(value)) {
        return PayLaterDataOneOf5ToJSON(value as PayLaterDataOneOf5);
    }
    if (instanceOfPayLaterDataOneOf6(value)) {
        return PayLaterDataOneOf6ToJSON(value as PayLaterDataOneOf6);
    }
    if (instanceOfPayLaterDataOneOf7(value)) {
        return PayLaterDataOneOf7ToJSON(value as PayLaterDataOneOf7);
    }
    if (instanceOfPayLaterDataOneOf8(value)) {
        return PayLaterDataOneOf8ToJSON(value as PayLaterDataOneOf8);
    }
    if (instanceOfPayLaterDataOneOf9(value)) {
        return PayLaterDataOneOf9ToJSON(value as PayLaterDataOneOf9);
    }

    return {};
}

