/* tslint:disable */
/* eslint-disable */
/**
 * Hyperswitch - API Documentation
 *  ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app\'s client  |  Never share your secret api keys. Keep them guarded and secure. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hyperswitch@juspay.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * For Klarna Sdk as PayLater Option
 * @export
 * @interface PayLaterDataOneOf1KlarnaSdk
 */
export interface PayLaterDataOneOf1KlarnaSdk {
    /**
     * The token for the sdk workflow
     * @type {string}
     * @memberof PayLaterDataOneOf1KlarnaSdk
     */
    token: string;
}

/**
 * Check if a given object implements the PayLaterDataOneOf1KlarnaSdk interface.
 */
export function instanceOfPayLaterDataOneOf1KlarnaSdk(value: object): value is PayLaterDataOneOf1KlarnaSdk {
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function PayLaterDataOneOf1KlarnaSdkFromJSON(json: any): PayLaterDataOneOf1KlarnaSdk {
    return PayLaterDataOneOf1KlarnaSdkFromJSONTyped(json, false);
}

export function PayLaterDataOneOf1KlarnaSdkFromJSONTyped(json: any, ignoreDiscriminator: boolean): PayLaterDataOneOf1KlarnaSdk {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
    };
}

export function PayLaterDataOneOf1KlarnaSdkToJSON(json: any): PayLaterDataOneOf1KlarnaSdk {
    return PayLaterDataOneOf1KlarnaSdkToJSONTyped(json, false);
}

export function PayLaterDataOneOf1KlarnaSdkToJSONTyped(value?: PayLaterDataOneOf1KlarnaSdk | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
    };
}

