/* tslint:disable */
/* eslint-disable */
/**
 * Hyperswitch - API Documentation
 *  ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app\'s client  |  Never share your secret api keys. Keep them guarded and secure. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hyperswitch@juspay.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaymentExperience } from './PaymentExperience';
import {
    PaymentExperienceFromJSON,
    PaymentExperienceFromJSONTyped,
    PaymentExperienceToJSON,
    PaymentExperienceToJSONTyped,
} from './PaymentExperience';

/**
 * 
 * @export
 * @interface PaymentExperienceTypes
 */
export interface PaymentExperienceTypes {
    /**
     * 
     * @type {PaymentExperience}
     * @memberof PaymentExperienceTypes
     */
    paymentExperienceType?: PaymentExperience | null;
    /**
     * The list of eligible connectors for a given payment experience
     * @type {Array<string>}
     * @memberof PaymentExperienceTypes
     */
    eligibleConnectors: Array<string>;
}



/**
 * Check if a given object implements the PaymentExperienceTypes interface.
 */
export function instanceOfPaymentExperienceTypes(value: object): value is PaymentExperienceTypes {
    if (!('eligibleConnectors' in value) || value['eligibleConnectors'] === undefined) return false;
    return true;
}

export function PaymentExperienceTypesFromJSON(json: any): PaymentExperienceTypes {
    return PaymentExperienceTypesFromJSONTyped(json, false);
}

export function PaymentExperienceTypesFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentExperienceTypes {
    if (json == null) {
        return json;
    }
    return {
        
        'paymentExperienceType': json['payment_experience_type'] == null ? undefined : PaymentExperienceFromJSON(json['payment_experience_type']),
        'eligibleConnectors': json['eligible_connectors'],
    };
}

export function PaymentExperienceTypesToJSON(json: any): PaymentExperienceTypes {
    return PaymentExperienceTypesToJSONTyped(json, false);
}

export function PaymentExperienceTypesToJSONTyped(value?: PaymentExperienceTypes | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'payment_experience_type': PaymentExperienceToJSON(value['paymentExperienceType']),
        'eligible_connectors': value['eligibleConnectors'],
    };
}

