/* tslint:disable */
/* eslint-disable */
/**
 * Hyperswitch - API Documentation
 *  ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app\'s client  |  Never share your secret api keys. Keep them guarded and secure. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hyperswitch@juspay.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UpiData } from './UpiData';
import {
    UpiDataFromJSON,
    UpiDataFromJSONTyped,
    UpiDataToJSON,
    UpiDataToJSONTyped,
} from './UpiData';
import type { BankRedirectData } from './BankRedirectData';
import {
    BankRedirectDataFromJSON,
    BankRedirectDataFromJSONTyped,
    BankRedirectDataToJSON,
    BankRedirectDataToJSONTyped,
} from './BankRedirectData';
import type { CardRedirectData } from './CardRedirectData';
import {
    CardRedirectDataFromJSON,
    CardRedirectDataFromJSONTyped,
    CardRedirectDataToJSON,
    CardRedirectDataToJSONTyped,
} from './CardRedirectData';
import type { CryptoData } from './CryptoData';
import {
    CryptoDataFromJSON,
    CryptoDataFromJSONTyped,
    CryptoDataToJSON,
    CryptoDataToJSONTyped,
} from './CryptoData';
import type { Address } from './Address';
import {
    AddressFromJSON,
    AddressFromJSONTyped,
    AddressToJSON,
    AddressToJSONTyped,
} from './Address';
import type { OpenBankingData } from './OpenBankingData';
import {
    OpenBankingDataFromJSON,
    OpenBankingDataFromJSONTyped,
    OpenBankingDataToJSON,
    OpenBankingDataToJSONTyped,
} from './OpenBankingData';
import type { GiftCardData } from './GiftCardData';
import {
    GiftCardDataFromJSON,
    GiftCardDataFromJSONTyped,
    GiftCardDataToJSON,
    GiftCardDataToJSONTyped,
} from './GiftCardData';
import type { Card } from './Card';
import {
    CardFromJSON,
    CardFromJSONTyped,
    CardToJSON,
    CardToJSONTyped,
} from './Card';
import type { CardToken } from './CardToken';
import {
    CardTokenFromJSON,
    CardTokenFromJSONTyped,
    CardTokenToJSON,
    CardTokenToJSONTyped,
} from './CardToken';
import type { MobilePaymentData } from './MobilePaymentData';
import {
    MobilePaymentDataFromJSON,
    MobilePaymentDataFromJSONTyped,
    MobilePaymentDataToJSON,
    MobilePaymentDataToJSONTyped,
} from './MobilePaymentData';
import type { RealTimePaymentData } from './RealTimePaymentData';
import {
    RealTimePaymentDataFromJSON,
    RealTimePaymentDataFromJSONTyped,
    RealTimePaymentDataToJSON,
    RealTimePaymentDataToJSONTyped,
} from './RealTimePaymentData';
import type { PayLaterData } from './PayLaterData';
import {
    PayLaterDataFromJSON,
    PayLaterDataFromJSONTyped,
    PayLaterDataToJSON,
    PayLaterDataToJSONTyped,
} from './PayLaterData';
import type { VoucherData } from './VoucherData';
import {
    VoucherDataFromJSON,
    VoucherDataFromJSONTyped,
    VoucherDataToJSON,
    VoucherDataToJSONTyped,
} from './VoucherData';
import type { WalletData } from './WalletData';
import {
    WalletDataFromJSON,
    WalletDataFromJSONTyped,
    WalletDataToJSON,
    WalletDataToJSONTyped,
} from './WalletData';
import type { BankTransferData } from './BankTransferData';
import {
    BankTransferDataFromJSON,
    BankTransferDataFromJSONTyped,
    BankTransferDataToJSON,
    BankTransferDataToJSONTyped,
} from './BankTransferData';
import type { BankDebitData } from './BankDebitData';
import {
    BankDebitDataFromJSON,
    BankDebitDataFromJSONTyped,
    BankDebitDataToJSON,
    BankDebitDataToJSONTyped,
} from './BankDebitData';

/**
 * The payment method information provided for making a payment
 * @export
 * @interface PaymentMethodDataRequest
 */
export interface PaymentMethodDataRequest {
    /**
     * 
     * @type {Card}
     * @memberof PaymentMethodDataRequest
     */
    card: Card;
    /**
     * 
     * @type {CardRedirectData}
     * @memberof PaymentMethodDataRequest
     */
    cardRedirect: CardRedirectData;
    /**
     * 
     * @type {WalletData}
     * @memberof PaymentMethodDataRequest
     */
    wallet: WalletData;
    /**
     * 
     * @type {PayLaterData}
     * @memberof PaymentMethodDataRequest
     */
    payLater: PayLaterData;
    /**
     * 
     * @type {BankRedirectData}
     * @memberof PaymentMethodDataRequest
     */
    bankRedirect: BankRedirectData;
    /**
     * 
     * @type {BankDebitData}
     * @memberof PaymentMethodDataRequest
     */
    bankDebit: BankDebitData;
    /**
     * 
     * @type {BankTransferData}
     * @memberof PaymentMethodDataRequest
     */
    bankTransfer: BankTransferData;
    /**
     * 
     * @type {RealTimePaymentData}
     * @memberof PaymentMethodDataRequest
     */
    realTimePayment: RealTimePaymentData;
    /**
     * 
     * @type {CryptoData}
     * @memberof PaymentMethodDataRequest
     */
    crypto: CryptoData;
    /**
     * 
     * @type {UpiData}
     * @memberof PaymentMethodDataRequest
     */
    upi: UpiData;
    /**
     * 
     * @type {VoucherData}
     * @memberof PaymentMethodDataRequest
     */
    voucher: VoucherData;
    /**
     * 
     * @type {GiftCardData}
     * @memberof PaymentMethodDataRequest
     */
    giftCard: GiftCardData;
    /**
     * 
     * @type {CardToken}
     * @memberof PaymentMethodDataRequest
     */
    cardToken: CardToken;
    /**
     * 
     * @type {OpenBankingData}
     * @memberof PaymentMethodDataRequest
     */
    openBanking: OpenBankingData;
    /**
     * 
     * @type {MobilePaymentData}
     * @memberof PaymentMethodDataRequest
     */
    mobilePayment: MobilePaymentData;
    /**
     * 
     * @type {Address}
     * @memberof PaymentMethodDataRequest
     */
    billing?: Address | null;
}

/**
 * Check if a given object implements the PaymentMethodDataRequest interface.
 */
export function instanceOfPaymentMethodDataRequest(value: object): value is PaymentMethodDataRequest {
    if (!('card' in value) || value['card'] === undefined) return false;
    if (!('cardRedirect' in value) || value['cardRedirect'] === undefined) return false;
    if (!('wallet' in value) || value['wallet'] === undefined) return false;
    if (!('payLater' in value) || value['payLater'] === undefined) return false;
    if (!('bankRedirect' in value) || value['bankRedirect'] === undefined) return false;
    if (!('bankDebit' in value) || value['bankDebit'] === undefined) return false;
    if (!('bankTransfer' in value) || value['bankTransfer'] === undefined) return false;
    if (!('realTimePayment' in value) || value['realTimePayment'] === undefined) return false;
    if (!('crypto' in value) || value['crypto'] === undefined) return false;
    if (!('upi' in value) || value['upi'] === undefined) return false;
    if (!('voucher' in value) || value['voucher'] === undefined) return false;
    if (!('giftCard' in value) || value['giftCard'] === undefined) return false;
    if (!('cardToken' in value) || value['cardToken'] === undefined) return false;
    if (!('openBanking' in value) || value['openBanking'] === undefined) return false;
    if (!('mobilePayment' in value) || value['mobilePayment'] === undefined) return false;
    return true;
}

export function PaymentMethodDataRequestFromJSON(json: any): PaymentMethodDataRequest {
    return PaymentMethodDataRequestFromJSONTyped(json, false);
}

export function PaymentMethodDataRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentMethodDataRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'card': CardFromJSON(json['card']),
        'cardRedirect': CardRedirectDataFromJSON(json['card_redirect']),
        'wallet': WalletDataFromJSON(json['wallet']),
        'payLater': PayLaterDataFromJSON(json['pay_later']),
        'bankRedirect': BankRedirectDataFromJSON(json['bank_redirect']),
        'bankDebit': BankDebitDataFromJSON(json['bank_debit']),
        'bankTransfer': BankTransferDataFromJSON(json['bank_transfer']),
        'realTimePayment': RealTimePaymentDataFromJSON(json['real_time_payment']),
        'crypto': CryptoDataFromJSON(json['crypto']),
        'upi': UpiDataFromJSON(json['upi']),
        'voucher': VoucherDataFromJSON(json['voucher']),
        'giftCard': GiftCardDataFromJSON(json['gift_card']),
        'cardToken': CardTokenFromJSON(json['card_token']),
        'openBanking': OpenBankingDataFromJSON(json['open_banking']),
        'mobilePayment': MobilePaymentDataFromJSON(json['mobile_payment']),
        'billing': json['billing'] == null ? undefined : AddressFromJSON(json['billing']),
    };
}

export function PaymentMethodDataRequestToJSON(json: any): PaymentMethodDataRequest {
    return PaymentMethodDataRequestToJSONTyped(json, false);
}

export function PaymentMethodDataRequestToJSONTyped(value?: PaymentMethodDataRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'card': CardToJSON(value['card']),
        'card_redirect': CardRedirectDataToJSON(value['cardRedirect']),
        'wallet': WalletDataToJSON(value['wallet']),
        'pay_later': PayLaterDataToJSON(value['payLater']),
        'bank_redirect': BankRedirectDataToJSON(value['bankRedirect']),
        'bank_debit': BankDebitDataToJSON(value['bankDebit']),
        'bank_transfer': BankTransferDataToJSON(value['bankTransfer']),
        'real_time_payment': RealTimePaymentDataToJSON(value['realTimePayment']),
        'crypto': CryptoDataToJSON(value['crypto']),
        'upi': UpiDataToJSON(value['upi']),
        'voucher': VoucherDataToJSON(value['voucher']),
        'gift_card': GiftCardDataToJSON(value['giftCard']),
        'card_token': CardTokenToJSON(value['cardToken']),
        'open_banking': OpenBankingDataToJSON(value['openBanking']),
        'mobile_payment': MobilePaymentDataToJSON(value['mobilePayment']),
        'billing': AddressToJSON(value['billing']),
    };
}

