/* tslint:disable */
/* eslint-disable */
/**
 * Hyperswitch - API Documentation
 *  ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app\'s client  |  Never share your secret api keys. Keep them guarded and secure. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hyperswitch@juspay.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaymentListConstraints
 */
export interface PaymentListConstraints {
    /**
     * The identifier for customer
     * @type {string}
     * @memberof PaymentListConstraints
     */
    customerId?: string | null;
    /**
     * A cursor for use in pagination, fetch the next list after some object
     * @type {string}
     * @memberof PaymentListConstraints
     */
    startingAfter?: string | null;
    /**
     * A cursor for use in pagination, fetch the previous list before some object
     * @type {string}
     * @memberof PaymentListConstraints
     */
    endingBefore?: string | null;
    /**
     * limit on the number of objects to return
     * @type {number}
     * @memberof PaymentListConstraints
     */
    limit?: number;
    /**
     * The time at which payment is created
     * @type {Date}
     * @memberof PaymentListConstraints
     */
    created?: Date | null;
    /**
     * Time less than the payment created time
     * @type {Date}
     * @memberof PaymentListConstraints
     */
    createdLt?: Date | null;
    /**
     * Time greater than the payment created time
     * @type {Date}
     * @memberof PaymentListConstraints
     */
    createdGt?: Date | null;
    /**
     * Time less than or equals to the payment created time
     * @type {Date}
     * @memberof PaymentListConstraints
     */
    createdLte?: Date | null;
    /**
     * Time greater than or equals to the payment created time
     * @type {Date}
     * @memberof PaymentListConstraints
     */
    createdGte?: Date | null;
}

/**
 * Check if a given object implements the PaymentListConstraints interface.
 */
export function instanceOfPaymentListConstraints(value: object): value is PaymentListConstraints {
    return true;
}

export function PaymentListConstraintsFromJSON(json: any): PaymentListConstraints {
    return PaymentListConstraintsFromJSONTyped(json, false);
}

export function PaymentListConstraintsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentListConstraints {
    if (json == null) {
        return json;
    }
    return {
        
        'customerId': json['customer_id'] == null ? undefined : json['customer_id'],
        'startingAfter': json['starting_after'] == null ? undefined : json['starting_after'],
        'endingBefore': json['ending_before'] == null ? undefined : json['ending_before'],
        'limit': json['limit'] == null ? undefined : json['limit'],
        'created': json['created'] == null ? undefined : (new Date(json['created'])),
        'createdLt': json['created.lt'] == null ? undefined : (new Date(json['created.lt'])),
        'createdGt': json['created.gt'] == null ? undefined : (new Date(json['created.gt'])),
        'createdLte': json['created.lte'] == null ? undefined : (new Date(json['created.lte'])),
        'createdGte': json['created.gte'] == null ? undefined : (new Date(json['created.gte'])),
    };
}

export function PaymentListConstraintsToJSON(json: any): PaymentListConstraints {
    return PaymentListConstraintsToJSONTyped(json, false);
}

export function PaymentListConstraintsToJSONTyped(value?: PaymentListConstraints | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'customer_id': value['customerId'],
        'starting_after': value['startingAfter'],
        'ending_before': value['endingBefore'],
        'limit': value['limit'],
        'created': value['created'] === null ? null : ((value['created'] as any)?.toISOString()),
        'created.lt': value['createdLt'] === null ? null : ((value['createdLt'] as any)?.toISOString()),
        'created.gt': value['createdGt'] === null ? null : ((value['createdGt'] as any)?.toISOString()),
        'created.lte': value['createdLte'] === null ? null : ((value['createdLte'] as any)?.toISOString()),
        'created.gte': value['createdGte'] === null ? null : ((value['createdGte'] as any)?.toISOString()),
    };
}

