/* tslint:disable */
/* eslint-disable */
/**
 * Hyperswitch - API Documentation
 *  ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app\'s client  |  Never share your secret api keys. Keep them guarded and secure. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hyperswitch@juspay.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaymentMethodType } from './PaymentMethodType';
import {
    PaymentMethodTypeFromJSON,
    PaymentMethodTypeFromJSONTyped,
    PaymentMethodTypeToJSON,
    PaymentMethodTypeToJSONTyped,
} from './PaymentMethodType';
import type { Bank } from './Bank';
import {
    BankFromJSON,
    BankFromJSONTyped,
    BankToJSON,
    BankToJSONTyped,
} from './Bank';
import type { CardDetailFromLocker } from './CardDetailFromLocker';
import {
    CardDetailFromLockerFromJSON,
    CardDetailFromLockerFromJSONTyped,
    CardDetailFromLockerToJSON,
    CardDetailFromLockerToJSONTyped,
} from './CardDetailFromLocker';
import type { PaymentMethod } from './PaymentMethod';
import {
    PaymentMethodFromJSON,
    PaymentMethodFromJSONTyped,
    PaymentMethodToJSON,
    PaymentMethodToJSONTyped,
} from './PaymentMethod';
import type { PaymentExperience } from './PaymentExperience';
import {
    PaymentExperienceFromJSON,
    PaymentExperienceFromJSONTyped,
    PaymentExperienceToJSON,
    PaymentExperienceToJSONTyped,
} from './PaymentExperience';

/**
 * 
 * @export
 * @interface PaymentMethodResponse
 */
export interface PaymentMethodResponse {
    /**
     * Unique identifier for a merchant
     * @type {string}
     * @memberof PaymentMethodResponse
     */
    merchantId: string;
    /**
     * The unique identifier of the customer.
     * @type {string}
     * @memberof PaymentMethodResponse
     */
    customerId?: string | null;
    /**
     * The unique identifier of the Payment method
     * @type {string}
     * @memberof PaymentMethodResponse
     */
    paymentMethodId: string;
    /**
     * 
     * @type {PaymentMethod}
     * @memberof PaymentMethodResponse
     */
    paymentMethod: PaymentMethod;
    /**
     * 
     * @type {PaymentMethodType}
     * @memberof PaymentMethodResponse
     */
    paymentMethodType?: PaymentMethodType | null;
    /**
     * 
     * @type {CardDetailFromLocker}
     * @memberof PaymentMethodResponse
     */
    card?: CardDetailFromLocker | null;
    /**
     * Indicates whether the payment method supports recurring payments. Optional.
     * @type {boolean}
     * @memberof PaymentMethodResponse
     */
    recurringEnabled?: boolean | null;
    /**
     * Indicates whether the payment method is eligible for installment payments (e.g., EMI, BNPL). Optional.
     * @type {boolean}
     * @memberof PaymentMethodResponse
     */
    installmentPaymentEnabled?: boolean | null;
    /**
     * Type of payment experience enabled with the connector
     * @type {Array<PaymentExperience>}
     * @memberof PaymentMethodResponse
     */
    paymentExperience?: Array<PaymentExperience> | null;
    /**
     * You can specify up to 50 keys, with key names up to 40 characters long and values up to 500 characters long. Metadata is useful for storing additional, structured information on an object.
     * @type {object}
     * @memberof PaymentMethodResponse
     */
    metadata?: object | null;
    /**
     * A timestamp (ISO 8601 code) that determines when the payment method was created
     * @type {Date}
     * @memberof PaymentMethodResponse
     */
    created?: Date | null;
    /**
     * 
     * @type {Bank}
     * @memberof PaymentMethodResponse
     */
    bankTransfer?: Bank | null;
    /**
     * 
     * @type {Date}
     * @memberof PaymentMethodResponse
     */
    lastUsedAt?: Date | null;
    /**
     * For Client based calls
     * @type {string}
     * @memberof PaymentMethodResponse
     */
    clientSecret?: string | null;
}



/**
 * Check if a given object implements the PaymentMethodResponse interface.
 */
export function instanceOfPaymentMethodResponse(value: object): value is PaymentMethodResponse {
    if (!('merchantId' in value) || value['merchantId'] === undefined) return false;
    if (!('paymentMethodId' in value) || value['paymentMethodId'] === undefined) return false;
    if (!('paymentMethod' in value) || value['paymentMethod'] === undefined) return false;
    return true;
}

export function PaymentMethodResponseFromJSON(json: any): PaymentMethodResponse {
    return PaymentMethodResponseFromJSONTyped(json, false);
}

export function PaymentMethodResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentMethodResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'merchantId': json['merchant_id'],
        'customerId': json['customer_id'] == null ? undefined : json['customer_id'],
        'paymentMethodId': json['payment_method_id'],
        'paymentMethod': PaymentMethodFromJSON(json['payment_method']),
        'paymentMethodType': json['payment_method_type'] == null ? undefined : PaymentMethodTypeFromJSON(json['payment_method_type']),
        'card': json['card'] == null ? undefined : CardDetailFromLockerFromJSON(json['card']),
        'recurringEnabled': json['recurring_enabled'] == null ? undefined : json['recurring_enabled'],
        'installmentPaymentEnabled': json['installment_payment_enabled'] == null ? undefined : json['installment_payment_enabled'],
        'paymentExperience': json['payment_experience'] == null ? undefined : ((json['payment_experience'] as Array<any>).map(PaymentExperienceFromJSON)),
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'created': json['created'] == null ? undefined : (new Date(json['created'])),
        'bankTransfer': json['bank_transfer'] == null ? undefined : BankFromJSON(json['bank_transfer']),
        'lastUsedAt': json['last_used_at'] == null ? undefined : (new Date(json['last_used_at'])),
        'clientSecret': json['client_secret'] == null ? undefined : json['client_secret'],
    };
}

export function PaymentMethodResponseToJSON(json: any): PaymentMethodResponse {
    return PaymentMethodResponseToJSONTyped(json, false);
}

export function PaymentMethodResponseToJSONTyped(value?: PaymentMethodResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'merchant_id': value['merchantId'],
        'customer_id': value['customerId'],
        'payment_method_id': value['paymentMethodId'],
        'payment_method': PaymentMethodToJSON(value['paymentMethod']),
        'payment_method_type': PaymentMethodTypeToJSON(value['paymentMethodType']),
        'card': CardDetailFromLockerToJSON(value['card']),
        'recurring_enabled': value['recurringEnabled'],
        'installment_payment_enabled': value['installmentPaymentEnabled'],
        'payment_experience': value['paymentExperience'] == null ? undefined : ((value['paymentExperience'] as Array<any>).map(PaymentExperienceToJSON)),
        'metadata': value['metadata'],
        'created': value['created'] === null ? null : ((value['created'] as any)?.toISOString()),
        'bank_transfer': BankToJSON(value['bankTransfer']),
        'last_used_at': value['lastUsedAt'] === null ? null : ((value['lastUsedAt'] as any)?.toISOString()),
        'client_secret': value['clientSecret'],
    };
}

