/* tslint:disable */
/* eslint-disable */
/**
 * Hyperswitch - API Documentation
 *  ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app\'s client  |  Never share your secret api keys. Keep them guarded and secure. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hyperswitch@juspay.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaymentProcessingDetailsAtOneOf
 */
export interface PaymentProcessingDetailsAtOneOf {
    /**
     * 
     * @type {string}
     * @memberof PaymentProcessingDetailsAtOneOf
     */
    paymentProcessingCertificate: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentProcessingDetailsAtOneOf
     */
    paymentProcessingCertificateKey: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentProcessingDetailsAtOneOf
     */
    paymentProcessingDetailsAt: PaymentProcessingDetailsAtOneOfPaymentProcessingDetailsAtEnum;
}


/**
 * @export
 */
export const PaymentProcessingDetailsAtOneOfPaymentProcessingDetailsAtEnum = {
    Hyperswitch: 'Hyperswitch'
} as const;
export type PaymentProcessingDetailsAtOneOfPaymentProcessingDetailsAtEnum = typeof PaymentProcessingDetailsAtOneOfPaymentProcessingDetailsAtEnum[keyof typeof PaymentProcessingDetailsAtOneOfPaymentProcessingDetailsAtEnum];


/**
 * Check if a given object implements the PaymentProcessingDetailsAtOneOf interface.
 */
export function instanceOfPaymentProcessingDetailsAtOneOf(value: object): value is PaymentProcessingDetailsAtOneOf {
    if (!('paymentProcessingCertificate' in value) || value['paymentProcessingCertificate'] === undefined) return false;
    if (!('paymentProcessingCertificateKey' in value) || value['paymentProcessingCertificateKey'] === undefined) return false;
    if (!('paymentProcessingDetailsAt' in value) || value['paymentProcessingDetailsAt'] === undefined) return false;
    return true;
}

export function PaymentProcessingDetailsAtOneOfFromJSON(json: any): PaymentProcessingDetailsAtOneOf {
    return PaymentProcessingDetailsAtOneOfFromJSONTyped(json, false);
}

export function PaymentProcessingDetailsAtOneOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentProcessingDetailsAtOneOf {
    if (json == null) {
        return json;
    }
    return {
        
        'paymentProcessingCertificate': json['payment_processing_certificate'],
        'paymentProcessingCertificateKey': json['payment_processing_certificate_key'],
        'paymentProcessingDetailsAt': json['payment_processing_details_at'],
    };
}

export function PaymentProcessingDetailsAtOneOfToJSON(json: any): PaymentProcessingDetailsAtOneOf {
    return PaymentProcessingDetailsAtOneOfToJSONTyped(json, false);
}

export function PaymentProcessingDetailsAtOneOfToJSONTyped(value?: PaymentProcessingDetailsAtOneOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'payment_processing_certificate': value['paymentProcessingCertificate'],
        'payment_processing_certificate_key': value['paymentProcessingCertificateKey'],
        'payment_processing_details_at': value['paymentProcessingDetailsAt'],
    };
}

