/* tslint:disable */
/* eslint-disable */
/**
 * Hyperswitch - API Documentation
 *  ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app\'s client  |  Never share your secret api keys. Keep them guarded and secure. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hyperswitch@juspay.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SdkNextAction } from './SdkNextAction';
import {
    SdkNextActionFromJSON,
    SdkNextActionFromJSONTyped,
    SdkNextActionToJSON,
    SdkNextActionToJSONTyped,
} from './SdkNextAction';

/**
 * 
 * @export
 * @interface PaypalSessionTokenResponse
 */
export interface PaypalSessionTokenResponse {
    /**
     * Name of the connector
     * @type {string}
     * @memberof PaypalSessionTokenResponse
     */
    connector: string;
    /**
     * The session token for PayPal
     * @type {string}
     * @memberof PaypalSessionTokenResponse
     */
    sessionToken: string;
    /**
     * 
     * @type {SdkNextAction}
     * @memberof PaypalSessionTokenResponse
     */
    sdkNextAction: SdkNextAction;
}

/**
 * Check if a given object implements the PaypalSessionTokenResponse interface.
 */
export function instanceOfPaypalSessionTokenResponse(value: object): value is PaypalSessionTokenResponse {
    if (!('connector' in value) || value['connector'] === undefined) return false;
    if (!('sessionToken' in value) || value['sessionToken'] === undefined) return false;
    if (!('sdkNextAction' in value) || value['sdkNextAction'] === undefined) return false;
    return true;
}

export function PaypalSessionTokenResponseFromJSON(json: any): PaypalSessionTokenResponse {
    return PaypalSessionTokenResponseFromJSONTyped(json, false);
}

export function PaypalSessionTokenResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaypalSessionTokenResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'connector': json['connector'],
        'sessionToken': json['session_token'],
        'sdkNextAction': SdkNextActionFromJSON(json['sdk_next_action']),
    };
}

export function PaypalSessionTokenResponseToJSON(json: any): PaypalSessionTokenResponse {
    return PaypalSessionTokenResponseToJSONTyped(json, false);
}

export function PaypalSessionTokenResponseToJSONTyped(value?: PaypalSessionTokenResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'connector': value['connector'],
        'session_token': value['sessionToken'],
        'sdk_next_action': SdkNextActionToJSON(value['sdkNextAction']),
    };
}

