/* tslint:disable */
/* eslint-disable */
/**
 * Hyperswitch - API Documentation
 *  ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app\'s client  |  Never share your secret api keys. Keep them guarded and secure. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hyperswitch@juspay.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SplitRefund } from './SplitRefund';
import {
    SplitRefundFromJSON,
    SplitRefundFromJSONTyped,
    SplitRefundToJSON,
    SplitRefundToJSONTyped,
} from './SplitRefund';
import type { RefundStatus } from './RefundStatus';
import {
    RefundStatusFromJSON,
    RefundStatusFromJSONTyped,
    RefundStatusToJSON,
    RefundStatusToJSONTyped,
} from './RefundStatus';

/**
 * 
 * @export
 * @interface RefundResponse
 */
export interface RefundResponse {
    /**
     * Unique Identifier for the refund
     * @type {string}
     * @memberof RefundResponse
     */
    refundId: string;
    /**
     * The payment id against which refund is initiated
     * @type {string}
     * @memberof RefundResponse
     */
    paymentId: string;
    /**
     * The refund amount, which should be less than or equal to the total payment amount. Amount for the payment in lowest denomination of the currency. (i.e) in cents for USD denomination, in paisa for INR denomination etc
     * @type {number}
     * @memberof RefundResponse
     */
    amount: number;
    /**
     * The three-letter ISO currency code
     * @type {string}
     * @memberof RefundResponse
     */
    currency: string;
    /**
     * 
     * @type {RefundStatus}
     * @memberof RefundResponse
     */
    status: RefundStatus;
    /**
     * An arbitrary string attached to the object. Often useful for displaying to users and your customer support executive
     * @type {string}
     * @memberof RefundResponse
     */
    reason?: string | null;
    /**
     * You can specify up to 50 keys, with key names up to 40 characters long and values up to 500 characters long. Metadata is useful for storing additional, structured information on an object
     * @type {object}
     * @memberof RefundResponse
     */
    metadata?: object | null;
    /**
     * The error message
     * @type {string}
     * @memberof RefundResponse
     */
    errorMessage?: string | null;
    /**
     * The code for the error
     * @type {string}
     * @memberof RefundResponse
     */
    errorCode?: string | null;
    /**
     * Error code unified across the connectors is received here if there was an error while calling connector
     * @type {string}
     * @memberof RefundResponse
     */
    unifiedCode?: string | null;
    /**
     * Error message unified across the connectors is received here if there was an error while calling connector
     * @type {string}
     * @memberof RefundResponse
     */
    unifiedMessage?: string | null;
    /**
     * The timestamp at which refund is created
     * @type {Date}
     * @memberof RefundResponse
     */
    createdAt?: Date | null;
    /**
     * The timestamp at which refund is updated
     * @type {Date}
     * @memberof RefundResponse
     */
    updatedAt?: Date | null;
    /**
     * The connector used for the refund and the corresponding payment
     * @type {string}
     * @memberof RefundResponse
     */
    connector: string;
    /**
     * The id of business profile for this refund
     * @type {string}
     * @memberof RefundResponse
     */
    profileId?: string | null;
    /**
     * The merchant_connector_id of the processor through which this payment went through
     * @type {string}
     * @memberof RefundResponse
     */
    merchantConnectorId?: string | null;
    /**
     * 
     * @type {SplitRefund}
     * @memberof RefundResponse
     */
    splitRefunds?: SplitRefund | null;
    /**
     * Error code received from the issuer in case of failed refunds
     * @type {string}
     * @memberof RefundResponse
     */
    issuerErrorCode?: string | null;
    /**
     * Error message received from the issuer in case of failed refunds
     * @type {string}
     * @memberof RefundResponse
     */
    issuerErrorMessage?: string | null;
}



/**
 * Check if a given object implements the RefundResponse interface.
 */
export function instanceOfRefundResponse(value: object): value is RefundResponse {
    if (!('refundId' in value) || value['refundId'] === undefined) return false;
    if (!('paymentId' in value) || value['paymentId'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('connector' in value) || value['connector'] === undefined) return false;
    return true;
}

export function RefundResponseFromJSON(json: any): RefundResponse {
    return RefundResponseFromJSONTyped(json, false);
}

export function RefundResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RefundResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'refundId': json['refund_id'],
        'paymentId': json['payment_id'],
        'amount': json['amount'],
        'currency': json['currency'],
        'status': RefundStatusFromJSON(json['status']),
        'reason': json['reason'] == null ? undefined : json['reason'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'errorMessage': json['error_message'] == null ? undefined : json['error_message'],
        'errorCode': json['error_code'] == null ? undefined : json['error_code'],
        'unifiedCode': json['unified_code'] == null ? undefined : json['unified_code'],
        'unifiedMessage': json['unified_message'] == null ? undefined : json['unified_message'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'connector': json['connector'],
        'profileId': json['profile_id'] == null ? undefined : json['profile_id'],
        'merchantConnectorId': json['merchant_connector_id'] == null ? undefined : json['merchant_connector_id'],
        'splitRefunds': json['split_refunds'] == null ? undefined : SplitRefundFromJSON(json['split_refunds']),
        'issuerErrorCode': json['issuer_error_code'] == null ? undefined : json['issuer_error_code'],
        'issuerErrorMessage': json['issuer_error_message'] == null ? undefined : json['issuer_error_message'],
    };
}

export function RefundResponseToJSON(json: any): RefundResponse {
    return RefundResponseToJSONTyped(json, false);
}

export function RefundResponseToJSONTyped(value?: RefundResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'refund_id': value['refundId'],
        'payment_id': value['paymentId'],
        'amount': value['amount'],
        'currency': value['currency'],
        'status': RefundStatusToJSON(value['status']),
        'reason': value['reason'],
        'metadata': value['metadata'],
        'error_message': value['errorMessage'],
        'error_code': value['errorCode'],
        'unified_code': value['unifiedCode'],
        'unified_message': value['unifiedMessage'],
        'created_at': value['createdAt'] === null ? null : ((value['createdAt'] as any)?.toISOString()),
        'updated_at': value['updatedAt'] === null ? null : ((value['updatedAt'] as any)?.toISOString()),
        'connector': value['connector'],
        'profile_id': value['profileId'],
        'merchant_connector_id': value['merchantConnectorId'],
        'split_refunds': SplitRefundToJSON(value['splitRefunds']),
        'issuer_error_code': value['issuerErrorCode'],
        'issuer_error_message': value['issuerErrorMessage'],
    };
}

