/* tslint:disable */
/* eslint-disable */
/**
 * Hyperswitch - API Documentation
 *  ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app\'s client  |  Never share your secret api keys. Keep them guarded and secure. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hyperswitch@juspay.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SplitRefund } from './SplitRefund';
import {
    SplitRefundFromJSON,
    SplitRefundFromJSONTyped,
    SplitRefundToJSON,
    SplitRefundToJSONTyped,
} from './SplitRefund';
import type { MerchantConnectorDetailsWrap } from './MerchantConnectorDetailsWrap';
import {
    MerchantConnectorDetailsWrapFromJSON,
    MerchantConnectorDetailsWrapFromJSONTyped,
    MerchantConnectorDetailsWrapToJSON,
    MerchantConnectorDetailsWrapToJSONTyped,
} from './MerchantConnectorDetailsWrap';
import type { RefundType } from './RefundType';
import {
    RefundTypeFromJSON,
    RefundTypeFromJSONTyped,
    RefundTypeToJSON,
    RefundTypeToJSONTyped,
} from './RefundType';

/**
 * 
 * @export
 * @interface RefundRequest
 */
export interface RefundRequest {
    /**
     * The payment id against which refund is to be initiated
     * @type {string}
     * @memberof RefundRequest
     */
    paymentId: string;
    /**
     * Unique Identifier for the Refund. This is to ensure idempotency for multiple partial refunds initiated against the same payment. If this is not passed by the merchant, this field shall be auto generated and provided in the API response. It is recommended to generate uuid(v4) as the refund_id.
     * @type {string}
     * @memberof RefundRequest
     */
    refundId?: string | null;
    /**
     * The identifier for the Merchant Account
     * @type {string}
     * @memberof RefundRequest
     */
    merchantId?: string | null;
    /**
     * Total amount for which the refund is to be initiated. Amount for the payment in lowest denomination of the currency. (i.e) in cents for USD denomination, in paisa for INR denomination etc., If not provided, this will default to the full payment amount
     * @type {number}
     * @memberof RefundRequest
     */
    amount?: number | null;
    /**
     * Reason for the refund. Often useful for displaying to users and your customer support executive. In case the payment went through Stripe, this field needs to be passed with one of these enums: `duplicate`, `fraudulent`, or `requested_by_customer`
     * @type {string}
     * @memberof RefundRequest
     */
    reason?: string | null;
    /**
     * 
     * @type {RefundType}
     * @memberof RefundRequest
     */
    refundType?: RefundType | null;
    /**
     * You can specify up to 50 keys, with key names up to 40 characters long and values up to 500 characters long. Metadata is useful for storing additional, structured information on an object.
     * @type {object}
     * @memberof RefundRequest
     */
    metadata?: object | null;
    /**
     * 
     * @type {MerchantConnectorDetailsWrap}
     * @memberof RefundRequest
     */
    merchantConnectorDetails?: MerchantConnectorDetailsWrap | null;
    /**
     * 
     * @type {SplitRefund}
     * @memberof RefundRequest
     */
    splitRefunds?: SplitRefund | null;
}



/**
 * Check if a given object implements the RefundRequest interface.
 */
export function instanceOfRefundRequest(value: object): value is RefundRequest {
    if (!('paymentId' in value) || value['paymentId'] === undefined) return false;
    return true;
}

export function RefundRequestFromJSON(json: any): RefundRequest {
    return RefundRequestFromJSONTyped(json, false);
}

export function RefundRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RefundRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'paymentId': json['payment_id'],
        'refundId': json['refund_id'] == null ? undefined : json['refund_id'],
        'merchantId': json['merchant_id'] == null ? undefined : json['merchant_id'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'reason': json['reason'] == null ? undefined : json['reason'],
        'refundType': json['refund_type'] == null ? undefined : RefundTypeFromJSON(json['refund_type']),
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'merchantConnectorDetails': json['merchant_connector_details'] == null ? undefined : MerchantConnectorDetailsWrapFromJSON(json['merchant_connector_details']),
        'splitRefunds': json['split_refunds'] == null ? undefined : SplitRefundFromJSON(json['split_refunds']),
    };
}

export function RefundRequestToJSON(json: any): RefundRequest {
    return RefundRequestToJSONTyped(json, false);
}

export function RefundRequestToJSONTyped(value?: RefundRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'payment_id': value['paymentId'],
        'refund_id': value['refundId'],
        'merchant_id': value['merchantId'],
        'amount': value['amount'],
        'reason': value['reason'],
        'refund_type': RefundTypeToJSON(value['refundType']),
        'metadata': value['metadata'],
        'merchant_connector_details': MerchantConnectorDetailsWrapToJSON(value['merchantConnectorDetails']),
        'split_refunds': SplitRefundToJSON(value['splitRefunds']),
    };
}

