/* tslint:disable */
/* eslint-disable */
/**
 * Hyperswitch - API Documentation
 *  ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app\'s client  |  Never share your secret api keys. Keep them guarded and secure. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hyperswitch@juspay.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaymentLinkStatus } from './PaymentLinkStatus';
import {
    PaymentLinkStatusFromJSON,
    PaymentLinkStatusFromJSONTyped,
    PaymentLinkStatusToJSON,
    PaymentLinkStatusToJSONTyped,
} from './PaymentLinkStatus';
import type { Currency } from './Currency';
import {
    CurrencyFromJSON,
    CurrencyFromJSONTyped,
    CurrencyToJSON,
    CurrencyToJSONTyped,
} from './Currency';

/**
 * 
 * @export
 * @interface RetrievePaymentLinkResponse
 */
export interface RetrievePaymentLinkResponse {
    /**
     * Identifier for Payment Link
     * @type {string}
     * @memberof RetrievePaymentLinkResponse
     */
    paymentLinkId: string;
    /**
     * Identifier for Merchant
     * @type {string}
     * @memberof RetrievePaymentLinkResponse
     */
    merchantId: string;
    /**
     * Open payment link (without any security checks and listing SPMs)
     * @type {string}
     * @memberof RetrievePaymentLinkResponse
     */
    linkToPay: string;
    /**
     * The payment amount. Amount for the payment in the lowest denomination of the currency
     * @type {number}
     * @memberof RetrievePaymentLinkResponse
     */
    amount: number;
    /**
     * Date and time of Payment Link creation
     * @type {Date}
     * @memberof RetrievePaymentLinkResponse
     */
    createdAt: Date;
    /**
     * Date and time of Expiration for Payment Link
     * @type {Date}
     * @memberof RetrievePaymentLinkResponse
     */
    expiry?: Date | null;
    /**
     * Description for Payment Link
     * @type {string}
     * @memberof RetrievePaymentLinkResponse
     */
    description?: string | null;
    /**
     * 
     * @type {PaymentLinkStatus}
     * @memberof RetrievePaymentLinkResponse
     */
    status: PaymentLinkStatus;
    /**
     * 
     * @type {Currency}
     * @memberof RetrievePaymentLinkResponse
     */
    currency?: Currency | null;
    /**
     * Secure payment link (with security checks and listing saved payment methods)
     * @type {string}
     * @memberof RetrievePaymentLinkResponse
     */
    secureLink?: string | null;
}



/**
 * Check if a given object implements the RetrievePaymentLinkResponse interface.
 */
export function instanceOfRetrievePaymentLinkResponse(value: object): value is RetrievePaymentLinkResponse {
    if (!('paymentLinkId' in value) || value['paymentLinkId'] === undefined) return false;
    if (!('merchantId' in value) || value['merchantId'] === undefined) return false;
    if (!('linkToPay' in value) || value['linkToPay'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function RetrievePaymentLinkResponseFromJSON(json: any): RetrievePaymentLinkResponse {
    return RetrievePaymentLinkResponseFromJSONTyped(json, false);
}

export function RetrievePaymentLinkResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RetrievePaymentLinkResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'paymentLinkId': json['payment_link_id'],
        'merchantId': json['merchant_id'],
        'linkToPay': json['link_to_pay'],
        'amount': json['amount'],
        'createdAt': (new Date(json['created_at'])),
        'expiry': json['expiry'] == null ? undefined : (new Date(json['expiry'])),
        'description': json['description'] == null ? undefined : json['description'],
        'status': PaymentLinkStatusFromJSON(json['status']),
        'currency': json['currency'] == null ? undefined : CurrencyFromJSON(json['currency']),
        'secureLink': json['secure_link'] == null ? undefined : json['secure_link'],
    };
}

export function RetrievePaymentLinkResponseToJSON(json: any): RetrievePaymentLinkResponse {
    return RetrievePaymentLinkResponseToJSONTyped(json, false);
}

export function RetrievePaymentLinkResponseToJSONTyped(value?: RetrievePaymentLinkResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'payment_link_id': value['paymentLinkId'],
        'merchant_id': value['merchantId'],
        'link_to_pay': value['linkToPay'],
        'amount': value['amount'],
        'created_at': ((value['createdAt']).toISOString()),
        'expiry': value['expiry'] === null ? null : ((value['expiry'] as any)?.toISOString()),
        'description': value['description'],
        'status': PaymentLinkStatusToJSON(value['status']),
        'currency': CurrencyToJSON(value['currency']),
        'secure_link': value['secureLink'],
    };
}

