/* tslint:disable */
/* eslint-disable */
/**
 * Hyperswitch - API Documentation
 *  ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app\'s client  |  Never share your secret api keys. Keep them guarded and secure. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hyperswitch@juspay.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DeRoutableConnectorChoice } from './DeRoutableConnectorChoice';
import {
    DeRoutableConnectorChoiceFromJSON,
    DeRoutableConnectorChoiceFromJSONTyped,
    DeRoutableConnectorChoiceToJSON,
    DeRoutableConnectorChoiceToJSONTyped,
} from './DeRoutableConnectorChoice';

/**
 * 
 * @export
 * @interface RoutingEvaluateRequest
 */
export interface RoutingEvaluateRequest {
    /**
     * 
     * @type {string}
     * @memberof RoutingEvaluateRequest
     */
    createdBy: string;
    /**
     * Parameters that can be used in the routing evaluate request.
     * eg: {"parameters": {
     * "payment_method": {"type": "enum_variant", "value": "card"},
     * "payment_method_type": {"type": "enum_variant", "value": "credit"},
     * "amount": {"type": "number", "value": 10},
     * "currency": {"type": "str_value", "value": "INR"},
     * "authentication_type": {"type": "enum_variant", "value": "three_ds"},
     * "card_bin": {"type": "str_value", "value": "424242"},
     * "capture_method": {"type": "enum_variant", "value": "scheduled"},
     * "business_country": {"type": "str_value", "value": "IN"},
     * "billing_country": {"type": "str_value", "value": "IN"},
     * "business_label": {"type": "str_value", "value": "business_label"},
     * "setup_future_usage": {"type": "enum_variant", "value": "off_session"},
     * "card_network": {"type": "enum_variant", "value": "visa"},
     * "payment_type": {"type": "enum_variant", "value": "recurring_mandate"},
     * "mandate_type": {"type": "enum_variant", "value": "single_use"},
     * "mandate_acceptance_type": {"type": "enum_variant", "value": "online"},
     * "metadata":{"type": "metadata_variant", "value": {"key": "key1", "value": "value1"}}
     * }}
     * @type {object}
     * @memberof RoutingEvaluateRequest
     */
    parameters: object;
    /**
     * 
     * @type {Array<DeRoutableConnectorChoice>}
     * @memberof RoutingEvaluateRequest
     */
    fallbackOutput: Array<DeRoutableConnectorChoice>;
}

/**
 * Check if a given object implements the RoutingEvaluateRequest interface.
 */
export function instanceOfRoutingEvaluateRequest(value: object): value is RoutingEvaluateRequest {
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('parameters' in value) || value['parameters'] === undefined) return false;
    if (!('fallbackOutput' in value) || value['fallbackOutput'] === undefined) return false;
    return true;
}

export function RoutingEvaluateRequestFromJSON(json: any): RoutingEvaluateRequest {
    return RoutingEvaluateRequestFromJSONTyped(json, false);
}

export function RoutingEvaluateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoutingEvaluateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'createdBy': json['created_by'],
        'parameters': json['parameters'],
        'fallbackOutput': ((json['fallback_output'] as Array<any>).map(DeRoutableConnectorChoiceFromJSON)),
    };
}

export function RoutingEvaluateRequestToJSON(json: any): RoutingEvaluateRequest {
    return RoutingEvaluateRequestToJSONTyped(json, false);
}

export function RoutingEvaluateRequestToJSONTyped(value?: RoutingEvaluateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_by': value['createdBy'],
        'parameters': value['parameters'],
        'fallback_output': ((value['fallbackOutput'] as Array<any>).map(DeRoutableConnectorChoiceToJSON)),
    };
}

