/* tslint:disable */
/* eslint-disable */
/**
 * Hyperswitch - API Documentation
 *  ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app\'s client  |  Never share your secret api keys. Keep them guarded and secure. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hyperswitch@juspay.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const SamsungPayAmountFormat = {
    FormatTotalPriceOnly: 'FORMAT_TOTAL_PRICE_ONLY',
    FormatTotalEstimatedAmount: 'FORMAT_TOTAL_ESTIMATED_AMOUNT'
} as const;
export type SamsungPayAmountFormat = typeof SamsungPayAmountFormat[keyof typeof SamsungPayAmountFormat];


export function instanceOfSamsungPayAmountFormat(value: any): boolean {
    for (const key in SamsungPayAmountFormat) {
        if (Object.prototype.hasOwnProperty.call(SamsungPayAmountFormat, key)) {
            if (SamsungPayAmountFormat[key as keyof typeof SamsungPayAmountFormat] === value) {
                return true;
            }
        }
    }
    return false;
}

export function SamsungPayAmountFormatFromJSON(json: any): SamsungPayAmountFormat {
    return SamsungPayAmountFormatFromJSONTyped(json, false);
}

export function SamsungPayAmountFormatFromJSONTyped(json: any, ignoreDiscriminator: boolean): SamsungPayAmountFormat {
    return json as SamsungPayAmountFormat;
}

export function SamsungPayAmountFormatToJSON(value?: SamsungPayAmountFormat | null): any {
    return value as any;
}

export function SamsungPayAmountFormatToJSONTyped(value: any, ignoreDiscriminator: boolean): SamsungPayAmountFormat {
    return value as SamsungPayAmountFormat;
}

