/* tslint:disable */
/* eslint-disable */
/**
 * Hyperswitch - API Documentation
 *  ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app\'s client  |  Never share your secret api keys. Keep them guarded and secure. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hyperswitch@juspay.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GpayShippingAddressParameters } from './GpayShippingAddressParameters';
import {
    GpayShippingAddressParametersFromJSON,
    GpayShippingAddressParametersFromJSONTyped,
    GpayShippingAddressParametersToJSON,
    GpayShippingAddressParametersToJSONTyped,
} from './GpayShippingAddressParameters';
import type { GpayTransactionInfo } from './GpayTransactionInfo';
import {
    GpayTransactionInfoFromJSON,
    GpayTransactionInfoFromJSONTyped,
    GpayTransactionInfoToJSON,
    GpayTransactionInfoToJSONTyped,
} from './GpayTransactionInfo';
import type { GpayMerchantInfo } from './GpayMerchantInfo';
import {
    GpayMerchantInfoFromJSON,
    GpayMerchantInfoFromJSONTyped,
    GpayMerchantInfoToJSON,
    GpayMerchantInfoToJSONTyped,
} from './GpayMerchantInfo';
import type { SdkNextAction } from './SdkNextAction';
import {
    SdkNextActionFromJSON,
    SdkNextActionFromJSONTyped,
    SdkNextActionToJSON,
    SdkNextActionToJSONTyped,
} from './SdkNextAction';
import type { SecretInfoToInitiateSdk } from './SecretInfoToInitiateSdk';
import {
    SecretInfoToInitiateSdkFromJSON,
    SecretInfoToInitiateSdkFromJSONTyped,
    SecretInfoToInitiateSdkToJSON,
    SecretInfoToInitiateSdkToJSONTyped,
} from './SecretInfoToInitiateSdk';
import type { GpayAllowedPaymentMethods } from './GpayAllowedPaymentMethods';
import {
    GpayAllowedPaymentMethodsFromJSON,
    GpayAllowedPaymentMethodsFromJSONTyped,
    GpayAllowedPaymentMethodsToJSON,
    GpayAllowedPaymentMethodsToJSONTyped,
} from './GpayAllowedPaymentMethods';

/**
 * 
 * @export
 * @interface SessionTokenOneOf
 */
export interface SessionTokenOneOf {
    /**
     * Identifier for the delayed session response
     * @type {boolean}
     * @memberof SessionTokenOneOf
     */
    delayedSessionToken: boolean;
    /**
     * The name of the connector
     * @type {string}
     * @memberof SessionTokenOneOf
     */
    connector: string;
    /**
     * 
     * @type {SdkNextAction}
     * @memberof SessionTokenOneOf
     */
    sdkNextAction: SdkNextAction;
    /**
     * 
     * @type {GpayMerchantInfo}
     * @memberof SessionTokenOneOf
     */
    merchantInfo: GpayMerchantInfo;
    /**
     * Is shipping address required
     * @type {boolean}
     * @memberof SessionTokenOneOf
     */
    shippingAddressRequired: boolean;
    /**
     * Is email required
     * @type {boolean}
     * @memberof SessionTokenOneOf
     */
    emailRequired: boolean;
    /**
     * 
     * @type {GpayShippingAddressParameters}
     * @memberof SessionTokenOneOf
     */
    shippingAddressParameters: GpayShippingAddressParameters;
    /**
     * List of the allowed payment meythods
     * @type {Array<GpayAllowedPaymentMethods>}
     * @memberof SessionTokenOneOf
     */
    allowedPaymentMethods: Array<GpayAllowedPaymentMethods>;
    /**
     * 
     * @type {GpayTransactionInfo}
     * @memberof SessionTokenOneOf
     */
    transactionInfo: GpayTransactionInfo;
    /**
     * 
     * @type {SecretInfoToInitiateSdk}
     * @memberof SessionTokenOneOf
     */
    secrets?: SecretInfoToInitiateSdk | null;
    /**
     * 
     * @type {string}
     * @memberof SessionTokenOneOf
     */
    walletName: SessionTokenOneOfWalletNameEnum;
}


/**
 * @export
 */
export const SessionTokenOneOfWalletNameEnum = {
    GooglePay: 'google_pay'
} as const;
export type SessionTokenOneOfWalletNameEnum = typeof SessionTokenOneOfWalletNameEnum[keyof typeof SessionTokenOneOfWalletNameEnum];


/**
 * Check if a given object implements the SessionTokenOneOf interface.
 */
export function instanceOfSessionTokenOneOf(value: object): value is SessionTokenOneOf {
    if (!('delayedSessionToken' in value) || value['delayedSessionToken'] === undefined) return false;
    if (!('connector' in value) || value['connector'] === undefined) return false;
    if (!('sdkNextAction' in value) || value['sdkNextAction'] === undefined) return false;
    if (!('merchantInfo' in value) || value['merchantInfo'] === undefined) return false;
    if (!('shippingAddressRequired' in value) || value['shippingAddressRequired'] === undefined) return false;
    if (!('emailRequired' in value) || value['emailRequired'] === undefined) return false;
    if (!('shippingAddressParameters' in value) || value['shippingAddressParameters'] === undefined) return false;
    if (!('allowedPaymentMethods' in value) || value['allowedPaymentMethods'] === undefined) return false;
    if (!('transactionInfo' in value) || value['transactionInfo'] === undefined) return false;
    if (!('walletName' in value) || value['walletName'] === undefined) return false;
    return true;
}

export function SessionTokenOneOfFromJSON(json: any): SessionTokenOneOf {
    return SessionTokenOneOfFromJSONTyped(json, false);
}

export function SessionTokenOneOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): SessionTokenOneOf {
    if (json == null) {
        return json;
    }
    return {
        
        'delayedSessionToken': json['delayed_session_token'],
        'connector': json['connector'],
        'sdkNextAction': SdkNextActionFromJSON(json['sdk_next_action']),
        'merchantInfo': GpayMerchantInfoFromJSON(json['merchant_info']),
        'shippingAddressRequired': json['shipping_address_required'],
        'emailRequired': json['email_required'],
        'shippingAddressParameters': GpayShippingAddressParametersFromJSON(json['shipping_address_parameters']),
        'allowedPaymentMethods': ((json['allowed_payment_methods'] as Array<any>).map(GpayAllowedPaymentMethodsFromJSON)),
        'transactionInfo': GpayTransactionInfoFromJSON(json['transaction_info']),
        'secrets': json['secrets'] == null ? undefined : SecretInfoToInitiateSdkFromJSON(json['secrets']),
        'walletName': json['wallet_name'],
    };
}

export function SessionTokenOneOfToJSON(json: any): SessionTokenOneOf {
    return SessionTokenOneOfToJSONTyped(json, false);
}

export function SessionTokenOneOfToJSONTyped(value?: SessionTokenOneOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'delayed_session_token': value['delayedSessionToken'],
        'connector': value['connector'],
        'sdk_next_action': SdkNextActionToJSON(value['sdkNextAction']),
        'merchant_info': GpayMerchantInfoToJSON(value['merchantInfo']),
        'shipping_address_required': value['shippingAddressRequired'],
        'email_required': value['emailRequired'],
        'shipping_address_parameters': GpayShippingAddressParametersToJSON(value['shippingAddressParameters']),
        'allowed_payment_methods': ((value['allowedPaymentMethods'] as Array<any>).map(GpayAllowedPaymentMethodsToJSON)),
        'transaction_info': GpayTransactionInfoToJSON(value['transactionInfo']),
        'secrets': SecretInfoToInitiateSdkToJSON(value['secrets']),
        'wallet_name': value['walletName'],
    };
}

