/* tslint:disable */
/* eslint-disable */
/**
 * Hyperswitch - API Documentation
 *  ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app\'s client  |  Never share your secret api keys. Keep them guarded and secure. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hyperswitch@juspay.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Currency } from './Currency';
import {
    CurrencyFromJSON,
    CurrencyFromJSONTyped,
    CurrencyToJSON,
    CurrencyToJSONTyped,
} from './Currency';

/**
 * 
 * @export
 * @interface SessionTokenOneOf6
 */
export interface SessionTokenOneOf6 {
    /**
     * Paze Client ID
     * @type {string}
     * @memberof SessionTokenOneOf6
     */
    clientId: string;
    /**
     * Client Name to be displayed on the Paze screen
     * @type {string}
     * @memberof SessionTokenOneOf6
     */
    clientName: string;
    /**
     * Paze Client Profile ID
     * @type {string}
     * @memberof SessionTokenOneOf6
     */
    clientProfileId: string;
    /**
     * 
     * @type {Currency}
     * @memberof SessionTokenOneOf6
     */
    transactionCurrencyCode: Currency;
    /**
     * The transaction amount
     * @type {string}
     * @memberof SessionTokenOneOf6
     */
    transactionAmount: string;
    /**
     * Email Address
     * @type {string}
     * @memberof SessionTokenOneOf6
     */
    emailAddress?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SessionTokenOneOf6
     */
    walletName: SessionTokenOneOf6WalletNameEnum;
}


/**
 * @export
 */
export const SessionTokenOneOf6WalletNameEnum = {
    Paze: 'paze'
} as const;
export type SessionTokenOneOf6WalletNameEnum = typeof SessionTokenOneOf6WalletNameEnum[keyof typeof SessionTokenOneOf6WalletNameEnum];


/**
 * Check if a given object implements the SessionTokenOneOf6 interface.
 */
export function instanceOfSessionTokenOneOf6(value: object): value is SessionTokenOneOf6 {
    if (!('clientId' in value) || value['clientId'] === undefined) return false;
    if (!('clientName' in value) || value['clientName'] === undefined) return false;
    if (!('clientProfileId' in value) || value['clientProfileId'] === undefined) return false;
    if (!('transactionCurrencyCode' in value) || value['transactionCurrencyCode'] === undefined) return false;
    if (!('transactionAmount' in value) || value['transactionAmount'] === undefined) return false;
    if (!('walletName' in value) || value['walletName'] === undefined) return false;
    return true;
}

export function SessionTokenOneOf6FromJSON(json: any): SessionTokenOneOf6 {
    return SessionTokenOneOf6FromJSONTyped(json, false);
}

export function SessionTokenOneOf6FromJSONTyped(json: any, ignoreDiscriminator: boolean): SessionTokenOneOf6 {
    if (json == null) {
        return json;
    }
    return {
        
        'clientId': json['client_id'],
        'clientName': json['client_name'],
        'clientProfileId': json['client_profile_id'],
        'transactionCurrencyCode': CurrencyFromJSON(json['transaction_currency_code']),
        'transactionAmount': json['transaction_amount'],
        'emailAddress': json['email_address'] == null ? undefined : json['email_address'],
        'walletName': json['wallet_name'],
    };
}

export function SessionTokenOneOf6ToJSON(json: any): SessionTokenOneOf6 {
    return SessionTokenOneOf6ToJSONTyped(json, false);
}

export function SessionTokenOneOf6ToJSONTyped(value?: SessionTokenOneOf6 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'client_id': value['clientId'],
        'client_name': value['clientName'],
        'client_profile_id': value['clientProfileId'],
        'transaction_currency_code': CurrencyToJSON(value['transactionCurrencyCode']),
        'transaction_amount': value['transactionAmount'],
        'email_address': value['emailAddress'],
        'wallet_name': value['walletName'],
    };
}

