/* tslint:disable */
/* eslint-disable */
/**
 * Hyperswitch - API Documentation
 *  ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app\'s client  |  Never share your secret api keys. Keep them guarded and secure. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hyperswitch@juspay.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Enum representing the possible outcomes of the 3DS Decision Rule Engine.
 * @export
 */
export const ThreeDSDecision = {
    NoThreeDs: 'no_three_ds',
    ChallengeRequested: 'challenge_requested',
    ChallengePreferred: 'challenge_preferred',
    ThreeDsExemptionRequestedTra: 'three_ds_exemption_requested_tra',
    ThreeDsExemptionRequestedLowValue: 'three_ds_exemption_requested_low_value',
    IssuerThreeDsExemptionRequested: 'issuer_three_ds_exemption_requested'
} as const;
export type ThreeDSDecision = typeof ThreeDSDecision[keyof typeof ThreeDSDecision];


export function instanceOfThreeDSDecision(value: any): boolean {
    for (const key in ThreeDSDecision) {
        if (Object.prototype.hasOwnProperty.call(ThreeDSDecision, key)) {
            if (ThreeDSDecision[key as keyof typeof ThreeDSDecision] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ThreeDSDecisionFromJSON(json: any): ThreeDSDecision {
    return ThreeDSDecisionFromJSONTyped(json, false);
}

export function ThreeDSDecisionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ThreeDSDecision {
    return json as ThreeDSDecision;
}

export function ThreeDSDecisionToJSON(value?: ThreeDSDecision | null): any {
    return value as any;
}

export function ThreeDSDecisionToJSONTyped(value: any, ignoreDiscriminator: boolean): ThreeDSDecision {
    return value as ThreeDSDecision;
}

