/* tslint:disable */
/* eslint-disable */
/**
 * Hyperswitch - API Documentation
 *  ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app\'s client  |  Never share your secret api keys. Keep them guarded and secure. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hyperswitch@juspay.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { UpiAdditionalDataOneOf } from './UpiAdditionalDataOneOf';
import {
    instanceOfUpiAdditionalDataOneOf,
    UpiAdditionalDataOneOfFromJSON,
    UpiAdditionalDataOneOfFromJSONTyped,
    UpiAdditionalDataOneOfToJSON,
} from './UpiAdditionalDataOneOf';
import type { UpiAdditionalDataOneOf1 } from './UpiAdditionalDataOneOf1';
import {
    instanceOfUpiAdditionalDataOneOf1,
    UpiAdditionalDataOneOf1FromJSON,
    UpiAdditionalDataOneOf1FromJSONTyped,
    UpiAdditionalDataOneOf1ToJSON,
} from './UpiAdditionalDataOneOf1';

/**
 * @type UpiAdditionalData
 * 
 * @export
 */
export type UpiAdditionalData = UpiAdditionalDataOneOf | UpiAdditionalDataOneOf1;

export function UpiAdditionalDataFromJSON(json: any): UpiAdditionalData {
    return UpiAdditionalDataFromJSONTyped(json, false);
}

export function UpiAdditionalDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpiAdditionalData {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfUpiAdditionalDataOneOf(json)) {
        return UpiAdditionalDataOneOfFromJSONTyped(json, true);
    }
    if (instanceOfUpiAdditionalDataOneOf1(json)) {
        return UpiAdditionalDataOneOf1FromJSONTyped(json, true);
    }

    return {} as any;
}

export function UpiAdditionalDataToJSON(json: any): any {
    return UpiAdditionalDataToJSONTyped(json, false);
}

export function UpiAdditionalDataToJSONTyped(value?: UpiAdditionalData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfUpiAdditionalDataOneOf(value)) {
        return UpiAdditionalDataOneOfToJSON(value as UpiAdditionalDataOneOf);
    }
    if (instanceOfUpiAdditionalDataOneOf1(value)) {
        return UpiAdditionalDataOneOf1ToJSON(value as UpiAdditionalDataOneOf1);
    }

    return {};
}

