/* tslint:disable */
/* eslint-disable */
/**
 * Hyperswitch - API Documentation
 *  ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app\'s client  |  Never share your secret api keys. Keep them guarded and secure. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hyperswitch@juspay.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaypalRedirection } from './PaypalRedirection';
import {
    PaypalRedirectionFromJSON,
    PaypalRedirectionFromJSONTyped,
    PaypalRedirectionToJSON,
    PaypalRedirectionToJSONTyped,
} from './PaypalRedirection';

/**
 * 
 * @export
 * @interface WalletDataOneOf21
 */
export interface WalletDataOneOf21 {
    /**
     * 
     * @type {PaypalRedirection}
     * @memberof WalletDataOneOf21
     */
    paypalRedirect: PaypalRedirection;
}

/**
 * Check if a given object implements the WalletDataOneOf21 interface.
 */
export function instanceOfWalletDataOneOf21(value: object): value is WalletDataOneOf21 {
    if (!('paypalRedirect' in value) || value['paypalRedirect'] === undefined) return false;
    return true;
}

export function WalletDataOneOf21FromJSON(json: any): WalletDataOneOf21 {
    return WalletDataOneOf21FromJSONTyped(json, false);
}

export function WalletDataOneOf21FromJSONTyped(json: any, ignoreDiscriminator: boolean): WalletDataOneOf21 {
    if (json == null) {
        return json;
    }
    return {
        
        'paypalRedirect': PaypalRedirectionFromJSON(json['paypal_redirect']),
    };
}

export function WalletDataOneOf21ToJSON(json: any): WalletDataOneOf21 {
    return WalletDataOneOf21ToJSONTyped(json, false);
}

export function WalletDataOneOf21ToJSONTyped(value?: WalletDataOneOf21 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'paypal_redirect': PaypalRedirectionToJSON(value['paypalRedirect']),
    };
}

