# coding: utf-8

"""
    Hyperswitch - API Documentation

     ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app's client  |  Never share your secret api keys. Keep them guarded and secure. 

    The version of the OpenAPI document: 0.1.0
    Contact: hyperswitch@juspay.in
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from hyperswitch.models.acquirer_details import AcquirerDetails
from hyperswitch.models.address import Address
from hyperswitch.models.authentication_connectors import AuthenticationConnectors
from hyperswitch.models.authentication_status import AuthenticationStatus
from hyperswitch.models.browser_information import BrowserInformation
from hyperswitch.models.currency import Currency
from hyperswitch.models.sca_exemption_type import ScaExemptionType
from hyperswitch.models.transaction_status import TransactionStatus
from typing import Optional, Set
from typing_extensions import Self

class AuthenticationSyncResponse(BaseModel):
    """
    AuthenticationSyncResponse
    """ # noqa: E501
    authentication_id: StrictStr = Field(description="The unique identifier for this authentication.")
    merchant_id: StrictStr = Field(description="This is an identifier for the merchant account.")
    status: AuthenticationStatus
    client_secret: Optional[StrictStr] = Field(default=None, description="The client secret for this authentication.")
    amount: StrictInt = Field(description="This Unit struct represents MinorUnit in which core amount works")
    currency: Currency
    authentication_connector: Optional[AuthenticationConnectors] = None
    force_3ds_challenge: Optional[StrictBool] = Field(default=None, description="Whether 3DS challenge was forced.")
    return_url: Optional[StrictStr] = Field(default=None, description="The URL to which the user should be redirected after authentication.")
    created_at: datetime
    profile_id: StrictStr = Field(description="The business profile that is associated with this authentication.")
    psd2_sca_exemption_type: Optional[ScaExemptionType] = None
    acquirer_details: Optional[AcquirerDetails] = None
    threeds_server_transaction_id: Optional[StrictStr] = Field(default=None, description="The unique identifier from the 3DS server.")
    maximum_supported_3ds_version: Optional[StrictStr] = Field(default=None, description="The maximum supported 3DS version.")
    connector_authentication_id: Optional[StrictStr] = Field(default=None, description="The unique identifier from the connector.")
    three_ds_method_data: Optional[StrictStr] = Field(default=None, description="The data required to perform the 3DS method.")
    three_ds_method_url: Optional[StrictStr] = Field(default=None, description="The URL for the 3DS method.")
    message_version: Optional[StrictStr] = Field(default=None, description="The version of the message.")
    connector_metadata: Optional[Any] = Field(default=None, description="The metadata for this authentication.")
    directory_server_id: Optional[StrictStr] = Field(default=None, description="The unique identifier for the directory server.")
    billing: Optional[Address] = None
    shipping: Optional[Address] = None
    browser_information: Optional[BrowserInformation] = None
    email: Optional[StrictStr] = Field(default=None, description="Email.")
    trans_status: Optional[TransactionStatus] = None
    acs_url: Optional[StrictStr] = Field(default=None, description="Access Server URL for challenge submission.")
    challenge_request: Optional[StrictStr] = Field(default=None, description="Challenge request to be sent to acs_url.")
    acs_reference_number: Optional[StrictStr] = Field(default=None, description="Unique identifier assigned by EMVCo.")
    acs_trans_id: Optional[StrictStr] = Field(default=None, description="Unique identifier assigned by the ACS.")
    acs_signed_content: Optional[StrictStr] = Field(default=None, description="JWS object created by the ACS for the ARes message.")
    three_ds_requestor_url: Optional[StrictStr] = Field(default=None, description="Three DS Requestor URL.")
    three_ds_requestor_app_url: Optional[StrictStr] = Field(default=None, description="Merchant app URL for OOB authentication.")
    authentication_value: Optional[StrictStr] = Field(default=None, description="The authentication value for this authentication, only available in case of server to server request. Unavailable in case of client request due to security concern.")
    eci: Optional[StrictStr] = Field(default=None, description="ECI value for this authentication, only available in case of server to server request. Unavailable in case of client request due to security concern.")
    error_message: Optional[StrictStr] = Field(default=None, description="Error message if any.")
    error_code: Optional[StrictStr] = Field(default=None, description="Error code if any.")
    profile_acquirer_id: Optional[StrictStr] = Field(default=None, description="Profile Acquirer ID")
    __properties: ClassVar[List[str]] = ["authentication_id", "merchant_id", "status", "client_secret", "amount", "currency", "authentication_connector", "force_3ds_challenge", "return_url", "created_at", "profile_id", "psd2_sca_exemption_type", "acquirer_details", "threeds_server_transaction_id", "maximum_supported_3ds_version", "connector_authentication_id", "three_ds_method_data", "three_ds_method_url", "message_version", "connector_metadata", "directory_server_id", "billing", "shipping", "browser_information", "email", "trans_status", "acs_url", "challenge_request", "acs_reference_number", "acs_trans_id", "acs_signed_content", "three_ds_requestor_url", "three_ds_requestor_app_url", "authentication_value", "eci", "error_message", "error_code", "profile_acquirer_id"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AuthenticationSyncResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of acquirer_details
        if self.acquirer_details:
            _dict['acquirer_details'] = self.acquirer_details.to_dict()
        # override the default output from pydantic by calling `to_dict()` of billing
        if self.billing:
            _dict['billing'] = self.billing.to_dict()
        # override the default output from pydantic by calling `to_dict()` of shipping
        if self.shipping:
            _dict['shipping'] = self.shipping.to_dict()
        # override the default output from pydantic by calling `to_dict()` of browser_information
        if self.browser_information:
            _dict['browser_information'] = self.browser_information.to_dict()
        # set to None if client_secret (nullable) is None
        # and model_fields_set contains the field
        if self.client_secret is None and "client_secret" in self.model_fields_set:
            _dict['client_secret'] = None

        # set to None if authentication_connector (nullable) is None
        # and model_fields_set contains the field
        if self.authentication_connector is None and "authentication_connector" in self.model_fields_set:
            _dict['authentication_connector'] = None

        # set to None if force_3ds_challenge (nullable) is None
        # and model_fields_set contains the field
        if self.force_3ds_challenge is None and "force_3ds_challenge" in self.model_fields_set:
            _dict['force_3ds_challenge'] = None

        # set to None if return_url (nullable) is None
        # and model_fields_set contains the field
        if self.return_url is None and "return_url" in self.model_fields_set:
            _dict['return_url'] = None

        # set to None if psd2_sca_exemption_type (nullable) is None
        # and model_fields_set contains the field
        if self.psd2_sca_exemption_type is None and "psd2_sca_exemption_type" in self.model_fields_set:
            _dict['psd2_sca_exemption_type'] = None

        # set to None if acquirer_details (nullable) is None
        # and model_fields_set contains the field
        if self.acquirer_details is None and "acquirer_details" in self.model_fields_set:
            _dict['acquirer_details'] = None

        # set to None if threeds_server_transaction_id (nullable) is None
        # and model_fields_set contains the field
        if self.threeds_server_transaction_id is None and "threeds_server_transaction_id" in self.model_fields_set:
            _dict['threeds_server_transaction_id'] = None

        # set to None if maximum_supported_3ds_version (nullable) is None
        # and model_fields_set contains the field
        if self.maximum_supported_3ds_version is None and "maximum_supported_3ds_version" in self.model_fields_set:
            _dict['maximum_supported_3ds_version'] = None

        # set to None if connector_authentication_id (nullable) is None
        # and model_fields_set contains the field
        if self.connector_authentication_id is None and "connector_authentication_id" in self.model_fields_set:
            _dict['connector_authentication_id'] = None

        # set to None if three_ds_method_data (nullable) is None
        # and model_fields_set contains the field
        if self.three_ds_method_data is None and "three_ds_method_data" in self.model_fields_set:
            _dict['three_ds_method_data'] = None

        # set to None if three_ds_method_url (nullable) is None
        # and model_fields_set contains the field
        if self.three_ds_method_url is None and "three_ds_method_url" in self.model_fields_set:
            _dict['three_ds_method_url'] = None

        # set to None if message_version (nullable) is None
        # and model_fields_set contains the field
        if self.message_version is None and "message_version" in self.model_fields_set:
            _dict['message_version'] = None

        # set to None if connector_metadata (nullable) is None
        # and model_fields_set contains the field
        if self.connector_metadata is None and "connector_metadata" in self.model_fields_set:
            _dict['connector_metadata'] = None

        # set to None if directory_server_id (nullable) is None
        # and model_fields_set contains the field
        if self.directory_server_id is None and "directory_server_id" in self.model_fields_set:
            _dict['directory_server_id'] = None

        # set to None if billing (nullable) is None
        # and model_fields_set contains the field
        if self.billing is None and "billing" in self.model_fields_set:
            _dict['billing'] = None

        # set to None if shipping (nullable) is None
        # and model_fields_set contains the field
        if self.shipping is None and "shipping" in self.model_fields_set:
            _dict['shipping'] = None

        # set to None if browser_information (nullable) is None
        # and model_fields_set contains the field
        if self.browser_information is None and "browser_information" in self.model_fields_set:
            _dict['browser_information'] = None

        # set to None if email (nullable) is None
        # and model_fields_set contains the field
        if self.email is None and "email" in self.model_fields_set:
            _dict['email'] = None

        # set to None if trans_status (nullable) is None
        # and model_fields_set contains the field
        if self.trans_status is None and "trans_status" in self.model_fields_set:
            _dict['trans_status'] = None

        # set to None if acs_url (nullable) is None
        # and model_fields_set contains the field
        if self.acs_url is None and "acs_url" in self.model_fields_set:
            _dict['acs_url'] = None

        # set to None if challenge_request (nullable) is None
        # and model_fields_set contains the field
        if self.challenge_request is None and "challenge_request" in self.model_fields_set:
            _dict['challenge_request'] = None

        # set to None if acs_reference_number (nullable) is None
        # and model_fields_set contains the field
        if self.acs_reference_number is None and "acs_reference_number" in self.model_fields_set:
            _dict['acs_reference_number'] = None

        # set to None if acs_trans_id (nullable) is None
        # and model_fields_set contains the field
        if self.acs_trans_id is None and "acs_trans_id" in self.model_fields_set:
            _dict['acs_trans_id'] = None

        # set to None if acs_signed_content (nullable) is None
        # and model_fields_set contains the field
        if self.acs_signed_content is None and "acs_signed_content" in self.model_fields_set:
            _dict['acs_signed_content'] = None

        # set to None if three_ds_requestor_url (nullable) is None
        # and model_fields_set contains the field
        if self.three_ds_requestor_url is None and "three_ds_requestor_url" in self.model_fields_set:
            _dict['three_ds_requestor_url'] = None

        # set to None if three_ds_requestor_app_url (nullable) is None
        # and model_fields_set contains the field
        if self.three_ds_requestor_app_url is None and "three_ds_requestor_app_url" in self.model_fields_set:
            _dict['three_ds_requestor_app_url'] = None

        # set to None if authentication_value (nullable) is None
        # and model_fields_set contains the field
        if self.authentication_value is None and "authentication_value" in self.model_fields_set:
            _dict['authentication_value'] = None

        # set to None if eci (nullable) is None
        # and model_fields_set contains the field
        if self.eci is None and "eci" in self.model_fields_set:
            _dict['eci'] = None

        # set to None if error_message (nullable) is None
        # and model_fields_set contains the field
        if self.error_message is None and "error_message" in self.model_fields_set:
            _dict['error_message'] = None

        # set to None if error_code (nullable) is None
        # and model_fields_set contains the field
        if self.error_code is None and "error_code" in self.model_fields_set:
            _dict['error_code'] = None

        # set to None if profile_acquirer_id (nullable) is None
        # and model_fields_set contains the field
        if self.profile_acquirer_id is None and "profile_acquirer_id" in self.model_fields_set:
            _dict['profile_acquirer_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AuthenticationSyncResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "authentication_id": obj.get("authentication_id"),
            "merchant_id": obj.get("merchant_id"),
            "status": obj.get("status"),
            "client_secret": obj.get("client_secret"),
            "amount": obj.get("amount"),
            "currency": obj.get("currency"),
            "authentication_connector": obj.get("authentication_connector"),
            "force_3ds_challenge": obj.get("force_3ds_challenge"),
            "return_url": obj.get("return_url"),
            "created_at": obj.get("created_at"),
            "profile_id": obj.get("profile_id"),
            "psd2_sca_exemption_type": obj.get("psd2_sca_exemption_type"),
            "acquirer_details": AcquirerDetails.from_dict(obj["acquirer_details"]) if obj.get("acquirer_details") is not None else None,
            "threeds_server_transaction_id": obj.get("threeds_server_transaction_id"),
            "maximum_supported_3ds_version": obj.get("maximum_supported_3ds_version"),
            "connector_authentication_id": obj.get("connector_authentication_id"),
            "three_ds_method_data": obj.get("three_ds_method_data"),
            "three_ds_method_url": obj.get("three_ds_method_url"),
            "message_version": obj.get("message_version"),
            "connector_metadata": obj.get("connector_metadata"),
            "directory_server_id": obj.get("directory_server_id"),
            "billing": Address.from_dict(obj["billing"]) if obj.get("billing") is not None else None,
            "shipping": Address.from_dict(obj["shipping"]) if obj.get("shipping") is not None else None,
            "browser_information": BrowserInformation.from_dict(obj["browser_information"]) if obj.get("browser_information") is not None else None,
            "email": obj.get("email"),
            "trans_status": obj.get("trans_status"),
            "acs_url": obj.get("acs_url"),
            "challenge_request": obj.get("challenge_request"),
            "acs_reference_number": obj.get("acs_reference_number"),
            "acs_trans_id": obj.get("acs_trans_id"),
            "acs_signed_content": obj.get("acs_signed_content"),
            "three_ds_requestor_url": obj.get("three_ds_requestor_url"),
            "three_ds_requestor_app_url": obj.get("three_ds_requestor_app_url"),
            "authentication_value": obj.get("authentication_value"),
            "eci": obj.get("eci"),
            "error_message": obj.get("error_message"),
            "error_code": obj.get("error_code"),
            "profile_acquirer_id": obj.get("profile_acquirer_id")
        })
        return _obj


