# coding: utf-8

"""
    Hyperswitch - API Documentation

     ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app's client  |  Never share your secret api keys. Keep them guarded and secure. 

    The version of the OpenAPI document: 0.1.0
    Contact: hyperswitch@juspay.in
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from hyperswitch.models.acquirer_details import AcquirerDetails
from hyperswitch.models.authentication_connectors import AuthenticationConnectors
from hyperswitch.models.currency import Currency
from hyperswitch.models.customer_details import CustomerDetails
from hyperswitch.models.sca_exemption_type import ScaExemptionType
from typing import Optional, Set
from typing_extensions import Self

class AuthenticationCreateRequest(BaseModel):
    """
    AuthenticationCreateRequest
    """ # noqa: E501
    authentication_id: Optional[StrictStr] = Field(default=None, description="The unique identifier for this authentication.")
    profile_id: Optional[StrictStr] = Field(default=None, description="The business profile that is associated with this authentication")
    customer: Optional[CustomerDetails] = None
    amount: StrictInt = Field(description="This Unit struct represents MinorUnit in which core amount works")
    authentication_connector: Optional[AuthenticationConnectors] = None
    currency: Currency
    return_url: Optional[StrictStr] = Field(default=None, description="The URL to which the user should be redirected after authentication.")
    force_3ds_challenge: Optional[StrictBool] = Field(default=None, description="Force 3DS challenge.")
    psd2_sca_exemption_type: Optional[ScaExemptionType] = None
    profile_acquirer_id: Optional[StrictStr] = Field(default=None, description="Profile Acquirer ID get from profile acquirer configuration")
    acquirer_details: Optional[AcquirerDetails] = None
    __properties: ClassVar[List[str]] = ["authentication_id", "profile_id", "customer", "amount", "authentication_connector", "currency", "return_url", "force_3ds_challenge", "psd2_sca_exemption_type", "profile_acquirer_id", "acquirer_details"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AuthenticationCreateRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of customer
        if self.customer:
            _dict['customer'] = self.customer.to_dict()
        # override the default output from pydantic by calling `to_dict()` of acquirer_details
        if self.acquirer_details:
            _dict['acquirer_details'] = self.acquirer_details.to_dict()
        # set to None if authentication_id (nullable) is None
        # and model_fields_set contains the field
        if self.authentication_id is None and "authentication_id" in self.model_fields_set:
            _dict['authentication_id'] = None

        # set to None if profile_id (nullable) is None
        # and model_fields_set contains the field
        if self.profile_id is None and "profile_id" in self.model_fields_set:
            _dict['profile_id'] = None

        # set to None if customer (nullable) is None
        # and model_fields_set contains the field
        if self.customer is None and "customer" in self.model_fields_set:
            _dict['customer'] = None

        # set to None if authentication_connector (nullable) is None
        # and model_fields_set contains the field
        if self.authentication_connector is None and "authentication_connector" in self.model_fields_set:
            _dict['authentication_connector'] = None

        # set to None if return_url (nullable) is None
        # and model_fields_set contains the field
        if self.return_url is None and "return_url" in self.model_fields_set:
            _dict['return_url'] = None

        # set to None if force_3ds_challenge (nullable) is None
        # and model_fields_set contains the field
        if self.force_3ds_challenge is None and "force_3ds_challenge" in self.model_fields_set:
            _dict['force_3ds_challenge'] = None

        # set to None if psd2_sca_exemption_type (nullable) is None
        # and model_fields_set contains the field
        if self.psd2_sca_exemption_type is None and "psd2_sca_exemption_type" in self.model_fields_set:
            _dict['psd2_sca_exemption_type'] = None

        # set to None if profile_acquirer_id (nullable) is None
        # and model_fields_set contains the field
        if self.profile_acquirer_id is None and "profile_acquirer_id" in self.model_fields_set:
            _dict['profile_acquirer_id'] = None

        # set to None if acquirer_details (nullable) is None
        # and model_fields_set contains the field
        if self.acquirer_details is None and "acquirer_details" in self.model_fields_set:
            _dict['acquirer_details'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AuthenticationCreateRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "authentication_id": obj.get("authentication_id"),
            "profile_id": obj.get("profile_id"),
            "customer": CustomerDetails.from_dict(obj["customer"]) if obj.get("customer") is not None else None,
            "amount": obj.get("amount"),
            "authentication_connector": obj.get("authentication_connector"),
            "currency": obj.get("currency"),
            "return_url": obj.get("return_url"),
            "force_3ds_challenge": obj.get("force_3ds_challenge"),
            "psd2_sca_exemption_type": obj.get("psd2_sca_exemption_type"),
            "profile_acquirer_id": obj.get("profile_acquirer_id"),
            "acquirer_details": AcquirerDetails.from_dict(obj["acquirer_details"]) if obj.get("acquirer_details") is not None else None
        })
        return _obj


