# coding: utf-8

"""
    Hyperswitch - API Documentation

     ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app's client  |  Never share your secret api keys. Keep them guarded and secure. 

    The version of the OpenAPI document: 0.1.0
    Contact: hyperswitch@juspay.in
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from hyperswitch.models.decision_engine_gateway_wise_extra_score import DecisionEngineGatewayWiseExtraScore
from hyperswitch.models.decision_engine_sr_sub_level_input_config import DecisionEngineSRSubLevelInputConfig
from typing import Optional, Set
from typing_extensions import Self

class DecisionEngineSuccessRateData(BaseModel):
    """
    DecisionEngineSuccessRateData
    """ # noqa: E501
    default_latency_threshold: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="defaultLatencyThreshold")
    default_bucket_size: Optional[StrictInt] = Field(default=None, alias="defaultBucketSize")
    default_hedging_percent: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="defaultHedgingPercent")
    default_lower_reset_factor: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="defaultLowerResetFactor")
    default_upper_reset_factor: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="defaultUpperResetFactor")
    default_gateway_extra_score: Optional[List[DecisionEngineGatewayWiseExtraScore]] = Field(default=None, alias="defaultGatewayExtraScore")
    sub_level_input_config: Optional[List[DecisionEngineSRSubLevelInputConfig]] = Field(default=None, alias="subLevelInputConfig")
    __properties: ClassVar[List[str]] = ["defaultLatencyThreshold", "defaultBucketSize", "defaultHedgingPercent", "defaultLowerResetFactor", "defaultUpperResetFactor", "defaultGatewayExtraScore", "subLevelInputConfig"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DecisionEngineSuccessRateData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in default_gateway_extra_score (list)
        _items = []
        if self.default_gateway_extra_score:
            for _item_default_gateway_extra_score in self.default_gateway_extra_score:
                if _item_default_gateway_extra_score:
                    _items.append(_item_default_gateway_extra_score.to_dict())
            _dict['defaultGatewayExtraScore'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in sub_level_input_config (list)
        _items = []
        if self.sub_level_input_config:
            for _item_sub_level_input_config in self.sub_level_input_config:
                if _item_sub_level_input_config:
                    _items.append(_item_sub_level_input_config.to_dict())
            _dict['subLevelInputConfig'] = _items
        # set to None if default_latency_threshold (nullable) is None
        # and model_fields_set contains the field
        if self.default_latency_threshold is None and "default_latency_threshold" in self.model_fields_set:
            _dict['defaultLatencyThreshold'] = None

        # set to None if default_bucket_size (nullable) is None
        # and model_fields_set contains the field
        if self.default_bucket_size is None and "default_bucket_size" in self.model_fields_set:
            _dict['defaultBucketSize'] = None

        # set to None if default_hedging_percent (nullable) is None
        # and model_fields_set contains the field
        if self.default_hedging_percent is None and "default_hedging_percent" in self.model_fields_set:
            _dict['defaultHedgingPercent'] = None

        # set to None if default_lower_reset_factor (nullable) is None
        # and model_fields_set contains the field
        if self.default_lower_reset_factor is None and "default_lower_reset_factor" in self.model_fields_set:
            _dict['defaultLowerResetFactor'] = None

        # set to None if default_upper_reset_factor (nullable) is None
        # and model_fields_set contains the field
        if self.default_upper_reset_factor is None and "default_upper_reset_factor" in self.model_fields_set:
            _dict['defaultUpperResetFactor'] = None

        # set to None if default_gateway_extra_score (nullable) is None
        # and model_fields_set contains the field
        if self.default_gateway_extra_score is None and "default_gateway_extra_score" in self.model_fields_set:
            _dict['defaultGatewayExtraScore'] = None

        # set to None if sub_level_input_config (nullable) is None
        # and model_fields_set contains the field
        if self.sub_level_input_config is None and "sub_level_input_config" in self.model_fields_set:
            _dict['subLevelInputConfig'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DecisionEngineSuccessRateData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "defaultLatencyThreshold": obj.get("defaultLatencyThreshold"),
            "defaultBucketSize": obj.get("defaultBucketSize"),
            "defaultHedgingPercent": obj.get("defaultHedgingPercent"),
            "defaultLowerResetFactor": obj.get("defaultLowerResetFactor"),
            "defaultUpperResetFactor": obj.get("defaultUpperResetFactor"),
            "defaultGatewayExtraScore": [DecisionEngineGatewayWiseExtraScore.from_dict(_item) for _item in obj["defaultGatewayExtraScore"]] if obj.get("defaultGatewayExtraScore") is not None else None,
            "subLevelInputConfig": [DecisionEngineSRSubLevelInputConfig.from_dict(_item) for _item in obj["subLevelInputConfig"]] if obj.get("subLevelInputConfig") is not None else None
        })
        return _obj


