# coding: utf-8

"""
    Hyperswitch - API Documentation

     ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app's client  |  Never share your secret api keys. Keep them guarded and secure. 

    The version of the OpenAPI document: 0.1.0
    Contact: hyperswitch@juspay.in
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from hyperswitch.models.merchant_connector_details_wrap import MerchantConnectorDetailsWrap
from typing import Optional, Set
from typing_extensions import Self

class PaymentsCaptureRequest(BaseModel):
    """
    PaymentsCaptureRequest
    """ # noqa: E501
    merchant_id: Optional[StrictStr] = Field(default=None, description="The unique identifier for the merchant. This is usually inferred from the API key.")
    amount_to_capture: Optional[StrictInt] = Field(default=None, description="The amount to capture, in the lowest denomination of the currency. If omitted, the entire `amount_capturable` of the payment will be captured. Must be less than or equal to the current `amount_capturable`.")
    refund_uncaptured_amount: Optional[StrictBool] = Field(default=None, description="Decider to refund the uncaptured amount. (Currently not fully supported or behavior may vary by connector).")
    statement_descriptor_suffix: Optional[StrictStr] = Field(default=None, description="A dynamic suffix that appears on your customer's credit card statement. This is concatenated with the (shortened) descriptor prefix set on your account to form the complete statement descriptor. The combined length should not exceed connector-specific limits (typically 22 characters).")
    statement_descriptor_prefix: Optional[StrictStr] = Field(default=None, description="An optional prefix for the statement descriptor that appears on your customer's credit card statement. This can override the default prefix set on your merchant account. The combined length of prefix and suffix should not exceed connector-specific limits (typically 22 characters).")
    merchant_connector_details: Optional[MerchantConnectorDetailsWrap] = None
    __properties: ClassVar[List[str]] = ["merchant_id", "amount_to_capture", "refund_uncaptured_amount", "statement_descriptor_suffix", "statement_descriptor_prefix", "merchant_connector_details"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PaymentsCaptureRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of merchant_connector_details
        if self.merchant_connector_details:
            _dict['merchant_connector_details'] = self.merchant_connector_details.to_dict()
        # set to None if merchant_id (nullable) is None
        # and model_fields_set contains the field
        if self.merchant_id is None and "merchant_id" in self.model_fields_set:
            _dict['merchant_id'] = None

        # set to None if amount_to_capture (nullable) is None
        # and model_fields_set contains the field
        if self.amount_to_capture is None and "amount_to_capture" in self.model_fields_set:
            _dict['amount_to_capture'] = None

        # set to None if refund_uncaptured_amount (nullable) is None
        # and model_fields_set contains the field
        if self.refund_uncaptured_amount is None and "refund_uncaptured_amount" in self.model_fields_set:
            _dict['refund_uncaptured_amount'] = None

        # set to None if statement_descriptor_suffix (nullable) is None
        # and model_fields_set contains the field
        if self.statement_descriptor_suffix is None and "statement_descriptor_suffix" in self.model_fields_set:
            _dict['statement_descriptor_suffix'] = None

        # set to None if statement_descriptor_prefix (nullable) is None
        # and model_fields_set contains the field
        if self.statement_descriptor_prefix is None and "statement_descriptor_prefix" in self.model_fields_set:
            _dict['statement_descriptor_prefix'] = None

        # set to None if merchant_connector_details (nullable) is None
        # and model_fields_set contains the field
        if self.merchant_connector_details is None and "merchant_connector_details" in self.model_fields_set:
            _dict['merchant_connector_details'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PaymentsCaptureRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "merchant_id": obj.get("merchant_id"),
            "amount_to_capture": obj.get("amount_to_capture"),
            "refund_uncaptured_amount": obj.get("refund_uncaptured_amount"),
            "statement_descriptor_suffix": obj.get("statement_descriptor_suffix"),
            "statement_descriptor_prefix": obj.get("statement_descriptor_prefix"),
            "merchant_connector_details": MerchantConnectorDetailsWrap.from_dict(obj["merchant_connector_details"]) if obj.get("merchant_connector_details") is not None else None
        })
        return _obj


